### ISSUE TITLE
Add task for deleting a collection

### ISSUE THREAD

**Issue by rjrudin** [marklogic-community/ml-gradle#159]
Use DMSDK for this so no modules are required

**Comment by rjrudin** [comment]
Targeting this for 4.0.0 once ML9 and Java Client 4.0.0 are officially released

**Comment by sanjuthomas** [comment]
Interested to learn DMSDK, @rjrudin I can pick this up if you can give me a reference.

**Comment by sastafford** [comment]
https://github.com/sastafford/marklogic-spring-batch/blob/master/infrastructure/src/main/java/com/marklogic/spring/batch/item/tasklet/DeleteDocumentsTasklet.java

**Comment by rjrudin** [comment]
Thanks @sanjuthomas - I need to give this a little thought, as I'm thinking a separate project may be in order here that contains reusable DMSDK chunks of code. This issue would still stay here, as we'd then add a Gradle task to reuse the code.

For example, something like this would be nice:

new DeleteCollectionsCommand(DatabaseClient, "coll1", "coll2", "etc").execute()

And then the Gradle task would simply execute code like that, and you could run it like this:

gradle mlDeleteCollections -Pcollections=coll1,coll2,etc

What I don't want to do is put a lot of code into Gradle tasks, because then it can't be reused and it's more difficult to test.

**Comment by sanjuthomas** [comment]
@rjrudin Happy to contribute to DMSDK module that you are planning. DMSDK familiarity will help me in the consulting projects.

**Comment by rjrudin** [comment]
Added via #216 - https://github.com/marklogic-community/ml-gradle/wiki/DMSDK-Tasks
