### ISSUE TITLE
Add scaffolding to generate a stub ml-gradle project

### ISSUE THREAD

**Issue by paxtonhare** [marklogic-community/ml-gradle#166]
Roxy has the `ml new` command.

I'd like to be able to create a new, stubbed ml-gradle project easily. Right now I have to.
- find an existing build.gradle
- copy contents into my new project dir
- mkdir a bunch of directories to house my xqy or sjs code

Help a lazy guy out.

**Comment by sastafford** [comment]
I think there are already some scaffolding tasks.
Run "gradle tasks"
There are some other scaffolding tasks to create transforms and resources
gradle mlCreateResource


 
 
  On Thu, Mar 2, 2017 at 1:17 PM, Paxton Hare<notifications@github.com> wrote:   
Roxy has the ml new command.

I'd like to be able to create a new, stubbed ml-gradle project easily. Right now I have to.
   
   - find an existing build.gradle
   - copy contents into my new project dir
   - mkdir a bunch of directories to house my xqy or sjs code

Help a lazy guy out.

**Comment by hansenmc** [comment]
What about something like this? An init script that defines an `mlNewProject` task that will create the project folder in the present working directory(if it doesn't already have one), and copy the specified example project files: build.gradle, gradle.properties, and README.md if they exist.

If the user were to place a gradle file in one of the init locations i.e.: `USER_HOME/.gradle/init.d/ml-gradle.gradle` then it would always be available and could be invoked from anywhere. 

The Spring project has [instructions for installing such scripts](https://github.com/spring-projects/gradle-init-scripts#or-download-via-command-line). You could also add a task to this init script that refreshes itself and updates from the github site, to make it easier to keep it updated. 

Example invocation that would create a project named "foo" and use the "ml-gradle/examples/corb2-project" as a template: 
    
    gradle mlNewProject -PmlAppName=foo -PmlTemplate=corb2

```
allprojects {
  afterEvaluate { project ->
    if (!tasks.findByName('mlNewProject')) {
      task mlNewProject << {
        if (new File('build.gradle').exists()) {
            println "There is already a gradle project here!"
        } else {
            def projectDir = new File("${mlAppName}")
            if (!projectDir.exists()) {
                println "Creating new project ${mlAppName}"
                projectDir.mkdir()
                ['build.gradle', 'gradle.properties', 'README.md'].each {
                    //allows user to choose which ml-gradle example project to load (doesn't crawl the folder)
                    def projectTemplate = project.getProperty("mlTemplate") ?: "minimal"
                    def content = new URL ("https://raw.githubusercontent.com/rjrudin/ml-gradle/master/examples/${projectTemplate}-project/${it}")
                    HttpURLConnection con = (HttpURLConnection) content.openConnection();
                    con.setRequestMethod("HEAD")
                    if (con.getResponseCode() == 200) {
                      new File("${mlAppName}/${it}") << content.getText()
                    }
                }
                //update the project property name (or create new file)
                ant.propertyfile(file: "${mlAppName}/gradle.properties") {
                    entry( key: "mlAppName", value: "${mlAppName}")
                }
            } else {
              println "${mlAppName} already exists"
            }
        }
      }
    }
  }
}

```

**Comment by rjrudin** [comment]
Dropping this from 2.7.0 for now as I think #182 gets us 80% of the way there - i.e. you can have a Gradle init script in your home directory that uses 2.7.0 and lets you run mlNewProject.

**Comment by RobertSzkutak** [comment]
+1 on this. It would be good to see mlNewProject build all the JSON scaffolding for a project because its not always clear how to modify the JSON resources after they've been deployed.

**Comment by popzip** [comment]
@rjrudin what is the 20% left on this?

**Comment by rjrudin** [comment]
Closing, as I think between mlScaffold and DHF's hubInit, we have enough of an answer.
