### ISSUE TITLE
Convert Roxy configuration to ml-gradle configuration

### ISSUE THREAD

**Issue by rjrudin** [marklogic-community/ml-gradle#169]
This is primarily an exercise in mapping the contents of Roxy's config file into a set of Management REST API-compliant payloads. I think a 100% complete mapping isn't practical, but getting the major things - databases, app servers, security resources - would take care of the bulk of the work of doing a conversion. Mapping the properties should be not difficult, though a 100% complete mapping may also not be practical.

**Comment by sanjuthomas** [comment]
@rjrudin I can help if you can do a task breakdown. Is this going to be a utility jar or something similar?

**Comment by rjrudin** [comment]
Thanks @sanjuthomas . Let me start a feature branch for this so I can lay out some plumbing for it. I'd like to make a command-like open/closed design so that it's easy for someone to plug in their own "adapters" for converting REST API config to files.

**Comment by sanjuthomas** [comment]
@rjrudin do we have this feature branch ready?

**Comment by rjrudin** [comment]
@sanjuthomas The "feature/export-api" branch in ml-app-deployer has the progress so far, as does the "feature/export-api" in ml-gradle too. The task is invoked like this:

    g -PpropertiesFile=build/export.properties mlExportResources

And the properties file looks like this (other keys are possible):

    servers=sample-app
    users=myApp-admin,myApp-reader,myApp-writer
    roles=myApp-admin,myApp-internal

**Comment by rjrudin** [comment]
Here's the Export API that can be used for this - https://github.com/marklogic-community/ml-gradle/wiki/Exporting-resources

There's still the matter of converting Roxy properties.

**Comment by rjrudin** [comment]
Closing this in favor of #194 , which has a plan for how to accomplish this.
