### ISSUE TITLE
Provide example project for running Roxy tests

### ISSUE THREAD

**Issue by rjrudin** [marklogic-community/ml-gradle#178]
This should be a straightforward matter:

1. Toss the Roxy test code under src/main/ml-modules, or alternatively under src/test/ml-modules
1. Configure an appserver for running tests that points to a test database
1. Run tests

**Comment by jamesagardner** [comment]
I have included an mlRoxyTest target as well as a roxy-test-project example that does the above.

Can this be assigned to me so I can generate a push request associated witht his issue?

**Comment by hansenmc** [comment]
You can submit a pull request from a feature branch if you push to a clone of this repo under your account. No assignment or permissions necessary. Not that you shouldn’t have contribute rights, but that is the normal means of submitting a PR.

**Comment by rjrudin** [comment]
What @hansenmc  said

**Comment by jamesagardner** [comment]
Submitted pull request #249

**Comment by rjrudin** [comment]
This is being addressed via the new unit-test-example project
