### ISSUE TITLE
Add task for sharing a project

### ISSUE THREAD

**Issue by rjrudin** [marklogic-community/ml-gradle#181]
Can zip/tar up the ml-gradle-specific parts of a project - build.gradle, gradle.properties, the gradle wrapper if it exists, and config and modules

**Comment by dmcassel** [comment]
is this to support handing off as a deliverable to a customer?

**Comment by rjrudin** [comment]
The original intent was to allow for debugging ml-gradle projects, but a need for this just hasn't come up. Closing.
