### ISSUE TITLE
No-op defaults and interactive initialization

### ISSUE THREAD

**Issue by jmakeig** [marklogic-community/ml-gradle#182]
As a new user, ml-gradle does too much magically by default. The baseline defaults are very sensible, but they do too much without any indication of what’s about to happen with `mlDeploy` or what are the knobs and levers I need to affect that. Once I need to do more (or less) than the defaults, I fall off a cliff (and have had to almost completely re-learn it each of the 3 or 4 times I’ve had to do it).

Rather than start a project from a default config, I’d much prefer the tool start with zero config and a special `init` command that could build up a config for me. Since this is only a one-time task it could be interactive, like `npm init`. (In fact, comparing `package.json` to the questions that `npm init` asked was a great way for me to learn how npm worked early in my journey.)

Pseudo-shell:
```shell
> gradle mlInit
> Project name:
…
> Create a database? y (y/N)
…
> How many forests? 4
…
> Create a REST app server? y (y/N)
…
> App server port? 8003
```

This is kind of related to #166.

**Comment by rjrudin** [comment]
Definitely doable. Would just be a task in ml-gradle initially, I don't think there's any need to add this to ml-app-deployer yet.

**Comment by jmakeig** [comment]
> Definitely doable

…but desirable? What do others think?

**Comment by hansenmc** [comment]
I don't mind the magic defaults, but it would be nice to get a list of them all.

Whether we have an interactive task that prompts the first time you create a project, and/or it can be invoked manually, it would be nice if those sensible defaults(or currently configured values) are available when the interactive prompts ask for a value. The sane default or currently configured value is presented and used if the user simply hits enter (i.e. Create a REST app server? [y])

This could be achieved using ANT [input](https://ant.apache.org/manual/Tasks/input.html):
  
    ant.input(addProperty: 'createRest', message: "Create a REST app server? ", defaultvalue: 'Y')

So, the user could choose to accept those sensible defaults by simply hitting enter (or running with `--non-interactive` to generate with all of the defaults).

A task that exports all of the properties and saves to the `build.properties` or groovy file would provide a baseline config file that could be versioned with those explicit properties listed and managed under version control.

**Comment by rjrudin** [comment]
Ran into an immediate problem - reading from the Console requires running Gradle with --no-daemon on the command line, and even then, I was having problems getting the "question" to print out cleanly without overlapping with Gradle logging. Sad!

**Comment by rjrudin** [comment]
Figured out how to do this, ant.input is the way to go.

**Comment by rjrudin** [comment]
mlNewProject now exists
