### ISSUE TITLE
Regression, 2.6.0 mlLoadSchemas

### ISSUE THREAD

**Issue by grechaw** [marklogic-community/ml-gradle#191]
Maybe just something backward incompatible happened.

I had a normal setup for loading TDE and schemas in to the database.  in 2.6.0, mlLoadSchemas reports seeing the right directory, but loads nothing from that directory.

I reverted to 2.5.0 and everything works as before.

Feel free to follow up with more questions and repro-- I would expect this issue is pretty obvious if it's indeed a regression as I've found.

**Comment by grechaw** [comment]
Now that I've seen issue #160, maybe it's that schemas are loaded from subdirs, but not the direct child of ml-schemas.  

.. I must be missing something, even artifacts from the subdirectories are not loaded.

**Comment by rjrudin** [comment]
@grechaw Can you describe your directory structure with filenames? Maybe it's a file extension issue?

Here's the sample directory that the tests in ml-javaclient-util use:

https://github.com/rjrudin/ml-javaclient-util/tree/master/src/test/resources/schemas

**Comment by rjrudin** [comment]
@grechaw I reproduced this in the schemas-project in ml-gradle - trying to figure out why it works fine in the ml-app-deployer test but not in ml-gradle

**Comment by rjrudin** [comment]
@grechaw I found the issue - when Gradle runs in daemon mode, the "Files.walkTree" method uses the Gradle daemon directory as the starting path. Very odd. Working on a fix.

**Comment by rjrudin** [comment]
Yup, running with "--no-daemon" results in the files being loaded correctly

**Comment by grechaw** [comment]
Whoa that's a wack bug.

**Comment by rjrudin** [comment]
Fixed in ml-javaclient-util - https://github.com/marklogic-community/ml-javaclient-util/commit/16e0fb4283ac034dd562306134b78434c8e7279c
