### ISSUE TITLE
Discontinue reliance on .tdex .tdej extensions for extraction templates

### ISSUE THREAD

**Issue by grechaw** [marklogic-community/ml-gradle#192]
Currently, in 2.6.0, artifacts from the schemas directory don't seem to load at all.

PM requests that we no longer depend on tdex, tdej in ml-gradle and ml-app-deployer for how to load extraction templates.  We've had some discussion about where to put extraction templates, including

`src/main/ml-schemas/tde`
and 
`src/main/tde`

This issue is to track the change in design and implementation.

**Comment by rjrudin** [comment]
I'll go with src/main/ml-schemas/tde for 2.7.0. Easy to support that in the future in addition to some other solution we may come up with.

**Comment by rjrudin** [comment]
Addressed in ml-javaclient-util (ignore hacky logging in there, I forgot to do a merge squash into dev and caught some sausage-making) - https://github.com/marklogic-community/ml-javaclient-util/commit/883bd6bf617b2ec7341b8b2515c5471c3e63764f

**Comment by rjrudin** [comment]
Added note at https://github.com/marklogic-community/ml-gradle/wiki/Loading-schemas
