### ISSUE TITLE
XDMP-FORESTOPINs during Undo ConfigureForestReplicasCommand

### ISSUE THREAD

**Issue by mflatscher** [marklogic-community/ml-gradle#196]
Teardown/undeploy of HA clusters seems brittle under ml-gradle 2.7.0 and late versions of ML8 due to intermittent `XDMP-FORESTOPIN: xdmp:forest-delete(as:forest-id("6683516993176664786")) -- Forest [forestName] has a shutdown operation in progress`.

Would it be feasible to add retries for this particular condition, or is FORESTOPIN too flakey to assume that the forest will be back shortly?

**Comment by rjrudin** [comment]
Thanks for the notice @mflatscher - I haven't had a chance to reproduce this yet. The way a database is deleted changed in 2.7.0 to accommodate how custom forests are created (the forests are detached, then the primary forests are all deleted, which transitively includes replicas), and that should be the best way to delete forests, but I don't think I reworked this command to use the same approach too.

**Comment by rjrudin** [comment]
Just reproduced this locally, going to investigate further

**Comment by rjrudin** [comment]
Using the retry approach for a fix - the error is caught, then the code waits 500ms and tries again, up to 3 retries. This works reliably. I'm not sure why the error occurs yet, doing some investigation on that too, but the fix will at least ensure the forest still gets deleted and undeploy finishes.

**Comment by rjrudin** [comment]
Interesting - realized in the process that replicas can be easily created via the "forest-replica" field of a forest payload - the Manage API will create any replica that doesn't exist yet. I'm on ML9, will confirm that's true for ML8 too.

**Comment by rjrudin** [comment]
This was fixed in ml-app-deployer, 2.8.0 release coming momentarily
