### ISSUE TITLE
Add support for ML9 Element Level Security

### ISSUE THREAD

**Issue by rjrudin** [marklogic-community/ml-gradle#199]
http://docs.marklogic.com/REST/GET/manage/v2/protected-paths

http://docs.marklogic.com/REST/GET/manage/v2/query-rolesets

**Comment by rjrudin** [comment]
These should be straightforward to add in ml-app-deployer, along with adding "mlDeployProtectedPaths" and "mlDeployQueryRolesets" in ml-gradle. 

DeployUsersCommand in ml-app-deployer should be a good example to follow (though I don't know if the admin user is required for these or not).

**Comment by millerbill3** [comment]
Hey Rob,
I'll take a stab at implementing this.

**Comment by miguelrgonzalez** [comment]
Hi Bill,
Would you mind picking another one?

I'm half done with this one.

Cheers,
Miguel

**Comment by millerbill3** [comment]
Sure @miguelrgonzalez I'll see if there's something else I can work on.

**Comment by erismank** [comment]
Would it be possible to get a rough estimate on completion of this task? I need to do some work in the next couple of weeks that will require adding a custom gradle task to call MarkLogic API endpoints directly to add protected paths and query rolesets. But if support for ML9 Element Level Security is almost finished, I would want to use ml-gradle instead.

**Comment by rjrudin** [comment]
We've had some issues with supporting updates - turns out the ID of a roleset is based on all of its properties, and thus it's impossible to know what roleset to delete when a roleset is updated (essentially, there's no concept of an update). 

@miguelrgonzalez Thoughts on a PR?

**Comment by miguelrgonzalez** [comment]
it should be ready early next week.

**Comment by miguelrgonzalez** [comment]
@rjrudin 
PR is up : https://github.com/marklogic-community/ml-app-deployer/pull/196

Let me know what's the procedure to sync up with ml-gradle

**Comment by rjrudin** [comment]
@erismank I just realized that this support exists since version 3.1.0, there are just aren't specific Gradle tasks for deploying just these resources. I'll add that as part of this ticket.

**Comment by rjrudin** [comment]
@erismank There are some samples of protected paths and query rolesets at https://github.com/marklogic-community/ml-app-deployer/tree/master/src/test/resources/sample-app/src/main/ml-config/security

**Comment by rjrudin** [comment]
@erismank I take that back about the support existing - the commands for deploying protected paths and query rolesets are present, but they're not registered with the "mlDeploy" task. Fixing that in 3.3.0, which will be out this week.

**Comment by rjrudin** [comment]
Support for these is in 3.3.0 - they're also listed on the new Resource reference page - https://github.com/marklogic-community/ml-gradle/wiki/Resource-reference .
