### ISSUE TITLE
kerberos ticket authentication fails at the end

### ISSUE THREAD

**Issue by praveenray** [marklogic-community/ml-gradle#200]
Create a new project with kerberos ticket. This can be done by editing src/main/ml-config/servers/rest-api-server.json:

`{
  "server-name": "%%NAME%%",
  "internal-security": false,
  "external-security": "Kerberos-1",
  "authentication": "kerberos-ticket"
}`

Run gradle mlDeploy. This ends with an error message: 
`Unable to read REST configuration from file: C:\projects\ml\src\main\ml-modules\rest-properties.json.`
Although the file rest-properties.json is present in correct location.

Changing authentication to 'digestbasic' works properly.
Running with –debug shows ‘PUT to http://localhost:9002/v1/config/properties’ failing towards the end (9002 is the new app server port). It’s because the app server is now setup with Kerberos?

**Comment by rjrudin** [comment]
@praveenray Was this on ML8 or ML9?

**Comment by praveenray** [comment]
ML 9

**Comment by rjrudin** [comment]
I hopefully will have a fix for this in 3.0.0. I'm reworking all the code in ml-app-deployer that constructs a new DatabaseClient to use the new SecurityContext interface in 4.0.x of the Java Client API. And there'll be properties to control which SecurityContext impl is used. So you should have precise control over this.

**Comment by rjrudin** [comment]
See the new properties that will be supported in 3.0.0 - https://github.com/marklogic-community/ml-gradle/wiki/Property-reference#rest-api-server-connection-properties

**Comment by rjrudin** [comment]
Basic, Digest, Certificate, and Kerberos authentication should all be easily configurable via the new properties in 3.0.0 as defined above in the Property Reference.
