### ISSUE TITLE
PKIX Path Building Failure with mlManageScheme=https

### ISSUE THREAD

**Issue by gku11ava** [marklogic-community/ml-gradle#201]
ml gradle version: 2.7.0
gradle version: 3.5
OS: CentOS 7
MarkLogic: 8.0-6.4

Manage and Admin ports have SSL enabled.   mlAdminScheme and mlManageScheme = https with mlSimpleSsl = true.  

mlDeploy fails with PKIX Path Building Failure on GET to https://localhost:8002/manage/v2/groups

Script works when 8002 is not behind SSL and mlManageScheme=http.

 
> I/O error on GET request for "https://localhost:8002/manage/v2/groups": sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target; nested exception is javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

Info Output
Executing command [com.marklogic.appdeployer.command.groups.DeployGroupsCommand] with sort order [5]
Processing files in directory: /home/gkullava/KeepAlive/src/main/ml-config/groups
Processing file: /home/gkullava/KeepAlive/src/main/ml-config/groups/default-group.json
Sending XML GET request as user with admin role 'admin' to path: /manage/v2/groups
:mlDeployApp FAILED
:mlDeployApp (Thread[Daemon worker Thread 2,5,main]) completed. Took 0.01 secs.

Debug Output
10:11:56.602 [INFO] [com.marklogic.appdeployer.impl.SimpleAppDeployer] Executing command [com.marklogic.appdeployer.command.group
s.DeployGroupsCommand] with sort order [5]
10:11:56.602 [INFO] [com.marklogic.appdeployer.command.groups.DeployGroupsCommand] Processing files in directory: /home/gkullava/
KeepAlive/src/main/ml-config/groups
10:11:56.602 [INFO] [com.marklogic.appdeployer.command.groups.DeployGroupsCommand] Processing file: /home/gkullava/KeepAlive/src/
main/ml-config/groups/default-group.json
10:11:56.602 [INFO] [com.marklogic.mgmt.ManageClient] Sending XML GET request as user with admin role 'admin' to path: /manage/v2
/groups
10:11:56.602 [DEBUG] [org.springframework.web.client.RestTemplate] Created GET request for "https://localhost:8002/manage/v2/grou
ps"
10:11:56.602 [DEBUG] [org.springframework.web.client.RestTemplate] Setting request Accept header to [text/plain, application/json
, application/*+json, */*]
10:11:56.603 [DEBUG] [org.apache.http.client.protocol.RequestAddCookies] CookieSpec selected: best-match
10:11:56.603 [DEBUG] [org.apache.http.client.protocol.RequestAuthCache] Auth cache not set in the context
10:11:56.603 [DEBUG] [org.apache.http.impl.conn.PoolingHttpClientConnectionManager] Connection request: [route: {s}->https://loca
lhost:8002][total kept alive: 0; route allocated: 0 of 2; total allocated: 0 of 20]
10:11:56.603 [DEBUG] [org.apache.http.impl.conn.PoolingHttpClientConnectionManager] Connection leased: [id: 29][route: {s}->https
://localhost:8002][total kept alive: 0; route allocated: 1 of 2; total allocated: 1 of 20]
10:11:56.603 [DEBUG] [org.apache.http.impl.execchain.MainClientExec] Opening connection {s}->https://localhost:8002
10:11:56.603 [DEBUG] [org.apache.http.impl.conn.HttpClientConnectionOperator] Connecting to localhost/127.0.0.1:8002
10:11:56.611 [DEBUG] [org.apache.http.impl.conn.DefaultManagedHttpClientConnection] http-outgoing-29: Shutdown connection
10:11:56.611 [DEBUG] [org.apache.http.impl.execchain.MainClientExec] Connection discarded
10:11:56.611 [DEBUG] [org.apache.http.impl.conn.DefaultManagedHttpClientConnection] http-outgoing-29: Close connection

**Comment by rjrudin** [comment]
For now, I think you need to call setRestTemplate and setAdminRestTemplate on the ManageClient object, which is under the property name mlManageClient. You can do this in an ext block in build.gradle.

The RestTemplate needs to be configured for SSL access. Google has some results for this, and this one is interesting because it doesn't actually involve RestTemplate at all - http://garciapl.blogspot.com/2012/09/spring-rest-template-with-ssl.html

I'll give some thought as to how to make this easier to configure. But let me know if the above works.

**Comment by rjrudin** [comment]
Just to confirm - you have certificate templates configured for the Admin and Manage servers on 8001/8002?

**Comment by gku11ava** [comment]
Thanks.  I'll give it a shot.
Both Admin and Manage servers have certificate templates.
I also had App-Services on SSL as well, but turned that off early in the debugging.

**Comment by gku11ava** [comment]
Now working with the following additions to build.gradle:

import org.apache.http.conn.ssl.TrustStrategy;
import java.security.cert.X509Certificate;

class SimpleStrategy implements TrustStrategy {
  public SimpleStrategy() {
  }

  public boolean isTrusted(X509Certificate[] chain, String authType) {
    return true;
  }  
}

ext {
  def manageConfig = mlManageClient.getManageConfig()
  // Use TrustSelfSignedStrategy instead?
  def strategy = new SimpleStrategy()
  def context = new org.apache.http.conn.ssl.SSLContextBuilder().loadTrustMaterial(null, strategy).build()
  //ALLOW_ALL_HOSTNAME_VERIFIER added because my hostname of my VMs changed slightly
  //when I switched to a public AP over lunch  
  def socketFactory = new org.apache.http.conn.ssl.SSLConnectionSocketFactory(context,
      org.apache.http.conn.ssl.SSLConnectionSocketFactory.ALLOW_ALL_HOSTNAME_VERIFIER)
  def scope = new org.apache.http.auth.AuthScope(mlAppConfig.getHost(), 8002, org.apache.http.auth.AuthScope.ANY_REALM)
  def credentials = new org.apache.http.auth.UsernamePasswordCredentials(manageConfig.getAdminUsername(), manageConfig.getAdminPassword())
  def provider = new org.apache.http.impl.client.BasicCredentialsProvider()
  provider.setCredentials(scope, credentials)
  def sslClient = org.apache.http.impl.client.HttpClients.custom().setDefaultCredentialsProvider(provider).setSSLSocketFactory(socketFactory).build()
  def restTemplate = mlManageClient.getRestTemplate()
  restTemplate.getRequestFactory().setHttpClient(sslClient)
  mlManageClient.setRestTemplate(restTemplate)
  mlManageClient.setAdminRestTemplate(restTemplate)
}

Probably should update ml-app-deployer RestTemplateUtil to include constructor that allows customization of SSL context?

**Comment by rjrudin** [comment]
Yes, will update ml-app-deployer

**Comment by rjrudin** [comment]
I'm adding "mlManageSimpleSsl" and "mlAdminSimpleSsl" properties to enable a very simple SSLContext on each RestTemplate instance.

**Comment by rjrudin** [comment]
Will be supported via - https://github.com/marklogic-community/ml-app-deployer/issues/182

**Comment by rjrudin** [comment]
Some docs - https://github.com/marklogic-community/ml-gradle/wiki/SSL-with-Manage-and-Admin-servers
