### ISSUE TITLE
Super Databases issue on mlDeploy

### ISSUE THREAD

**Issue by hgarrow** [marklogic-community/ml-gradle#204]
Attempting to deploy a super database in one step fails if the super database itself does not already exist.  If the super database exists, the mlDeploy works without issue.

Here is the simplest configuration for testing:

```
src/main/ml-config/databases/1-my-firstsub.json
{
  "database-name" : "my-firstsub"
}

src/main/ml-config/databases/2-my-nextsub.json
{
  "database-name" : "my-nextsub"
}

src/main/ml-config/databases/6-my-documents.json
{
  "database-name" : "my-documents",
  "subdatabase" : [ {
    "database-name" : "my-firstsub"
  }, {
    "database-name" : "my-nextsub"
  } ]
}
```

**Comment by rjrudin** [comment]
There's a PR in ml-app-deployer that should address this, but I'd like to get 3.0.0 out the door and toss this into 3.1.0.

**Comment by rjrudin** [comment]
Version 3.1.0 has support for sub-databases. There's a test in ml-app-deployer that uses the following configuration files for deploying sub-databases, this should address this issue:

https://github.com/marklogic-community/ml-app-deployer/tree/dev/src/test/resources/sample-app/subdatabases/databases
