### ISSUE TITLE
"hourly" and "monthly" are not supported when creating a scheduled task

### ISSUE THREAD

**Issue by praveenray** [marklogic-community/ml-gradle#208]
Following file in the ml-config/tasks/my-task.xml :
```
     <task-properties xmlns="http://marklogic.com/manage">
         <task-enabled>false</task-enabled>
         <task-path>/lib/my-task.xqy</task-path>
         <task-root>/</task-root>
         <task-type>minutely</task-type>
         <task-period>720</task-period>
         <task-database>%%NAME%%-content</task-database>
         <task-modules>%%NAME%%-modules</task-modules>
         <task-user>admin</task-user>
    </task-properties>
```
Running mlDeploy creates this task but it's enabled.

Another issue is task-type. 'daily' or 'hourly' don't work at all. mlDeploy errors out.
This is on ML9 Windows (both server and mlDeploy command).

**Comment by rjrudin** [comment]
For enabled, try making the same call with curl. I believe you'll get the same behavior, as the manage API doesn't support creating a new task that's disabled.

For hourly and monthly - try creating the task manually with the admin ui and then use the manage API on 8002 to inspect the JSON or xml for the task.

**Comment by rjrudin** [comment]
I believe "task-enabled" simply isn't supported when a task is created - the Admin UI doesn't allow it either. 

I was able to reproduce "hourly" and "monthly" not working; this seems like a product bug. I've labeled it as such and will file a bug with MarkLogic.

**Comment by rjrudin** [comment]
Captured as bug 46629

**Comment by rjrudin** [comment]
Just verified this isn't fixed yet in 9.0-2

**Comment by xquery** [comment]
The issue here is that there is no defined task-start-time ... this causes internals of REST API to bork with little indication of why (generic MANAGE-INVALIDPAYLOAD with no information). I will add some more error messaging and provide some reasonable defaults.

**Comment by rjrudin** [comment]
Confirming the following:

1. task-enabled=false isn't supported by ML when a scheduled task is created
1. The fix for the task-type is to include a task-start-time
