### ISSUE TITLE
make plugin as single jar to avoid issues with dependencies when running the tasks

### ISSUE THREAD

**Issue by divino** [marklogic-community/ml-gradle#211]
This is just a proposal and I am not sure if fatjars can work for gradle plugins. I think it would be nicer if users doesn't need to specify dependencies for the plugin anymore.

**Comment by rjrudin** [comment]
I'm not sure what you mean by "doesn't need to specify dependencies for the plugin anymore". The only thing a user has to specify is:

    plugins { id "com.marklogic.ml-gradle" version "2.8.0" }

The user doesn't need to worry about any dependencies.

**Comment by rjrudin** [comment]
@divino I'm closing this for now. It would be helpful to see some examples of dependency issues that folks are running into before investigating fat jar or "shadow" jar support.

**Comment by divino** [comment]
I encountered this but I cannot recreate it anymore. Probably about a specific task. I solved it by adding:

buildscript.dependencies.classpath 'com.fasterxml.jackson.core:jackson-core:2.5.0'
