### ISSUE TITLE
export users should allow setting of default password

### ISSUE THREAD

**Issue by divino** [marklogic-community/ml-gradle#213]
This will make user export usable right away for importing.

**Comment by rjrudin** [comment]
I'm wondering if a user needs to specify something, or if the exported file can simply contain e.g. 

    "password": "CHANGEME"

My guess is it isn't often that all the users will have the same password. And I think the main benefit here is that by adding the password element/key, it's a lot easier for a user to change the value to the correct one. 

If we do allow for a default value, that changes the Exporter API a bit, as we now need to define a context map of keys/values that can be passed to every Exporter when the "export(File path)" method is called. We'd now have "export(File path, Map<String, Object> context)". Of course, that would probably have future utility by allowing for any keys/values to be passed into any exporter. 

So thoughts on simply adding a default value vs allowing a user to pick a default value?

**Comment by rjrudin** [comment]
Note too that if we only add a default value, this change will be made completely in ml-app-deployer. If we allow a user to specify a default value, we'll need to modify ml-gradle too to look for a particular command-line property.

**Comment by rjrudin** [comment]
Password defaults to "CHANGEME"
