### ISSUE TITLE
should handle proper ordering of deployment of roles

### ISSUE THREAD

**Issue by divino** [marklogic-community/ml-gradle#214]
right now, we still have to edit the role names to make sure that parents goes first before child roles.

**Comment by sastafford** [comment]
prefix the file name with a number with the order that you want to load your roles, will load in sorted order.

**Comment by divino** [comment]
sorry, that is what I mean by "editing the role name" ... I really meant editing the filenames.

**Comment by divino** [comment]
accidentally closed the ticket

**Comment by rjrudin** [comment]
If supported, this change would be made in ml-app-deployer.

**Comment by rjrudin** [comment]
This defaults to true - mlSortRolesByDependencies can be used to disable it.
