### ISSUE TITLE
Setting up multiproject sample

### ISSUE THREAD

**Issue by peetkes** [marklogic-community/ml-gradle#215]
Hi, 

Just tried setting up a multiproject project where the ml-gradle project is a subproject. When I then try to run ./gradlew :mlproject:mlDeploy -i I only get the standard rest servers for the application, my extra servers don't get installed, triggers don't get installed and some more items are not installed.
It seems that when you run the deployment from the root project the plugin does not honor the subproject paths.
Is that by design?
If I run the deployment from within the subproject, it will work.
My root project _build.gradle_ has this:
`
plugins {
    id 'net.saliman.properties' version '1.4.6'
}
`
`
group "nn.mmm"
version "1.0-SNAPSHOT"
`

My root settings.gradle has this:
`rootProject.name = 'nnn-datahub'
include 'api'
include 'ml-datahub'
`
My ml-datahub has the usual stuff from ml-gradle

**Comment by rjrudin** [comment]
ml-gradle finds files to deploy based on the values of mlConfigPath and mlModulePaths. These defaults to src/main/ml-config and src/main/ml-modules. So if you run an ml-gradle task from the parent directory, and the "src" directory is under a child directory, none of the files will be found.

In order for the files to be found, either mlConfigPath and mlModulePaths need to be overridden to take into account the child directory, or the ml-gradle tasks should be run from the child directory.

**Comment by peetkes** [comment]
Cool, thanks for the explanation!
