### ISSUE TITLE
Issue  while using mlModulePaths for new path other than the default path.

### ISSUE THREAD

**Issue by saths-github** [marklogic-community/ml-gradle#223]
Hi,

While using gradle to deploy Marklogic into my LocalHost using the "mlModulePaths=src/main/dev/ml-modules" as the new path, the gradle refers the default module path as "src/main/ml-modules". 

Copied from the log :
Loading modules into test server from dir: src/main/ml-modules

Executing task ':printHost' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
mlHost: localhost
mlConfigPath: src/main/dev/ml-config
mlModulePaths: src/main/dev/ml-modules
:printHost (Thread[Daemon worker Thread 28,5,main]) completed. Took 0.001 secs.

The command line is as follows, gradle -PenvironmentName=local -i mlLoadModules printHost > gradle_mlModulePaths_LOG

Attached the screen shot and the log. 

[gradle_mlModulePaths_LOG.txt](https://github.com/marklogic-community/ml-gradle/files/1194377/gradle_mlModulePaths_LOG.txt)
![mlmodulepaths_screen_shot](https://user-images.githubusercontent.com/19993602/28880969-3a1d685c-77c4-11e7-8bd4-e0a525f15078.png)

Thanks
SathishS

**Comment by rjrudin** [comment]
How are you setting mlModulePaths? I'm on a project right now that sets this in gradle.properties, and the logging shown when mlLoadModules is invoked is correct:

    # from gradle.properties
    mlModulePaths=build/mlRestApi/obfuscated/ml-modules,src/main/xqy

Also, what version of ml-gradle are you using?

**Comment by saths-github** [comment]
Hi,
Thanks for the response.
Following is the set of lines copied from my gradle.properties,
mlGradleDependency=com.rjrudin:ml-gradle:2.0b+
# mlSimpleSsl=true
mlAppName=wbcoder
mlHost=localhost
mlUsername=admin
mlPassword=admin
mlRestPort=8030
mlXdbcPort=8031
mlTestRestPort=8033
mlTestXdbcPort=8034
mlModulesXdbcPort=8032
mlConfigPath=src/main/dev/ml-config
mlModulePaths=src/main/dev/ml-modules

I got the latest version of gradle recently downloaded and the gradles version is "gradle-4.0.1", I don't know what is the related ml-gradle version to use. I follow the same mlgradledependency copied from the previous gradle.properties files. "mlGradleDependency=com.rjrudin:ml-gradle:2.0b+"
Please let me know for any other details.
RegardsSathishS

**Comment by saths-github** [comment]
Hi,
Any update/solution on the issue ?

Regards
SathishS

**Comment by saths-github** [comment]
Adding my World Bank email account, for quick mail check.

**Comment by rjrudin** [comment]
Yes - the "com.rjrudin:ml-gradle:2.0b+" version is a beta one that pre-dates the official 2.0.0 release. I don't know that mlModulePaths was supported in that. 

Try upgrading to 2.8.0 - "com.marklogic:ml-gradle:2.8.0". I think the main issue you may have is that the package names changed from "com.rjrudin.marklogic" to "com.marklogic", so if you have any instances of e.g. MlcpTask, you'll need to fix those.

**Comment by rjrudin** [comment]
Closing this out, but please let me know if upgrading doesn't fix the issue.
