### ISSUE TITLE
rest-properties.json not applied

### ISSUE THREAD

**Issue by sparnell** [marklogic-community/ml-gradle#224]
Change "validate-queries" to false in rest-properties.json. Run mlDeploy. The validate-queries property is still set to true (the default).

**Comment by rjrudin** [comment]
Ack - turns out this is a bug in ml-javaclient-util - the methods are swapped for validate-queries and validate-options:

    if (node.has("validate-options")) {
      mgr.setQueryValidation(node.get("validate-options").asBoolean());
    }
    if (node.has("validate-queries")) {
      mgr.setQueryOptionValidation(node.get("validate-queries").asBoolean());
    }

**Comment by rjrudin** [comment]
I'm about to publish ml-gradle 2.9.0 - I'll make a 2.14.1 of ml-javaclient-util and include the bugfix in there, so it'll be part of 2.9.0. Thanks for the report.

**Comment by rjrudin** [comment]
Fixed and including in ml-gradle 2.9.0
