### ISSUE TITLE
Migrate Roxy Project not processing ml-config.xml

### ISSUE THREAD

**Issue by bhandaru** [marklogic-community/ml-gradle#226]
Hello,

We are trying to migrate a roxy project to gradle and found that it does not process ml-config.xml and import the index and other configurations from the roxy project.

Does mlRoxyMigrateProject task support this?

**Comment by rjrudin** [comment]
The mlRoxyMigrateProject task does not - please see the guide on migrating a Roxy project, specifically this section - https://github.com/marklogic-community/ml-gradle/wiki/Migrating-a-Roxy-project-to-ml-gradle#exporting-the-current-roxy-application
