### ISSUE TITLE
There doesn't seem to be a property to set the schema database name

### ISSUE THREAD

**Issue by jkerr5** [marklogic-community/ml-gradle#228]
The content database name can be set with `mlContentDatabaseName` and the modules database name can be set with `mlModulesDatabaseName` but the schema database name cannot be set via a property like this.

**Comment by rjrudin** [comment]
I'll get a property added soon - in the meantime, you can do:

    ext {
      mlAppConfig.schemasDatabaseName = "my-custom-name"
    }

(the properties are often syntactic sugar over modifying the mlAppConfig object directly)

**Comment by rjrudin** [comment]
Addressed via https://github.com/marklogic-community/ml-app-deployer/issues/181
