### ISSUE TITLE
Is there any way to configure CPF for a specific database?

### ISSUE THREAD

**Issue by tzejohn** [marklogic-community/ml-gradle#229]
Currently, it appears that the CPF domain and pipelines are deployed to all databases. Is there any way to target the CPF for a specific database? My case is more with the datahub where I want to only setup CPF on the final database to replicate to another db instance.

**Comment by rjrudin** [comment]
CPF resources are deployed to a database - call it "app-triggers" -  and then every database that has "app-triggers" as its "triggers-database" will have the CPF resources associated with it. 

So the easiest way to ensure that a particular database doesn't have CPF resources associated with it is to set its "triggers-database" to "Triggers" (the OOTB database that is normally empty).

**Comment by tzejohn** [comment]
Thanks. This works. I configured the db to use another triggers database, and the CPF is no longer installed in it.
