### ISSUE TITLE
TDE deployment and generation point to different directories.

### ISSUE THREAD

**Issue by grechaw** [marklogic-community/ml-gradle#230]
This bug has to do with the default behavior of `mlLoadSchemas` and `mlGenerateCode` with regard to entity services (and given some time I'm willing to track down and fix).

If you use mlGenerate to create code from entity services, then it creates a TDE template and places it in 

`$configDir/ml-schemas`

However, in order to deploy schemas, ml-gradle looks to

`$configDir/ml-schemas/tde`

The second location was a deliberate change, to provide a place just for extraction templates.  So to fix this bug, my recommendation would be to change `mlGenerateCode` to save to the `tde` subdirectory.

**Comment by rjkennedy98** [comment]
Similarly, it is a bit confusing that my.tde is under ml-schemas in the schemas-project example:
https://github.com/marklogic-community/ml-gradle/blob/master/examples/schemas-project/src/main/ml-schemas/my.tde

**Comment by rjrudin** [comment]
@grechaw Just to confirm - the .tdex file should go under ./ml-schemas/tde, but the .xsd file should stay under ./ml-schemas?

**Comment by rjrudin** [comment]
Fixed via https://github.com/marklogic-community/ml-app-deployer/commit/59a4a0b5508522093d6f7b77e3101fbc65c3ccd3

**Comment by rjrudin** [comment]
@rjkennedy98 I fixed the location of the TDE file in the sample project too.
