### ISSUE TITLE
Custom Task extending MarkLogicTask

### ISSUE THREAD

**Issue by ravi-b-m** [marklogic-community/ml-gradle#234]
I have a custom task that extends Marklogic Taks, and inside the custom Task, I read a specific JSON File, the json file has markers for the "Database". These markers are not filled in when I access this file for eg:-

My Json file looks like 
```JSON
{
  "task-enabled":true,
  "task-path":"/MarkLogic/flexrep/tasks/push-local-forests.xqy",
  "task-root": "Modules/",
  "task-type": "minutely",
  "task-period" : 1,
  "task-database": "%%DATABASE%%",
  "task-modules": "file system",
  "task-user": "admin",
  "task-priority": "higher"
}
```

In My custom task I access this File, and `%%DATABASE%%` is not filled with actual property.. do I need to do anything specific for this to happen ??.. My custom task looks something like this

```Java
   task scheduleFlexrepTask(type: com.marklogic.gradle.task.MarkLogicTask){
      doLast{
       File tasksDir = new File(getAppConfig().getConfigDir().getBaseDir(), "flexrep-tasks")
        if(!tasksDir.exists())
            throw new org.gradle.api.GradleException("Flexrep directory " + tasksDir.absolutePath + " does not exist.")

        for(File f:tasksDir.listFiles(new FileFilter(){
            boolean accept(File pathname){
                return pathname.getName().endsWith(".json") ||
                        pathname.getName().endsWith(".xml")
            }
        })){
            println GFileUtils.readFile(f)

     }
}
```

**Comment by ravi-b-m** [comment]
I think I found a way but is this the right way ??

```Java
 String json = GFileUtils.readFile(f);
  com.marklogic.appdeployer.command.TokenReplacer playloadTokenReplacer = new com.marklogic.appdeployer.command.DefaultTokenReplacer();
   json = playloadTokenReplacer.replaceTokens(json, getAppConfig(), false)
```

**Comment by rjrudin** [comment]
If you're looking to deploy this scheduled task, just add it under ml-config/tasks. You don't need a custom task to do that. 

The TokenReplacer does replace tokens - which can be anything (the "%%" isn't required, it just helps make it obvious that it's intended to be replaced) - and it's used on every file that ml-gradle processes.

**Comment by ravi-b-m** [comment]
I want my FlexRep Scheduled task to be explicitly deployed, and also only if a  flexrep is enabled for a particular environment. I understand I can remove the deploy task command, based on some user defined variable or env, but this will remove all the deployment of other tasks as well. Is there a way where I can tell not to deploy a particular task ?

**Comment by rjrudin** [comment]
See mlResourceFilenamesToIgnore and mlResourceFilenamesToExcludeRegex at https://github.com/marklogic-community/ml-gradle/wiki/Property-reference . You can conditionally set those properties to a list of filenames or a regex to specify filenames that you don't want processed, regardless of the resource type.

**Comment by ravi-b-m** [comment]
Hmm couple of strange behaviors

When using `id "com.marklogic.ml-gradle" version "2.3.2"`.. And does a `mlRedeploy` and if the schedule task already exists .. then I get the following exception

```
:mlDeployApp
PUT request for "http://internal-ml-cluster-irx-dev-lb-1031654958.us-east-1.elb.amazonaws.com:8002/manage/v2/tasks/4512031935706283211/properties?group-id=Default" resulted in 500 (Internal Server Error); invoking error handler
Logging HTTP response body to assist with debugging: {"errorResponse":{"statusCode":"500", "status":"Internal Server Error", "messageCode":"MANAGE-INVALID", "message":"MANAGE-INVALID (err:FOER0000): task-user"}}
:mlDeployApp FAILED
```

And also the `2.3.2` version does not take into account `mlResourceFilenamesToIgnore`

So I thought of using `id "com.marklogic.ml-gradle" version "2.9.0"`.. but my ML version is  `8.0-5.4`, so when  I do `mlRedeploy` I get the following exception

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mlDeployApp'.
> Unable to complete bulk load, cause: Unrecognized response code (504). Is this an XDBC server?

```

The gradle command that I used for Redeploy
```
mlRedeploy -PenvironmentName=dev  --stacktrace -Dxcc.httpcompliant=true
```

**Comment by rjrudin** [comment]
Can you try a later version of ml-gradle, like 2.9.0, which has mlResourceFilenamesToIgnore? The Regex properties were added in 3.0.0.

Also, in some scenarios (maybe all?), the Manage API throws an error if you try to update a scheduled task that has a different user than the one in your payload. That's been an issue on one of my projects.

**Comment by ravi-b-m** [comment]
I have the same `task-user` .. but still cannot undeploy a task or when I do `redeploy` it fails.. Following is my task looks like 
```json
{
  "task-enabled":true,
  "task-path":"/MarkLogic/flexrep/tasks/push-local-forests.xqy",
  "task-root": "Modules/",
  "task-type": "minutely",
  "task-period" : 1,
  "task-database": "%%DATABASE%%",
  "task-modules": "%%MODULES_DATABASE%%",
  "task-user": "admin",
  "task-priority": "higher"
}
```

When I look at debug output I found this
```
09:49:18.628 [DEBUG] [org.apache.http.impl.auth.HttpAuthenticator] Selected authentication options: [DIGEST [complete=true, nonce=null, nc=0]]
09:49:18.629 [DEBUG] [org.apache.http.impl.execchain.MainClientExec] Executing request PUT /manage/v2/tasks/194786451762326512/properties?group-id=Default HTTP/1.1
09:49:18.629 [DEBUG] [org.apache.http.impl.execchain.MainClientExec] Target auth state: CHALLENGED
09:49:18.629 [DEBUG] [org.apache.http.impl.auth.HttpAuthenticator] Generating response to an authentication challenge using digest scheme
09:49:18.630 [DEBUG] [org.apache.http.impl.execchain.MainClientExec] Proxy auth state: UNCHALLENGED
09:49:19.412 [DEBUG] [org.apache.http.impl.execchain.MainClientExec] Connection can be kept alive for 5000 MILLISECONDS
09:49:19.413 [DEBUG] [org.apache.http.impl.auth.HttpAuthenticator] Authentication succeeded
09:49:19.413 [DEBUG] [org.apache.http.impl.client.TargetAuthenticationStrategy] Caching 'digest' auth scheme for http://10.239.12.85:8002
09:49:19.414 [DEBUG] [org.springframework.web.client.RestTemplate] PUT request for "http://10.239.12.85:8002/manage/v2/tasks/194786451762326512/properties?group-id=Default" resulted in 500 (Internal Server Error); invoking error handler
```

`http://10.239.12.85:8002/manage/v2/tasks/194786451762326512/properties?group-id=Default` Which authentication or credentials does `ml-gradle` this use, because when I type in the url on the browser and use admin credentials I was able to access it

**Comment by rjrudin** [comment]
Try --info logging instead, it makes it easier to which user is used. 

You can try using curl to make the same PUT call to see if that works.

**Comment by ravi-b-m** [comment]
`ml-gradle` uses the `mlManageUsername`  for the PUT for tasks.. in my case I changed my `task-user` to be same as `mlManageUsernam`.  redeploy still fails.. even using CURL..
```
curl -X PUT --digest -u content-repo-manager:manager -H "Content-type: application/json" -d '{"task-enabled":true,"task-path":"/MarkLogic/flexrep/tasks/push-local-forests.xqy","task-root": "Modules/","task-type": "minutely",
"task-period" : 1,"task-database": "content-repo-content","task-modules": "content-repo-modules", "task-user": "content-repo-manager", "task-priority": "higher"}' http://10.239.12.85:8002//manage/v2/tasks/18299886840194492751/properties?group-id=Default
```

**Comment by xquery** [comment]
when u attempt with curl, what is the failure ?

**Comment by rjrudin** [comment]
Note this bug too - https://github.com/marklogic-community/ml-gradle/issues/208 - that may be the cause, since you have "minutely" as the task period.

**Comment by ravi-b-m** [comment]
I get the same error 
```json
"errorResponse":{"statusCode":"500", "status":"Internal Server Error", "messageCode":"MANAGE-INVALID", "message":"MANAGE-INVALID (err:FOER0000): task-user"}}
```

Since `undeployTasks` works I just did
```
mlDeployTasks.dependsOn mlUndeployTasks
mlDeploy.dependsOn mlUndeployTasks
mlRedeploy.dependsOn mlUndeployTasks
```

**Comment by rjrudin** [comment]
@xquery I know I've run into this issue before, where a scheduled task can't be updated, and the error is about "task-user". We've resorted to just deleting the task and redeploying. Unfortunately I don't have reproducible steps.

**Comment by hansenmc** [comment]
We have had issues re-deploying tasks, and it turned out to be a permissions issue. @rrumpf added a comment with information about it to https://github.com/marklogic-community/ml-gradle/issues/39. We needed to give the user the *security role*.

> In order to create a scheduled task via mlDeployTasks, you needed one set of privileges. However, if the tasks already existed, running mlDeployTasks (with the same task configuration) would fail with the error: MANAGE-INVALID (err:FOER0000): task-user when run by the same (non-admin) user that created the task.

>The way to fix this was to add the security role to the user interacting with MarkLogic via the REST API in this gradle task. Presumably, there are additional checks regarding roles and privileges when the task is deployed on top of itself.

**Comment by rjrudin** [comment]
Thanks @hansenmc , that's the issue here - solution is to ensure the user updating scheduled tasks has the "security" role.
