### ISSUE TITLE
error when deploying more than one cpf-config

### ISSUE THREAD

**Issue by tzejohn** [marklogic-community/ml-gradle#236]
I have two cpf configuration JSON files in my **cpf-configs** directory. Each one is configured for a different domain. However, when I run the **mlDeploy** task, I get an error that the config already exists.

```
:mlDeployApp
Logging HTTP response body to assist with debugging: {"errorResponse":{"statusCode":"400", "status":"Bad Request", "messageCode":"MANAGE-PRECONDITIONFAILED", "message":"MANAGE-PRECONDITIONFAILED: (err:FOER0000) Precondition not met:  Cannot create cpf-config, incoming cpf-config already exists."}}
:mlDeployApp FAILED
```

Can only a single cpf-config exist at a time?

**Comment by rjrudin** [comment]
I've never tried that, but the Manage API error message seems to think not. 

What do you need the second configuration for? You can have as many domains as you want; I forget what exactly the "domain-name" in a CPF configuration is for, and it hasn't had any bearing on the project I've mostly been working on.

**Comment by tzejohn** [comment]
Maybe this is my misunderstanding as to the relation between _cpf-configs_ and the domains declared in the _domains_ folder. I have different domains to trigger different CPF processing depending on collection,path, etc. I have one CPF flow triggering off of items under a specific hierarchy, and I have a different flow for documents in a certain collection. Specifically the collection one is a flex-rep case.

My thought was that in _cpf-configs_ each configuration domain would be associated with the other domain. The documentation [here](https://docs.marklogic.com/REST/POST/manage/v2/databases/[id-or-name]/cpf-configs) seems to imply the correlation. So I guess I just am not clear what this endpoint does.. is it just to enable CPF , and I can call this domain anything I want, and then anything run against CPF in this triggers database would share the same restart/permission settings.

Sorry for rambling.

@kmoralesml what do you think?

**Comment by rjrudin** [comment]
That has been my experience with CPF configs - that I just need one, and it can be associated with any domain. I can then have N domains with any number of pipelines attached to them.

**Comment by rjrudin** [comment]
@tzejohn Any update on this? Did you try one CPF configuration, and is your application working fine?

**Comment by tzejohn** [comment]
I used just one config, and it has been fine.  Thanks.

**Comment by lifan0127** [comment]
This is indeed confusing. Based on the generated trigger document, it seems the "domain" in `cpf-config` means the "default domain" for the "default conversion": https://docs.marklogic.com/guide/cpf/default#id_16194

```xml
<dom:configuration xml:lang="zxx" xmlns:dom="http://marklogic.com/cpf/domains">
<dom:config-id>...</dom:config-id>
<dom:evaluation-context>
<dom:database>...</dom:database>
<dom:root>/</dom:root>
</dom:evaluation-context>
<dom:restart-user>...</dom:restart-user>
<dom:restart-trigger>
<dom:trigger>...</dom:trigger>
</dom:restart-trigger>
<dom:default-domain>...</dom:default-domain>
<dom:conversion-enabled>true</dom:conversion-enabled>
</dom:configuration>
```
