### ISSUE TITLE
Help Options for mlCreateTransform are incorrect

### ISSUE THREAD

**Issue by rjkennedy98** [marklogic-community/ml-gradle#246]
There is a typo: PtranssformName instead of -PtransformName

https://github.com/marklogic-community/ml-gradle/blob/c5811d40577e41eb3640b3eaf51be5795d3b47cc/src/main/groovy/com/marklogic/gradle/MarkLogicPlugin.groovy#L156

**Comment by rjrudin** [comment]
Thanks!
