### ISSUE TITLE
Getting MISSING_FLOW error when invoking from DMSDK

### ISSUE THREAD

**Issue by janmichaelyu** [marklogic-community/ml-gradle#247]
The issue

All in the title!
Tech details

Which Operating System are you using?
Linux
Which version of MarkLogic are you using?
9.0.3
Which version of the Data Hub Framework are you using?
2.0.0
Is this a QuickStart UI bug? If so, which browser are you using?
Likely not

The devil is in the details...

ErrorLog from ML
13:38:13.046 [pool-1-thread-10] WARN  c.m.c.d.impl.WriteBatcherImpl - Error writing batch: com.marklogic.client.FailedRequestException: Local message: failed to apply resource at documents: Internal Server Error. Server Message: The specified flow : is missing. (MISSING_FLOW): . See the MarkLogic server error log for further detail.

AccessLog from ML
172.28.128.1 - admin [26/Oct/2017:05:37:42 +0000] "POST /v1/documents?trans:job-id=2bcab367-2764-4d93-be95-3eb5603cf244&transform=run-flow&trans:options={%22targetEntity%22:%22TruvenEnrollment%22}&trans:entity=GenericEnvelope&trans:flow=basic&database=abbvie-es-data-hub-STAGING HTTP/1.1" 500 221 - "okhttp/3.8.1"

Java code
`
		ServerTransform runFlow = null;

			runFlow = new ServerTransform("run-flow");
			String dataHubEntity = entityName;
			if (properties.containsKey("dataHubEntity")) {
				dataHubEntity = properties.getProperty("dataHubEntity");
			}
			runFlow.addParameter("entity", dataHubEntity);
			runFlow.addParameter("flow", properties.getProperty("dataHubFlow"));
			runFlow.addParameter("job-id", UUID.randomUUID().toString());
			try {
				runFlow.addParameter("options", new JSONObject().put("targetEntity", entityName).toString());
			} catch (JSONException e) {
				e.printStackTrace();
			}
		`

**Comment by sastafford** [comment]
This doesn't sound like a ml-gradle issue.  You are probably missing a flow transform or it could be data-hub related.  Try verifying the transform exists.  

http://docs.marklogic.com/REST/GET/v1/config/transforms

**Comment by janmichaelyu** [comment]
Yeah, my apologies. I meant to post this in datahub, must have had too many tabs open trying to fix this issue and posted in ml-gradle by mistake.

Sent from Nine<http://www.9folders.com/>
________________________________
