### ISSUE TITLE
Blank harmonization page

### ISSUE THREAD

**Issue by kghmanuel** [marklogic-community/ml-gradle#248]
Steps to replicate:
1. Create entity bug_report
2. Create entity user_group
3. Create and execute harmonize flow for user_group
4. Create harmonize flow for bug_report
    * (bug) unable to load the harmonize page as shown below
    * still able to load harmonization page for user_group

No errors posted on the browser console, nor with the command prompt running java -jar quickstart.war

====

Details:
1. OS is Windows 7
2. ML 9.0-2
3. quick-start-2.0.0.war

**Comment by rjrudin** [comment]
Can you post this in the Data Hub Framework project instead? This is specific to DHF.

**Comment by kghmanuel** [comment]
update: this only happens if the created folder under plugins is created using non-lowercase characters, i.e. folder is Bug_Report, but the entity is bug_report.

**Comment by kghmanuel** [comment]
sorry... wrong thread. will post there
