### ISSUE TITLE
How to set up temporal via gradle tasks?

### ISSUE THREAD

**Issue by sjordan1975** [marklogic-community/ml-gradle#252]
What task(s) exist to complete the steps required for temporal configuration as outlined in the [Quick Start Guide](https://docs.marklogic.com/guide/temporal/temporal-quick-start)

Namely:
* Create Metadata Fields for the Valid and System Axes
* Create Range Field Indexes for the Valid and System Axes
* Create System and Valid Axes
* Create a Temporal Collection

**Comment by rjrudin** [comment]
See the sample projects, let me know if something isn't addressed. 

https://github.com/marklogic-community/ml-gradle/tree/master/examples/temporal-project

https://github.com/marklogic-community/ml-gradle/tree/master/examples/temporal-lsqt-project

**Comment by sjordan1975** [comment]
I saw these projects. How are the config and axes actually deployed/provisioned to the database?

The following did not seem to do the trick:
```
$> gradle mlDeploy
```

Similarly, how are the metadata fields sets (as described in the [Quick Start](https://docs.marklogic.com/guide/temporal/temporal-quick-start#id_50302))

**Comment by rjrudin** [comment]
Which version of ml-gradle are you using? 

Try running "mlDeploy -i" on a sample project - you should see info-level logging that shows temporal commands processing the files under src/main/ml-config/temporal.

As for fields and range indexes - those are configured on your database, so those go into your content database payload file, which defaults to content-database.json. Easiest way to configure that is the same for all resources - configure them manually via the Admin UI, and then go to host:8002/manage/v2/databases, find your database, and click on properties - it'll give you the XML/JSON that you need to put into your file.

**Comment by sjordan1975** [comment]
Below is a snippet of my database config (as output by http://_host_:8002/manage/v2/databases/_my-database_?view=config&format=json):

```
...
            "range-path-indexes": null,
            "fields": {
                "field": [{
                    "field-name": "validStart",
                    "metadata": ""
                }, {
                    "field-name": "validEnd",
                    "metadata": ""
                }, {
                    "field-name": "systemStart",
                    "metadata": ""
                }, {
                    "field-name": "systemEnd",
                    "metadata": ""
                }]
            },
            "range-field-indexes": {
                "range-field-index": [{
                    "scalar-type": "dateTime",
                    "field-name": "validStart",
                    "collation": "",
                    "range-value-positions": true,
                    "invalid-values": "reject"
                }, {
                    "scalar-type": "dateTime",
                    "field-name": "validEnd",
                    "collation": "",
                    "range-value-positions": true,
                    "invalid-values": "reject"
                }, {
                    "scalar-type": "dateTime",
                    "field-name": "systemStart",
                    "collation": "",
                    "range-value-positions": true,
                    "invalid-values": "reject"
                }, {
                    "scalar-type": "dateTime",
                    "field-name": "systemEnd",
                    "collation": "",
                    "range-value-positions": true,
                    "invalid-values": "reject"
                }]
            },
            "geospatial-element-indexes": null,
...
```
Copied the above into my database config.

Getting Error:
```
gradle mlReDeploy
> Task :mlDeployApp
Logging HTTP response body to assist with debugging: {"errorResponse":{"statusCode":"400", "status":"Bad Request", "messageCode":"MANAGE-INVALIDPAYLOAD", "message":"MANAGE-INVALIDPAYLOAD: (err:FOER0000) Payload has errors in structure, content-type or values. Unexpected element: fields (not in schema)"}}
```

**Comment by paxtonhare** [comment]
@sjordan1975 can you re-run `gradle mlRedeploy -i` so we can see the place where it choked?

@rjrudin Salim tells me he's running DHF. Thus my magical appearance here.

**Comment by sjordan1975** [comment]
Ok, a couple updates:

The following I _kinda_ works:

```
...
    "field": [{
        "field-name": "validStart"
    },
    {
        "field-name": "validEnd"
    },
    {
        "field-name": "systemStart"
    },
    {
        "field-name": "systemEnd"
    }]
}
```

However, it creates the fields as _root_ fields.

Based on the output of http://host:8002/manage/v2/databases/my-database?view=config&format=json, I believe the following _should_ work (but errors):

```
...
    "field": [{
        "field-name": "validStart",
        "metadata": ""
    },
    {
        "field-name": "validEnd",
        "metadata": ""
    },
    {
        "field-name": "systemStart",
        "metadata": ""
    },
    {
        "field-name": "systemEnd",
        "metadata": ""
    }]
}
```

Error (with -i flag per @paxtonhare's request):

```
gradle mlRedeploy -i

...
Sending XML GET request as user 'admin' to path: /manage/v2/databases/emerald-hub-MODULES/properties
Merging JSON files at locations: [/Users/sjordan/Projects/marklogic/UPMC/emerald/hub-internal-config/databases/final-database.json]
Sending XML GET request as user 'admin' to path: /manage/v2/databases
Found database with name of emerald-hub-FINAL, so updating at path /manage/v2/databases/emerald-hub-FINAL/properties
Sending JSON PUT request as user 'admin' to path: /manage/v2/databases/emerald-hub-FINAL/properties
Logging HTTP response body to assist with debugging: {"errorResponse":{"statusCode":"500", "status":"Internal Server Error", "messageCode":"XDMP-UNDFUN", "message":"XDMP-UNDFUN: (err:XPST0017) xdmp:function(fn:QName(\"http://marklogic.com/xdmp/admin\",\"database-set-field-metadata\"))($config, $dbid, $field-name, $prop/fn:data(.)) -- Undefined function Q{http://marklogic.com/xdmp/admin}database-set-field-metadata()"}}

:mlDeployApp (Thread[Task worker for ':',5,main]) completed. Took 20.069 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mlDeployApp'.
> 500 Internal Server Error

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 30s
```

**Comment by rjrudin** [comment]
Your custom task doesn't define the fields in the database though. How did you get that part working? 

The calls in your custom task are to the "/temporal/" endpoints. Are those not working with ml-gradle? If so, are they not working because the fields aren't created properly in the database?

**Comment by sjordan1975** [comment]
@rjrudin In the end, I went away from using database metadata fields as outlined in the [Quick Start](https://docs.marklogic.com/guide/temporal/temporal-quick-start); rather I went with storing temporal information in the document itself as outline in this [alternate approach](https://docs.marklogic.com/guide/temporal/managing#id_59302). 

This does not seem to require fields, just element range indexes, which can be created via the database config and seems to work (whereas I could not get metadata fields created successfully via the database config).

**Comment by sjordan1975** [comment]
@rjrudin Could this be-reopened (not tagged CLOSED)?

**Comment by rjrudin** [comment]
Sure, though I don't know what the scope of the ticket is at this point.
