### ISSUE TITLE
.DS_Store in ml-schemas directory causes XDMP-DOCUTF8SEQ

### ISSUE THREAD

**Issue by mfgumban** [marklogic-community/ml-gradle#258]
When you have an empty ml-schemas directory but contains the hidden file .DS_Store (or potentially any hidden file), gradle mlDeploy will throw the following exception: 
`com.marklogic.client.FailedRequestException: Local message: failed to apply resource at documents: Bad Request. Server Message: XDMP-DOCUTF8SEQ: xdmp:get-request-part-body("text") -- Invalid UTF-8 escape sequence at  line 1 -- document is not UTF-8 encoded`

The workaround is to ensure the directory is truly empty or simply delete the directory.  The error message is a little confusing at first because the file is not apparent and hidden.

**Comment by rjrudin** [comment]
This is fixed in ml-javaclient-util and ml-app-deployer (the latter now allows for a custom FileFilter to be configured).
