### ISSUE TITLE
'mlExportResources' with given ml group name

### ISSUE THREAD

**Issue by arulsiva21** [marklogic-community/ml-gradle#259]
Exporting all app-servers for the given "mlGroupName" is not working. Is it hardcoded to Default? Or can it be overridden with different group name? I tried below line in gradle.properties
mlGroupName=Batch

**Comment by rjrudin** [comment]
Do you get an error, or is each server just not exported? I'm figuring it's an error. 

mlExportResources uses Exporter in ml-app-deployer. And that uses an instance of ServerExporter, which  defaults to the "Default" group. 

Do you need to specify multiple groups, or do you just need the ability to change the group? The latter should be easy to do; the former will require some thought as to how a user specifies different groups.

**Comment by arulsiva21** [comment]
yes, i'm getting error as it's trying to export app-server which is not attached with "Default" group. So, i would like to use my own group instead of default. I tried by using mlGroupName=Batch in gradle.properties, but it didnt pick. thanks for clarifying!

**Comment by rjrudin** [comment]
Okay, I've made changes to the Exporter API in ml-app-deployer so that a group can be specified for exporting servers and tasks (tasks will have the same issue as servers here).

I think reusing mlGroupName is a good idea, as opposed to adding a new property that's specific to this task. It seems natural to e.g. override mlGroupName if needed on the command line. And if it's already set to something besides Default, it seems expected to use that so it doesn't need to be specified on the command line. 

Tossing into 3.2.0, which should be released worst case by early next week.

**Comment by arulsiva21** [comment]
Great! Thank you for your quick turnaround!

**Comment by arulsiva21** [comment]
Is there any way to export Group configuration which includes list-cache-size, list-cache-partitions etc? I would also need a way to import or deploy only group configuration. Thanks!

**Comment by rjrudin** [comment]
Were those properties not exported when you exported e.g. the Default group? They're all present when I go to http://localhost:8002/manage/v2/groups/Default/properties?format=html .

**Comment by arulsiva21** [comment]
Yes, they are presnt in /manage/v2/group....., but it was not exported along with other resources like servers/databases etc

Here is what i tried
-gradle -d -PincludeTypes=groups -Pregex=.*.* mlExportResources

Should i add any option to include group?

**Comment by arulsiva21** [comment]
Also, i manually copied group config from config manager (http://localhost:8002/manage/v2/groups/Default/properties?format=html) to /src/main/ml-config/groups/default.json and updated some config value, and tried updating with mlDeployGroups command. It was failing with below message

12:57:44.409 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
12:57:44.409 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
12:57:44.409 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
12:57:44.409 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':mlDeployGroups'.
12:57:44.410 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Cannot get field value from JSON; field name: group-name; JSON: {"group-config":{"id":"4443721925526416068", "name":"Default", "meta":{"uri":"/manage/LATEST/groups/Default?view=config", "current-time":"2017-12-07T10:51:25.0376994-05:00", "elapsed-time":{"units":"sec", "value":0.0802145}}, "config-properties":{"list-cache-size":4096, "list-cache-partitions":2, "compressed-tree-cache-size":2048, "compressed-tree-cache-partitions":3, "compressed-tree-read-size":32, "expanded-tree-cache-size":4096, "expanded-tree-cache-partitions":2, "triple-cache-size":4096, "triple-cache-partitions":2, "triple-cache-timeout":300, "triple-value-cache-size":2048, "triple-value-cache-partitions":3, "triple-value-cache-timeout":300, "email-address":"admin@accenturefederal.com", "smtp-relay":"accenturefederal-com.mail.protection.outlook.com", "smtp-timeout":60, "http-user-agent":"MarkLogic", "http-timeout":60, "xdqp-timeout":10, "host-timeout":30, "host-initial-timeout":240, "retry-timeout":180, "module-cache-timeout":300, "system-log-level":"notice", "file-log-level":"info", "rotate-log-files":"daily", "keep-log-files":10, "failover-enable":true, "xdqp-ssl-enabled":false, "xdqp-ssl-allow-sslv3":true, "xdqp-ssl-allow-tls":true, "xdqp-ssl-ciphers":"ALL:!LOW:@STRENGTH", "schemas":{"schema":[{"namespace-uri":"http://www.w3.org/1999/xhtml", "schema-location":"xhtml1.1.xsd"}]}, "namespaces":null, "module-locations":null, "events-activated":false, "events":null, "audit":{"audit-enabled":false, "rotate-audit-files":"daily", "keep-audit-files":7, "audit-events":null, "audit-restrictions":null}, "background-io-limit":0, "metering-enabled":true, "performance-metering-enabled":true, "meters-database":"15835818462236551092", "performance-metering-period":60, "performance-metering-retain-raw":7, "performance-metering-retain-hourly":30, "performance-metering-retain-daily":90, "s3-domain":"s3.amazonaws.com", "s3-protocol":"http", "s3-server-side-encryption":"none", "security-database":"8089855481085298892"}, "related-views":{"related-view":[{"view-type":"item", "view-name":"default", "view-uri":"/manage/LATEST/groups/Default"}]}}}

**Comment by arulsiva21** [comment]
Never mind on deployment part... It works fine with correct group config.
Missing part is exporting group config. Thanks!

**Comment by hgarrow** [comment]
I do not have a group named Default and still cannot export resources correctly.  The tasks call is still using Default instead of mygroup01
  id "com.marklogic.ml-gradle" version "3.3.0"


Sending XML GET request as user 'admin' to path: /manage/v2/tasks?group-id=Default
Logging HTTP response body to assist with debugging: {"errorResponse":{"statusCode":"404", "status":"Not Found", "messageCode":"XDMP-NOSUCHGROUP", "message":"XDMP-NOSUCHGROUP: xdmp:group(\"Default\") -- No such group Default"}}
:mlExportResources FAILED
:mlExportResources (Thread[Daemon worker Thread 2,5,main]) completed. Took 6.39 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mlExportResources'.
> 404 Not Found

**Comment by rjrudin** [comment]
@hgarrow This should really be a separate ticket, as this one is closed - but try setting mlGroupName=mygroup01. You can either do that in gradle.properties or on the command line, e.g.

    gradle -PmlGroupName=mygroup01 mlExportResources ....
