### ISSUE TITLE
Consider alternate default modules db config for REST server

### ISSUE THREAD

**Issue by damonfeldman** [marklogic-community/ml-gradle#263]
MarkLogic defaults are to create one forest per host for the modules DB, but without HA, this makes it more likely that the modules db goes offline. A nicer default would be to either put one forest on one host (non-HA) or distribute the forests across hosts but include HA replication so the modules db host does not become a single point of failure for the REST server.

See also internal MarkLogic RFE 4081.

**Comment by rjrudin** [comment]
@damonfeldman Is this for the modules database created by the call to /v1/rest-apis? I don't think there's any way to control how that database is created.

I think the better approach would be to create a modules-database.json file and configure that like any other database. The call to /v1/rest-apis will see that the modules database already exists and use that.

**Comment by rjrudin** [comment]
Closing this with the recommendation above - i.e. using a modules-database.json file to customize the aspects of the modules database.
