### ISSUE TITLE
Documentation for Password Encryption

### ISSUE THREAD

**Issue by RobertSzkutak** [marklogic-community/ml-gradle#267]
It would be helpful to see a best-practices guide on how to support encrypted passwords with ml-gradle.

**Comment by damonfeldman** [comment]
Maybe something like https://github.com/etiennestuder/gradle-credentials-plugin ? A goal of using gradle is to piggyback on the broader ecosystem.

**Comment by rjrudin** [comment]
I agree with @damonfeldman . I'll add a Wiki page for this, as I think this is a common enough request that even though it's not specific to ml-gradle but rather Gradle, it's worth having a quick answer for. But yeah, in general, for a feature that isn't specific to MarkLogic, googling on "gradle feature" should produce the answer, if one exists.

**Comment by rjrudin** [comment]
https://github.com/marklogic-community/ml-gradle/wiki/Encrypting-passwords
