### ISSUE TITLE
Mirror Jcenter artifacts to Maven Central

### ISSUE THREAD

**Issue by mcrosier** [marklogic-community/ml-gradle#269]
For those users who are on networks with limited connectivity, it would be helpful to have the artifacts for ml-gradle (and other related jcenter based dependencies such as ml-app-deployer) to be mirrored to maven central. This would benefit users who have access to a locally mirrored maven central repository, but do not have access to jcenter.

**Comment by rjrudin** [comment]
@hansenmc Know how to do this? I think you did this for corb?

**Comment by hansenmc** [comment]
Yes, we do this for CORB2. Bintray makes this pretty easy to sync to Maven Central. You need to satisfy the [requirements ](http://central.sonatype.org/pages/requirements.html) to publish to Central.

I have been using the manual sync option through the site. In the Bintray project site, there is a **Maven Central** tab. You enter your credentials and click the button to sync. 

I have not yet configured it, but another option is to configure the Bintray plugin to sync automatically with the [mavenCentralSync ](https://github.com/bintray/gradle-bintray-plugin#maven-central-sync)closure.

**Comment by rjrudin** [comment]
Just a note, this is underway - e.g. https://search.maven.org/#search%7Cga%7C1%7Ca%3A%22ml-javaclient-util%22

**Comment by popzip** [comment]
@rjrudin considered done now?

**Comment by rjrudin** [comment]
This is in process now.
