### ISSUE TITLE
Deploying Database configurations without touching the forest assignments

### ISSUE THREAD

**Issue by RobertSzkutak** [marklogic-community/ml-gradle#270]
I've been talking with Damon and a few others behind the scenes about this. We think it would be good to have an open discussion about this before potentially petitioning for some enhancements to Management API or further pursuing the idea.

DB deployments always touch the forest assignments : 

{
  "database-name": "customer-data-hub",
  "forest": [
    "customer-data-hub-f1-h1",
    "customer-data-hub-f2-h2"
   ...
  ],
  ...
}

It would be nice to be able to perform a DB deployment without touching the forest assignment for a myriad of reasons:

1) It's safer for inexperienced DBAs (who could accidentally unassign forests)
2) If the "forest" attribute was not needed it could cut down on the number of *.json files you need to maintain for the database (presently, 1 per environment)
   2.5) It would allow you to avoid doing JSON surgery between environment configs to transfer settings over

Potential ways to support this;

1) ml-gradle tasks to eval code to do DB deployments in a way that doesn't touch every setting every time
2) ml-gradle could patch in the forest config based on a regex so we don't need to maintain multiple DB config.json files.
3) More granular management APIs (add/remove index, enable/disable triple index, etc.) and subsequent ml-gradle support for these (this also has the added benefit of being able to not to touch other DB settings just to add an index)
4) Make the forest attribute optional in the management API . And/or have a separate Management API to do forest assignments. Subsequent ml-gradle support for this change.

Thanks for your consideration.

**Comment by rjrudin** [comment]
[3.1.0](https://github.com/marklogic-community/ml-gradle/releases/tag/3.1.0) introduced the "mlCreateForests" property, which can be set to false, so that when mlDeploy/mlDeployDatabases run, only the database payload file is deployed.

But based on your scenario, it sounds like that's not helpful because the forests are defined in the database payload file?

It's then a more general problem of - I'd like to update this resource, but I don't want to use all the fields in the payload file, I only want to send a subset of them specified via an include/exclude pattern. Right?

Arguably, the Mgmt API supports granular operations such as "add/remove index" - just specify a payload with only e.g. {"triple-index":true} in it. 

But for ad hoc operations, using a file-driven approach isn't good. File-driven is a good fit for application configuration that should be stored in version control and then packaged up. 

ml-gradle does have an "experimental" answer for this - using the Groovy shell - https://github.com/marklogic-community/ml-gradle/wiki/Groovy-shell-integration . I think that's a good way of supporting ad hoc behavior - i.e. you could do something like this:

    db = ml.db("my-database")
    db.tripleIndex = true
    db.save()

Thoughts on these two approaches then:

1. Deploy a resource and specify field names to include/exclude - e.g. mlDeployDatabases -PexcludeFields=forest; or mlDeployDatabases -PincludeFields=triple-index
1. Use the Groovy shell for ad hoc operations like enabling the triple index where using a payload file doesn't always make sense

**Comment by rjrudin** [comment]
I'm thinking the properties should really be "mlExcludeFields" and "mlIncludeFields", as they can be applied to any resource.

This would be a change in ml-app-deployer. It would need to be done in AbstractCommand, presumably in the new "adjustPayloadBeforeSavingResource" method, where it could see if excludeFields or includeFields is set. It would use PayloadParser to convert the payload into either an ObjectNode or Fragment, and then it would remove whatever fields need removing, and then write the payload back out to a string.

**Comment by miguelrgonzalez** [comment]
@rjrudin I will take a stab at this

**Comment by miguelrgonzalez** [comment]
pull request is up https://github.com/marklogic-community/ml-app-deployer/pull/218

**Comment by RobertSzkutak** [comment]
Hi,

I did some work with the customer in question this was affecting and we were able to through it by using @rjrudin suggestions of setting mlCreateForests to false and removing the forests from the payload. However, it would still be nice if there was a way to bootstrap those forests assignments and then ignore them and other settings when only making minor configuration changes (such as adding an index).

Generally speaking, DBAs want to make as few configuration changes as possible when running a deployment and not touch things that don't need to be changed. As a best practice for this customer, I told them to do forest configuration manually and to only store index info in the database.json file. I felt that approach would be the least error-prone from our working sessions.

My ideal situation would be a way to say 'gradle mlUpdateIndexes' and only have range indexes/fields/geo indexes/etc. updated for databases. 

This would be the equivalent of what Roxy could do with './ml bootstrap --apply-changes=indexes' .

It looks like mlIncludeFields will get us pretty close to what Roxy did. Perhaps we can just make the options abstract so mlIncludeFields=indexes will cover a large set of fields related to index configuration for example. That would be good enough for me.

Really appreciate everyone's time addressing this.

_____

Response to @xquery :

I've thought about v1/eval but with the amount of work required there I'd probably use Roxy instead.

> unsure what this may mean - today you need to prescribe the entire list of indexes
which if you are manually crafting http requests is annoying ... though the logic
for patching can be done either in the client or server. You do not need
to send all properties to just update indexes

In the JSON file for a database we store a lot of settings. As you said, not all of these need to be set (or reset, rather) just to update an index for example. I'd be okay with the patching happening on either the ml-gradle client side or ML Server side. I can certainly follow-up with a PATCH API RFE if the discussion trends in the direction of not wanting to do JSON patching with ml-gradle.

Really appreciate the time you took to write this.

**Comment by rjrudin** [comment]
@RobertSzkutak Do you think an "mlUpdateIndexes" task is worthwhile then? Like Jim said, it'd need to be updated periodically as new index fields are added to the JSON for a database, but that doesn't happen too often, I think. 

Right now, it's a pretty trivial task to throw together - just load up the JSON/XML for a database, and then drop everything except the "known" index fields. Would be invoked like:

    gradle -Pdatabase=example mlUpdateIndexes

(the task would be smart enough to go through all the database files and find the one with a name of "example")

**Comment by RobertSzkutak** [comment]
@rjrudin Yes, that would be perfect!

**Comment by rjrudin** [comment]
@RobertSzkutak I'm adding mlUpdateIndexes to 3.4.0 - for now, it'll run against every database, and it's trimming the payload for each to only include these properties (the near-duplicates are because of the differences in array property names between JSON and XML):

    getAppConfig().setIncludeProperties(
			"database-name",
			"stemmed-searches",
			"word-searches",
			"word-positions",
			"fast-phrase-searches",
			"fast-reverse-searches",
			"triple-index",
			"triple-positions",
			"fast-case-sensitive-searches",
			"fast-diacritic-sensitive-searches",
			"fast-element-word-searches",
			"element-word-positions",
			"fast-element-phrase-searches",
			"element-value-positions",
			"attribute-value-positions",
			"field-value-searches",
			"field-value-positions",
			"three-character-searches",
			"three-character-word-positions",
			"fast-element-character-searches",
			"trailing-wildcard-searches",
			"trailing-wildcard-word-positions",
			"fast-element-trailing-wildcard-searches",
			"word-lexicon",
			"word-lexicons",
			"two-character-searches",
			"one-character-searches",
			"uri-lexicon",
			"collection-lexicon",
			"element-word-query-through",
			"element-word-query-throughs",
			"phrase-through",
			"phrase-throughs",
			"phrase-around",
			"phrase-arounds",
			"range-element-index",
			"range-element-indexes",
			"range-element-attribute-index",
			"range-element-attribute-indexes",
			"range-path-index",
			"range-path-indexes",
			"range-field-index",
			"range-field-indexes",
			"field",
			"fields",
			"geospatial-element-index",
			"geospatial-element-indexes",
			"geospatial-element-child-index",
			"geospatial-element-child-indexes",
			"geospatial-element-pair-index",
			"geospatial-element-pair-indexes",
			"geospatial-element-attribute-pair-index",
			"geospatial-element-attribute-pair-indexes",
			"geospatial-path-index",
			"geospatial-path-indexes",
			"geospatial-region-path-index",
			"geospatial-region-path-indexes"
		)
