### ISSUE TITLE
Load modules strips file path prefix

### ISSUE THREAD

**Issue by damonfeldman** [marklogic-community/ml-gradle#273]
This may be a doc issue rather than a bug. I have a fairly simple setup to load some modules from ml-modules/root, and the top-level directory there is com.marklogic.hub, but the URIs are loaded without that prefix.

Here is some info showing the project setup:
```
MacPro-2903:hubmodulesonly dfeldman$ grep -i modules *
grep: build: Is a directory
build.gradle:        modulesDatabaseName = "data-hub-MODULES"
build.gradle:    // Gotta tell ml-gradle not to delete the modules database when we undeploy this
build.gradle:    mlAppDeployer.getCommand("DeployRestApiServersCommand").setDeleteModulesDatabase(false)
gradle.properties:mlModulesDbName=data-hub-MODULES
gradle.properties:mlReplaceTokensInModules=false
gradle.properties:mlModulePaths=ml-modules/root
grep: ml-modules: Is a directory
grep: src: Is a directory
```

```
MacPro-2903:hubmodulesonly dfeldman$ ls ml-modules/root
com.marklogic.hub	trace-ui
MacPro-2903:hubmodulesonly dfeldman$ gradle mlReloadModules

> Task :mlDeleteModuleTimestampsFile 
Deleting /Users/dfeldman/ProjectRepos/hubmodulesonly/build/ml-javaclient-util/module-timestamps.properties

> Task :mlClearModulesDatabase 
Clearing modules database
Finished clearing modules database

BUILD SUCCESSFUL in 4s
```
Then when I check module URIs I get this:
```
cts:uri-match("*mlcp*flow*") 
==>
/mlcp-flow-transform.xqy
```

Key parts here are that 
* the modules path is    ml-modules/root
* the top-level subdirectory there is com.marklogic.hub 
  * which contains the mlcp-flow-transform file
* the loaded URI does not include com.marklogic.hub

**Comment by rjrudin** [comment]
@damonfeldman I just did a test with a non-DHF project, where the module is at src/main/ml-modules/root/com.marklogic.hub/hello.xqy. And that was loaded as "/com.marklogic.hub/hello.xqy". 

Oh I see - mlModulePaths needs to "ml-modules", not "ml-modules/root". 

The module path refers to the directory that contains all of the different directories for different kinds of modules - see https://github.com/marklogic-community/ml-gradle/wiki/How-modules-are-loaded

**Comment by rjrudin** [comment]
@damonfeldman I'm closing this, as I've opened an issue in ml-javaclient-util to log each directory as it's scanned.
