### ISSUE TITLE
Add property to control what hosts get forests via group assignment

### ISSUE THREAD

**Issue by jkerr5** [marklogic-community/ml-gradle#274]
3.2.0 now supports `mlForestHosts` but one typical use of groups is to separate E and D nodes and only create forests on the hosts in the D node group. 

Can we add a `mlForestGroups` property as well? The behavior would be that forests would only be created on hosts in the groups listed. This would prevent having to know the host names of the hosts you want to have forests on.

**Comment by rjrudin** [comment]
Thanks @jkerr5 , this should be trivial to add (will be done in ml-app-deployer).

**Comment by rjrudin** [comment]
https://github.com/marklogic-community/ml-app-deployer/issues/217

**Comment by rjrudin** [comment]
@jkerr5 Does it make sense that this should take precedence over mlDatabaseHosts? I don't think someone would set both mlDatabaseHosts and mlDatabaseGroups, but if that were to happen, I think the right thing to do is use mlDatabaseGroups and ignore mlDatabaseHosts.

**Comment by jkerr5** [comment]
Yeah, I think mlDatabaseGroups should override mlDatabaseHosts. Maybe issue
a warning if both are set and mlDatabaseHosts is ignored?

One thing to double check is to make sure that the hosts that are
considered for replica forests only come from that pool too. I believe I
saw that when using mlDatabaseHosts, even the hosts not listed might end up
getting replica forests (maybe need a separate ticket to fix that).

**Comment by rjrudin** [comment]
Completed in ml-app-deployer - https://github.com/marklogic-community/ml-app-deployer/issues/217 

This can be tried out before the 3.3.0 release by using version 3.2.0-217 of ml-app-deployer.
