### ISSUE TITLE
When setup server, cannot set auth-method to digestbasic.

### ISSUE THREAD

**Issue by wwu666** [marklogic-community/ml-gradle#275]
ML 9 has auth-method of digest and digestbasic. Not sure what the differences is. ml-gradle fails if auth-method is set to digestbasic.

**Comment by rjrudin** [comment]
See https://github.com/marklogic-community/ml-gradle/wiki/Property-reference#rest-api-server-connection-properties - try setting mlRestAuthentication to "BASIC".

**Comment by rjrudin** [comment]
@wwu666 Please reopen this if setting mlRestAuthentication to BASIC isn't the solution. Under the hood, ml-gradle is using the Java Client API to connect to a REST API server.
