### ISSUE TITLE
Require property to be set in order to run mlUndeploy

### ISSUE THREAD

**Issue by rjrudin** [marklogic-community/ml-gradle#276]
This is to prevent an accidental "mlUndeploy" - e.g.

gradle -Pundeploy=true mlUndeploy

**Comment by manjsr** [comment]
How and where to set confirm property? as I'm also not able to undeploy. getting below error

Execution failed for task ':mlUndeployApp'.
> To execute this task, set the 'confirm' property to 'true'; e.g. '-Pconfirm=true'

**Comment by sunchouhan** [comment]
> How and where to set confirm property? as I'm also not able to undeploy. getting below error
> 
> Execution failed for task ':mlUndeployApp'.
> 
> > To execute this task, set the 'confirm' property to 'true'; e.g. '-Pconfirm=true'

Just tryt below command:

gradle mlUndeploy -Pconfirm=true

-Sunil
