### ISSUE TITLE
Document supported Manage API resources

### ISSUE THREAD

**Issue by rjkennedy98** [marklogic-community/ml-gradle#280]
## Documenting ML Gradle Configuration
I was wondering if there could be more documentation around the different ML Gradle configurations.

To me, it would be helpful to have a break down of the payloads with:
1. Which management endpoint is being hit (and perhaps a link to the documentation for the payload)
2. Which directory to put the payload in
3. Which property to change the default directory
4. Which port is used to deploy the payload
5. Which tasks trigger that payload deployment
6. Which example projects demo it

For someone who is new and even someone familiar it would be helpful to have an easy reference to figure out quickly how and where to add a new component or make a change to an existing component.

**Comment by rjrudin** [comment]
@rjkennedy98 To clarify, this sounds like an e.g. Wiki page for listing the Manage API resources that are supported. And for each one, at a minimum, define which directory the resource payloads go into, and the property that defines which port will be hit. And in addition to mlDeploy, what task can be used to deploy that resource. And possibly a sample project to demo it (I'm not as convinced about that one). 

There isn't a resource-specific property for changing the default directory; mlConfigPath is for the entire ml-config directory. 

Does that sound right? I'm going to rename this just to be a little more precise, as "configuration" can be a number of things.

**Comment by rjrudin** [comment]
@rjkennedy98 How is this for a start? - https://github.com/marklogic-community/ml-gradle/wiki/Resource-reference

**Comment by rjrudin** [comment]
I filled out https://github.com/marklogic-community/ml-gradle/wiki/Resource-reference for each of the resource types. I think this is a reasonable starting point - please open up a new ticket for any ideas on how to enhance this.
