### ISSUE TITLE
Creating servers with the same name in different groups

### ISSUE THREAD

**Issue by jedigo** [marklogic-community/ml-gradle#284]
When we add a server with a specific group, this will not be deployed if a server with the same name already exists in another group.

We get an error message like this:

> Task :mlDeployServers
Logging HTTP response body to assist with debugging: {"errorResponse":{"statusCode":"404", "status":"Not Found", "messageCode":"MANAGE-NOGROUPWITHSERVER", "message":"MANAGE-NOGROUPWITHSERVER: (err:FOER0000) No such group with server: group-id: GROUP_NAME server-id: SERVER_NAME"}}

**Comment by rjrudin** [comment]
@jedigo Do you get this same error when you try to do this manually via the Admin UI on port 8001? Generally, a Manage API error like this means MarkLogic isn't allowing something, and thus ml-gradle won't be allowed to do it either.

**Comment by jedigo** [comment]
Hi, Apologies for the delay in this.

Yes, we can create multiple identical servers in different groups either through the GUI, or even by posting to the management API.

I think the issue is that even though the server does not exist, we are still getting a lines like this in the debug output:

[DEBUG] [org.springframework.web.client.RestTemplate] GET request for "http://mlhost:8002/manage/v2/servers" resulted in 200 (OK)

[INFO] [com.marklogic.mgmt.resource.appservers.ServerManager] Found server with name of foo, so updating at path /manage/v2/servers/foo/properties?group-id=group-2


The issue is that the server with that name exists in group "Default" , but not in "group-2"

I think I may be able to get a pull request together to fix this, but I am not sure when I will get a chance to dig into the code far enough.

**Comment by rjrudin** [comment]
Thanks @jedigo , that helps isolate the issue to this method which has a "TODO" on it that we can now safely answer "yes" to: 

    /**
     * TODO Not sure yet whether we need to account for resourceUrlParams when doing an existence check.
     */
    public boolean exists(String resourceNameOrId, String... resourceUrlParams) {
        return getAsXml().resourceExists(resourceNameOrId);
    }

I'm assigning this to 3.5.0, though this will be a fix in ml-app-deployer and could be a 3.4.1 bugfix release.

**Comment by rjrudin** [comment]
@jedigo Will have a 3.4.1 release of ml-gradle and ml-app-deployer available today with a bugfix for this in it.

**Comment by jedigo** [comment]
Thanks, thats super quick!

**Comment by rjrudin** [comment]
@jedigo  3.4.1 is now available, give it a try. There's a test case in ml-app-deployer to verify that the "exists" check on ServerManager now takes the group-id into account, should work now then.

**Comment by jedigo** [comment]
Hi @rjrudin I can confirm this has fixed the issue.

Thanks again for the quick turnaround.
