### ISSUE TITLE
Exporting and Deploying using ml-gradle

### ISSUE THREAD

**Issue by GiangTHo** [marklogic-community/ml-gradle#288]
I was able to successfully run the export command but nothing was exported.  I ran the command:
gradle -PincludeTypes=databases,servers -Pregex=.*myapp.* mlExportResources
And replaced "databases,servers" with the actual server "ipaddess:port".  The resulting script:
![exportmlgradle](https://user-images.githubusercontent.com/35116128/34584380-7b8feeb0-f193-11e7-82ba-d651f04f441a.jpg)

When I go to the folder "src\main\ml-config", nothing was exported as no file was generated.

Another issue I ran into was I can't figure out how ml-gradle is configured to deploy databases using json files.  I believe it should be in the gradle.properties file where I saw in one of the example projects:
configDir.contentDatabaseFiles.add(new File("src/main/ml-config/databases/more-content-database-config.json"))

But in the gradle.properties file that I am currently using which was develop by another developer had no database configuration in the gradle.properties.  There were json files in the path ml-config/databases which it seems that gradle is looking for deploying.  Does gradle automatically look into ml-config/databases to deploy database json files?
Thanks,
Giang

**Comment by rjrudin** [comment]
What are the names of the resources that ".myapp" should match? "myapp" seems like it would be a prefix, in which case you'd want a regex of "myapp.*".

**Comment by GiangTHo** [comment]
Hi Rob,
The command I ran was:
gradle -PincludeTypes="serverip" -Pregex=.*myapp.* mlExportResources

I have the * before and after guess when I posted somehow they were taken out.
Thanks,
Giang

**Comment by rjrudin** [comment]
Try changing "serverip" to "servers". You'll see logging for every resource that's matched and which file it's written to.

**Comment by rjrudin** [comment]
Also, just to be safe, put the regex in double quotes, which is a "safe" way to specify Gradle property values on the command line.

**Comment by GiangTHo** [comment]
I'm tried using both "serverip" and localhost:9001 but it seems to keep pointing at localhost:8000.  And it's still not exporting anything from local host.  I've attached the information I get when I add --info to the command as well as marklogic server information on local host.
![localhost](https://user-images.githubusercontent.com/35116128/34680224-558fce42-f490-11e7-8b43-6be4cdfdde0b.jpg)
![marklogiclocalhost](https://user-images.githubusercontent.com/35116128/34680225-55e7a540-f490-11e7-8635-1f3894cd99f6.jpg)

**Comment by rjrudin** [comment]
"includeTypes" specifies the types of resources to export. You wouldn't put a hostname or a port number there - if you need to change those (i.e. if "localhost" and 8002 aren't correct, but I'm guessing they are), you'd use mlHost and mlManagePort for those. 

Try this:

    gradle -PincludeTypes=servers -Pregex=".*myapp.*" mlExportResources --info

**Comment by rjrudin** [comment]
Resolved this offline
