### ISSUE TITLE
Invoke security operations

### ISSUE THREAD

**Issue by rjrudin** [marklogic-community/ml-gradle#290]
Add a task for each of the POST operations at:

http://docs.marklogic.com/REST/POST/manage/v2/security

Should have a SecurityManager in ml-app-deployer that knows how to make the calls, and then just add tasks for each operation to ml-gradle - e.g. mlImportWallet.

**Comment by davidbcollins** [comment]
@rjrudin I will work on this, including the required enhancements for ml-app-deployer

**Comment by rjrudin** [comment]
Decided not to include support for this, as the API is so simple.
