### ISSUE TITLE
ml-gradle for a project that only has a modules database

### ISSUE THREAD

**Issue by tzejohn** [marklogic-community/ml-gradle#302]
Is this a valid use case for ml-gradle? Let's say I have an existing project where I have a content database and modules database, and that deployment also configures an app server. Now I want a separate project that references the existing deployed content database, but adds its own modules database to provide some other rest extensions in a separate app server. Is this something straightforward to do, i.e. removing all the content database commands, or would this break everything?

**Comment by rjrudin** [comment]
That should work fine. Be sure to set mlNoRestServer=true, in which case nothing is created except for that which is defined by resource files. So just have an e.g. databases/modules-database.json file, and you should be good to go.
