### ISSUE TITLE
Gradle XCC tasks: executing XQuery code via SSL doesn't work

### ISSUE THREAD

**Issue by jaklan** [marklogic-community/ml-gradle#306]
I can't successfully run Gradle XCC tasks to execute XQuery code on the server with SSL. The sample task looks like this:
```
task loadConfigs(type: com.marklogic.gradle.task.XccTask) {
    xccUrl = "xcc://${mlUsername}:${mlPassword}@${mlHost}:${mlRestPort}/${mlContentDatabaseName}"
    xquery = "xdmp:invoke('/XYZ/lib/loadConfigs.xqy',(" +
    "(xs:QName('folder')," + folder + ")," +
    "(xs:QName('schemas-folder')," + schemasFolder + ")," +
    "(xs:QName('json-path')," + jsonPath + ")" +
    "))"
}
```

and the error is:

```
* What went wrong:
Execution failed for task ':loadData'.
com.marklogic.xcc.exceptions.ServerConnectionException: Malformed Response: <!DOCTYPE HTML PUBLIC '-//IETF//DTD HTML 2.0//EN'>
   [Session: user=admin, cb=XYZ [ContentSource: user=admin, cb=XYZ [provider: address=XYZ, pool=0/64]]]
   [Client: XCC/9.0-1]
```

Properties related to SSL I have in gradle.properties:

```
mlSSLHostname=XYZ
mlSSLCertificateTemplate=XYZ
mlAdminScheme=https
mlManageScheme=https

mlManageSimpleSsl=true
mlAdminSimpleSsl=true
mlSimpleSsl=true
mlAppServicesSimpleSsl=true

mlAppServicesAuthentication=basic
mlRestAuthentication=basic
mlAdminAuthentication=basic
mlManageAuthentication=basic
```

Changing "xcc" to "xccs" in URI doesn't change anything.
Deploying an app to the server via gradle mlDeploy runs with success, so there's only problem with XCC tasks.

**Comment by grillazz** [comment]
+1 @jaklan

**Comment by rjrudin** [comment]
XccTask - https://github.com/marklogic-community/ml-gradle/blob/master/src/main/groovy/com/marklogic/gradle/task/XccTask.groovy - uses XccHelper - https://github.com/marklogic-community/ml-gradle/blob/master/src/main/groovy/com/marklogic/gradle/xcc/XccHelper.java - which doesn't yet support SSL:

    this.contentSource = ContentSourceFactory.newContentSource(new URI(uri));

There are a couple options:

1. If you have a REST server that points to your modules database, use com.marklogic.gradle.task.ServerEvalTask instead. The mlSimpleSsl property and mlRest* properties affect how the DatabaseClient is constructed for that task.
1. Don't extend XccTask, just make a task with a doLast block in it that constructs an XCC ContentSource with SSL enabled. 

Additionally, if you'd like to see SSL support for XCC, create an issue. I'm looking at the XCC Javadocs, and it looks like it'd be as simple as reusing the SSLContext that's used for REST connections.

**Comment by jaklan** [comment]
First option works like a charm, thank you @rjrudin :smile:
