### ISSUE TITLE
SSL support for XCC

### ISSUE THREAD

**Issue by jaklan** [marklogic-community/ml-gradle#307]
Currently there's no SSL support for XCC.

> XccTask - https://github.com/marklogic-community/ml-gradle/blob/master/src/main/groovy/com/marklogic/gradle/task/XccTask.groovy - uses XccHelper - https://github.com/marklogic-community/ml-gradle/blob/master/src/main/groovy/com/marklogic/gradle/xcc/XccHelper.java - which doesn't yet support SSL:
`this.contentSource = ContentSourceFactory.newContentSource(new URI(uri));`

The problem is described in #306 and commented by @rjrudin  [here](https://github.com/marklogic-community/ml-gradle/issues/306#issuecomment-363409381).

**Comment by rjrudin** [comment]
XccTask now has the following 3 properties

    String xccUrl
    SecurityOptions securityOptions
    ContentSource contentSource

If contentSource is populated, it's used. Otherwise, xccUrl and securityOptions are used to create a ContentSource. SecurityOptions is an XCC class - https://docs.marklogic.com/javadoc/xcc/com/marklogic/xcc/SecurityOptions.html

**Comment by rjrudin** [comment]
@jaklan Just released 3.4.1 yesterday to address this.
