### ISSUE TITLE
Error when redeploying an app server with the URL rewriter set

### ISSUE THREAD

**Issue by jkerr5** [marklogic-community/ml-gradle#308]
If I have a URL rewriter set for an app server, when I try to run `mlDeploy` more than once, I get the following error:

```
Logging HTTP response body to assist with debugging: {"errorResponse":{"statusCode":400, "status":"Bad Request", "messageCode":"RESTAPI-INVALIDCONTENT", "message":"Your bootstrap payload caused the server to throw an error.  Underlying error message: REST-INVALIDPARAM: (err:FOER0000) Invalid parameter: Port 9041 is in use."}}
```

This is with a server json file that looks like this

```
{
  "server-name": "%%NAME%%",
  "url-rewriter": "/myrewriter.xml"
}
```

**Comment by jkerr5** [comment]
What's interesting is that I can run `mlDeplyServers` over and over without issue.

**Comment by rjrudin** [comment]
Is this a REST API server? My guess is yes, and fun fact - the GET to /v1/rest-apis will only return servers that have the string "rest-api" in their rewriter. Not kidding. :)  If you change the url-rewriter to "/rest-api/myrewriter.xml" for instance, should work fine. This isn't an ml-gradle thing, it's just how /v1/rest-apis determines if the REST API instance exists or not.

**Comment by jkerr5** [comment]
It is a REST API server but digging into the code, it looks like the URL rewriter has to start with "/MarkLogic/rest-api/". So, I'll need to create a different app server with my own rewriter.

It's certainly a strange error condition that if you change the URL rewriter in a REST API config, there's basically no way to back out of it other than deleting the app server.

Maybe there should be a warning message if you find a REST API config that has a URL rewriter set.

**Comment by rjrudin** [comment]
I'm pretty sure it's just "rest-api" that has to be in there - I know that works for one project, where the rewriter has "rest-api" in the path but does not start with "/MarkLogic/". 

I'll verify that a warning message of some sort can be logged - i.e. if the "rest-api-server.json" file has a url-rewriter in it.

**Comment by jkerr5** [comment]
This is the match expression in ML 9.0-4:
```
^/MarkLogic/rest-api/(8000-rewriter|rewriter|rewriter-noxdbc)\.xml$
```

**Comment by rjrudin** [comment]
I opened https://github.com/marklogic-community/ml-app-deployer/issues/242 to log a warning via ml-app-deployer.
