### ISSUE TITLE
DeleteCollectionsTask does not delete all documents

### ISSUE THREAD

**Issue by sastafford** [marklogic-community/ml-gradle#309]
I've got a task to delete all documents (~13K) in a collection using a DeleteCollectionsTask.  It is not deleting all of them.  It seems to delete only about half.  

Using ml-gradle 3.4.0

**Comment by rjrudin** [comment]
Just got the same thing with a collection of 24k docs. I'll see what's up.

**Comment by rjrudin** [comment]
I was able to reproduce this in the Documents database by first running this script in qconsole:

    for $i in 1 to 10000
    return xdmp:document-insert("/test/" || $i || ".xml", <hello>{$i}</hello>, (), "test")

And then I ran this program to delete the docs. It first deletes 5000, then 3000, then 1000, and then the last 1000.

    DatabaseClient client = DatabaseClientFactory.newClient("localhost", 8000, "Documents",
		new DatabaseClientFactory.DigestAuthContext("admin", "admin"));
	try {
			DataMovementManager dmm = client.newDataMovementManager();
			StructuredQueryDefinition query = client.newQueryManager().newStructuredQueryBuilder().collection("test");
			QueryBatcher queryBatcher = dmm.newQueryBatcher(query);
			queryBatcher.onUrisReady(new DeleteListener());
			dmm.startJob(queryBatcher);
			queryBatcher.awaitCompletion();
			dmm.stopJob(queryBatcher);
		} finally {
			client.release();
		}

**Comment by jmakeig** [comment]
Does the above test case indicate that DMSDK on its own behaves as you’d expect, but when invoked from ml-gradle, not so much? In the ml-gradle test were there other things writing to the database in parallel with the delete?

**Comment by rjrudin** [comment]
@sastafford Try adding "-PconsistentSnapshot=true" when you run the Gradle task. I'm curious if at least all the documents get deleted. I'm getting mixed results depending on the dataset.

**Comment by rjrudin** [comment]
@sastafford Are you using "-Pdatabase"? Curious if there's a difference between going through mlRestPort and not specifying a database vs going through 8000 and specifying -Pdatabase.

**Comment by sastafford** [comment]
All the documents were deleted with the consistentSnapshot flag set to true.  

This is the task I'm running.  I passed the snapshot flag via the command line.  

```groovy
task deleteBabyNames (type: com.marklogic.gradle.task.datamovement.DeleteCollectionsTask) {
    collections = ["baby-name"]
}
```
I don't think I can pass in a consistentSnapshot property on this DeleteCollectionsTask.  I tried.  Is that a property that should be added?

**Comment by rjrudin** [comment]
It has to be a Gradle property. You can define that as part of the Gradle task though:

    doFirst { project.ext { consistentSnapshot = "true" } }

**Comment by rjrudin** [comment]
Half of this is that ml-gradle (ml-javaclient-util really) should default some jobs to use a consistent snapshot, and then there's also a bug to fix in ML too - https://github.com/marklogic/java-client-api/issues/890

**Comment by rjrudin** [comment]
I created https://github.com/marklogic-community/ml-javaclient-util/issues/91 . Closing this as the other half of this ticket is an ML bug.
