### ISSUE TITLE
Lack of docs on specifying different configuration per environment

### ISSUE THREAD

**Issue by damonfeldman** [marklogic-community/ml-gradle#315]
The wiki does have Environment-based properties section here:
https://github.com/marklogic-community/ml-gradle/wiki/Configuring-ml-gradle#environment-based-properties 

But it does not cover how you use the saliman plugin (and need it) to have gradle-<environment>.properties and vary config per environment.

**Comment by rjrudin** [comment]
@damonfeldman That section has a link to the sample project - https://github.com/marklogic-community/ml-gradle/tree/master/examples/properties-project - which provides instructions with a working example on how to use the properties plugin (in addition of course to the docs for the properties plugin themselves). 

I think what you said is not covered is covered by that, so I'm going to close this. Please reopen if there's something else missing.
