### ISSUE TITLE
Assign forests over multiple mount points

### ISSUE THREAD

**Issue by paul-hoehne** [marklogic-community/ml-gradle#324]
Let's assume the following situation.  On a cluster of 3 hosts, there are 3 mount-points.  For example, Host 1, 2 and 3 (H1, H2, and H3) each have mounts /mldata1, /mldata2, and /mldata3 (M1, M2, and M3).    For example, each mount is a separate GP2 filesystem on AWS.  The forest assignment policy should multiplex the forests on hosts with the following constraints:

1) for each host, primary forests should be balanced across the mounts (as much as possible).
2) replica forests should be balanced across the remaining hosts, such a failover will spread the load across the cluster.
3) on each host, the replicas should be balanced across the mount points.

For example, H1 has mounts M1, M2, and M3.  With two forests per mount point, that should imply M1 has forests F1 and F2, M2 has forests F3 and F4 and M4 should have forests M5 and M6.  H2 (which has Forests F7-F12), would also be spread over its three mounts, etc.

The replica for H1, M1, F1 might be on H2, M2.  the replicat for H1, M1, F2 might be on H3, M3.  The replicat for H1, M2, F3 might be on H1, M1.  The replica for H1, M2, F4 might be on H3, M1, etc.

**Comment by rjrudin** [comment]
This sounds fun to work on - everything will be done in ml-app-deployer - but adding "help wanted" just in case someone else thinks it'd be interesting too and would like to do it.

**Comment by rjrudin** [comment]
@paul-hoehne How would you want use properties to specify the different data directories to use? This lists all the current properties for forest directories - https://github.com/marklogic-community/ml-gradle/wiki/Property-reference#database-and-forest-properties 

I think we'd need a double-delimited string here, e.g.:

    mlForestDataDirectory=path1,path2,path3 // This is a single value, becomes a sequence of values
    mlDatabaseDataDirectories=database1,path1|path2|path3,database2,path1 // This is a sequence of values, would become a double-delimited "map" of values

**Comment by rjrudin** [comment]
@paul-hoehne Do you envision that the mount points would be the same on each host?

**Comment by paul-hoehne** [comment]
+1

**Comment by rjrudin** [comment]
This will be supported by the mlDatabaseDataDirectories property, which now supports multiple data directories per host.
