### ISSUE TITLE
unit-test-project example points to missing dependency

### ISSUE THREAD

**Issue by dmcassel** [marklogic-community/ml-gradle#325]
`com.marklogic:ml-unit-test-client:0.9.1` is not visible in `https://dl.bintray.com/rjrudin/maven/com/marklogic/marklogic-unit-test-client/` or in jcenter (only 0.4)

**Comment by rjrudin** [comment]
It was renamed to "ml-unit-test-client", visible at:

https://dl.bintray.com/rjrudin/maven/com/marklogic/ml-unit-test-client/

Note that 0.9.0 is visible via https://jcenter.bintray.com/com/marklogic/ml-unit-test-client/ , but 0.9.1 is not there yet - I emailed the jcenter folks to find out what's up. And the zip file of XQuery code still isn't visible via that jcenter URL, still have to go to the rjrudin-specific one - hoping for help from jcenter on that too.
