### ISSUE TITLE
sample deployment of ml unit test in DHF

### ISSUE THREAD

**Issue by joecrean** [marklogic-community/ml-gradle#327]
this was manually hacked together because of issues with DHF and ml-gradle which prevent the automatica deployment from working correctly. 

I have hardcoded the port for the test App Server to 8135 - look in the file ``rest-api.json`` to change it.

**Comment by joecrean** [comment]
[tmp.zip](https://github.com/marklogic-community/ml-gradle/files/1829593/tmp.zip)

**Comment by joecrean** [comment]
sorry guys this should really be under DHF..

**Comment by rjrudin** [comment]
@joecrean Should I close this then?

**Comment by joecrean** [comment]
closing this as it is really a DHF issue
