### ISSUE TITLE
provide a task to write configuration packages

### ISSUE THREAD

**Issue by ehennum** [marklogic-community/ml-gradle#333]
MarkLogic 9.0-5 is expected to add support for configuration packages.

After that lands, ml-gradle could provide more convenient, reliable, and performant configuration by adding a task that takes a configuration package from the file system and sends it to the server.

Ideally, the task would call an API exposed in the Client Java API:

https://github.com/marklogic/java-client-api/issues/910

**Comment by grechaw** [comment]
That about matches my reading of it, @rjrudin

**Comment by jmakeig** [comment]
Pinging @xquery too.

**Comment by rjrudin** [comment]
Added mlDeployConfigurations - almost all the work is in ml-app-deployer (as usual).
