### ISSUE TITLE
How to handle releases built from different teams input ?

### ISSUE THREAD

**Issue by kosed** [marklogic-community/ml-gradle#336]
As a MarkLogic application manager,
I want to have automated MarkLogic releases
So that multiple/different teams can contribute according to their respective roles.

In the very general case: 
- Team DEV will produce the release package (source + config)
- Team ADMIN will collect the package, possibly merge it to another and run necessary gradle tasks.

ml-gradle currently allows multiple roles to be defined and actually only ADMIN team will usually have access to highly privileged accounts (Security and Manage admin).
DEV team should not (as the cluster is managed by the ADMIN team).

The current limitation we are facing is that the DEV provided package can contain anything like: 
- User/role update, but this is not a problem if the gradle tasks are run with a non security privileged user (fine for most operations)
- Application server config update (Manage admin role is enough to run that)

The 2 actions above are of course not acceptable in the current scenario.

From there, multiple options can be considered in order to support our use case.
Among others:
1. Provide a validation mechanism for the payloads' contents
2. Provide some level of package composition where different teams will be allowed different payload types/directories (this can be done at payload file level first and possibly down to field level)

**Comment by kosed** [comment]
**Option 1: Provide a validation mechanism for the payloads' contents**

After discussing with @rjrudin, there is a somewhat quick path to have some sort of validation.
The output of running an ml-gradle command will be saved to a file.
The content of the file can then be checked for "unauthorized" properties/values
As this have to be automated, there need to be an existing white/black list of properties
This will then be used for the validation.

Resources/links:
- Interceptor pattern: https://github.com/marklogic-community/ml-app-deployer/issues/263#issuecomment-377418704
- script generation: https://github.com/marklogic-community/ml-gradle/wiki/Generating-a-shell-script
- Similar concern: https://github.com/marklogic-community/ml-gradle/issues/314

**Comment by kosed** [comment]
Mirored on DHF https://github.com/marklogic-community/marklogic-data-hub/issues/887

**Comment by kosed** [comment]
As suggested by @miguelrgonzalez, there is also a solution path in considering the package creation itself. https://docs.gradle.org/current/userguide/distribution_plugin.html

Intermediary sub packages can be created (using different source folders) so that admins stuff are selected from one folder and dev stuff from another.

To be effective, this composition will have to be made by the admins (otherwise we fallback to the initial situation).
Something like:
- devs create and sends a first package with whatever they need/want
- admins maintain there own admin config source folder
- admins uncompresses the dev release
- admins rerun a packaging by composing from both dev and admin sources
- Final package is ready for deployment.

**Comment by kosed** [comment]
**Option 2: Provide some level of package composition where different teams will be allowed different payload types/directories (this can be done at payload file level first and possibly down to field level)**

Below is a demonstration code to be added in build.gradle.
The class ConfigDirCustom extends the usual ConfigDir class and provides the option to set a different path for each folder containing config files (databases, servers, etc...)

```
import java.util.HashMap;
import com.marklogic.appdeployer.ConfigDir;

public class ConfigDirCustom extends ConfigDir {

  private HashMap<String, String> folders;
  private File baseDir;

  public ConfigDirCustom() {
    HashMap<String, String> folders = new HashMap<String, String>();
    folders.put("default", "src/main/ml-conf");
    setBaseDir(folders);
  }

  public ConfigDirCustom(HashMap<String, String> folders) {
    setBaseDir(folders);
  }

  public void setBaseDir(HashMap<String, String> folders) {
    this.folders = folders;
    this.baseDir = new File(folders.get("default"));
    initializeContentDatabaseFiles();
  }

  public File getBaseDir() {
    return baseDir;
  }

  public String getFolderPath(String key){
    String path = folders.get(key);
    if (path == null) {
      path = folders.get("default");
    }
    return path;
  }

  public File getTriggersDir() {
    return new File(getFolderPath("triggers"), "triggers");
  }
  public File getAlertDir() {
    return new File(getFolderPath("alert"), "alert");
  }
  public File getTemporalDir() {
    return new File(getFolderPath("temporal"), "temporal");
  }

  public File getServersDir() {
    return new File(getFolderPath("servers"), "servers");
  }
  public File getSecurityDir() {
    return new File(getFolderPath("security"), "security");
  }

}

ext {

  String baseDirAdmin = "src/main/ml-admin";
  String baseDirDev = "src/main/ml-conf";

  HashMap<String, String> folders = new HashMap<String, String>();
  folders.put("default", baseDirDev);
  //folders.put("databases", baseDirDev); //Let's rather use the default above :-)
  folders.put("triggers", baseDirDev);
  folders.put("alert", baseDirDev);
  folders.put("temporal", baseDirDev);

  folders.put("security", baseDirAdmin);
  folders.put("servers", baseDirAdmin);

  mlAppConfig {
    setConfigDir(new ConfigDirCustom(folders));
  }

}
```

**Comment by rjrudin** [comment]
Can mlConfigPaths be used here:

    mlConfigPaths=src/main/ml-admin,src/main/ml-conf

Then, when the Admin teams does a deployment into e.g. production, it could set this property to just the ml-conf directory so that e.g. security and servers resources are not deployed:

    mlConfigPaths=src/main/ml-conf

**Comment by rjrudin** [comment]
@kosed I think mlConfigPaths can handle this, so I'm closing this issue - please reopen if I'm misunderstanding.
