### ISSUE TITLE
mlgradle - how to use existing rest server

### ISSUE THREAD

**Issue by RubinaV** [marklogic-community/ml-gradle#355]
Hi, 
I am setting up discovery app and want to use preexisting db and rest app server which is manually created. When I configure port of my rest server in gradle properties and run mlDeploy command it tried to create new rest server and complains about port already being used.

Is there any way where I can provide configuration to use existing db name and rest port instead of creating new ?

**Comment by rjrudin** [comment]
Which version of ML are you on, and which version of ml-gradle?

When ml-gradle uses mlRestPort, it makes a call to /v1/rest-apis to see if a REST server exists already on that port. The behavior of that endpoint changed between ML 9.0-3 and 9.0-4, such that the bug you mention happens in ml-gradle prior to version 3.6.0 of ml-gradle. With 3.6.0 or greater of ml-gradle, you shouldn't run into that bug.

**Comment by RubinaV** [comment]
I am using ML version - **9.0-5** and ml-gradle version **2.9.0.** Can I upgrade the version by simply changing it in build.gradle file as mentioned below or do I need to download anything specific to this.
id "com.marklogic.ml-gradle" version "Higer version here"

Also could you pls let me know if I use existing rest server , will framework use the db associated with the same rest server ? I have rest server and db created manually and I am intending to use the same through discovery app.

Thanks for the prompt response !!

**Comment by rjrudin** [comment]
Right, just change 2.9.0 to 3.7.1 (the current latest version). 

If ml-gradle sees a server at the port, it won't create anything. 

Alternatively, you can also set mlNoRestServer=true in gradle.properties to disable even checking for a REST server.

**Comment by RubinaV** [comment]
Hi,

If I set mlNoRestServer=true , it will skip rest server creation. That will fix my error but then how can I point Discovery app to access existing database to load / search data from ?

Thanks.

**Comment by rjrudin** [comment]
Just add a file under ml-config/servers that has the name of your app server and the port, and then set the content-database (and optionally modules-database) properties.

**Comment by rjrudin** [comment]
@RubinaV I think the above is the solution for you, please reopen if not the case.
