### ISSUE TITLE
Permissions error setting external security on app server

### ISSUE THREAD

**Issue by jonesyface** [marklogic-community/ml-gradle#356]
As I understand it, the manage user (set using mlManageUsername/Password) is by default used when deploying application resources via the Management REST API. Meanwhile, the security user (set using mlSecurityUsername/Password) is used for deploying users/roles etc. If this user isn't defined then the manage user can do this job if it is given the "security" role but the opportunity is there to keep these permissions in separate users.

The issue I'm finding is when deploying an application server using the mlDeployServers command where the server is using a pre-created external security configuration defined within the payload. By default the manage user is used for the deployment but I'm seeing a ADMIN-NOSUCHEXTERNALSECURITY error when this is run. This is the case whether or not the security user is defined.

If the manage user is given the "security" role then this error disappears. This therefore appears to be a permissions issue for the manage user in having read access to the external security configuration when it doesn't have the "security" role.

Is there any way for the security user to be used for this particular part of this task rather than the manage user? It would be good to avoid giving the manage user the "security" role just for this scenario, though I could look into giving the user a specific privilege that gives them read access the external security config (assuming this exists).

**Comment by rjrudin** [comment]
@jonesyface This is an interesting issue, thanks for the good write-up on it. 

@xquery Can you confirm what's above? 

I'm not sure of a good solution here other than for ml-gradle to say "If this server config has an external-security field in it, then I need to use the security user". The logs will make it clear that's being done.

**Comment by xquery** [comment]
I can confirm there are a handful of scenarios and situations in RMA that require both manage-admin and security role ... the docs for manage/v2 endpoints should highlight when if they dont then thats a doc bug. This design just follows status quo established in the server.

**Comment by jonesyface** [comment]
Thanks for the responses guys.

The manage/v2 documentation does mention requiring the security and manage-admin roles for the external-security endpoints but it's not mentioned in the server endpoints, so arguably an omission for this specific scenario. If you feel it's worth raising this then I can do that.

Do you know if there's a specific privilege/set of privileges I can set rather than giving the manage user the full security role? I've looked at the list of privileges set on the security role and tried adding all the external-security ones to the manage user but no luck.

If not then it sounds like, for now at least, I'll need to add the security role until we have a fix for this (if you decide it merits one).

**Comment by rjrudin** [comment]
@jonesyface The fix for this will be in ml-app-deployer, I'll write up a ticket and include it in the upcoming 3.8.0 release (upcoming = this week).

**Comment by rjrudin** [comment]
Fixed via https://github.com/marklogic-community/ml-app-deployer/issues/284
