### ISSUE TITLE
Privileges aren’t automatically deployed as part of mlDeploy

### ISSUE THREAD

**Issue by jmakeig** [marklogic-community/ml-gradle#366]
From marklogic/marklogic-data-hub#1128 via @sparnell: 

> Executing `mlDeploy` does not deploy URI privileges located in `user-config/security/privileges`.
> `mlDeployPrivileges` must be run manually after deploying the application.

**Comment by rjrudin** [comment]
Ignoring DHF for a moment (I'll respond to that in the DHF ticket), I can't reproduce this via mlDeploy, mlDeploySecurity, or mlDeployPrivileges. I've had one project also where privileges have been deployed for a few years via mlDeploy. I checked CommandMapBuilder in ml-app-deployer just to verify that DeployPrivilegesCommand is in there, and it is. 

To verify that privileges are deployed, just run with "-i" included and look for logging mentioning DeployPrivilegesCommand.
