### ISSUE TITLE
xls, xlsx and xlsm are corrupted in the Module database

### ISSUE THREAD

**Issue by Chunyu01** [marklogic-community/ml-gradle#375]
We tried to put the spreadsheet in src/main/ml-modules/root/. It is loaded into Module database.
However, it is corrupted. 
It can not open vie rest API. for example, http://localhost:8010/test2.xlsx.
[test2.xlsx](https://github.com/marklogic-community/ml-gradle/files/2340017/test2.xlsx)

**Comment by rjrudin** [comment]
Assuming this is not a DHF project, just add the following to gradle.properties:

    mlAdditionalBinaryExtensions=xlsm

Docs for this are at - https://github.com/marklogic-community/ml-gradle/wiki/Property-reference#module-and-schema-properties 

Please close if that fixes it.

**Comment by rjrudin** [comment]
Also added https://github.com/marklogic-community/ml-gradle/wiki/Debugging-module-loading#modules-getting-corrupted

**Comment by Chunyu01** [comment]
Yes, that property is working. Thanks.
