### ISSUE TITLE
mlTestRestPort no longer replaced in test suite files

### ISSUE THREAD

**Issue by tdiepenbrock** [marklogic-community/ml-gradle#376]
From customer email:

I upgraded our ml-gradle from 2.8.0 to 3.8.2 (a couple weeks ago) and we tried running the test suite this week but it failed. After tracing the issue, I found that the new version 3.8.2 is no longer replacing the variable name “mlTestRestPort” in the test suite files. So the failure always results in “mlTestRestPort variable not defined”. This worked fine in 2.8.0, not sure which version between that and 3.8.2 killed it, but definitely an issue.

**Comment by rjrudin** [comment]
Closing this, as I believe the above link addresses how the token replacement changes between 2.8 and 3.x. Please reopen if not the case.
