### ISSUE TITLE
mlDeleteCollections doesn't always complete

### ISSUE THREAD

**Issue by grtjn** [marklogic-community/ml-gradle#380]
Observing erratic messages like `Cancelling task to run the job completion listeners since the batcher is stopped` when doing various collection delete. Sometimes first, sometimes middle one or ones, sometimes none. Sleeping or waiting for taskserver in between doesn't help. Doing all in one go (comma-separated list) or separate doesn't seem to make a difference either.

We are running something like:
```
./gradlew mlDeleteCollections "-PenvironmentName=$env" -Pconfirm=true -Pdatabase=data-hub-STAGING -Pcollections=coll1
./gradlew mlDeleteCollections "-PenvironmentName=$env" -Pconfirm=true -Pdatabase=data-hub-STAGING -Pcollections=coll2
./gradlew mlDeleteCollections "-PenvironmentName=$env" -Pconfirm=true -Pdatabase=data-hub-STAGING -Pcollections=coll3
```

Data-hub 3.0.0 (with its default ml-gradle)
gradle-wrapper points to gradle 4.8

**Comment by rjrudin** [comment]
See the note at the top of https://github.com/marklogic-community/ml-gradle/wiki/DMSDK-Tasks - I believe DHF is using 3.4.0 ml-gradle, and 3.5.0 is the version that defaults DMSDK jobs to using a consistent snapshot.

**Comment by grtjn** [comment]
How is consistent snapshots related to those messages? The relation is not obvious to me..

**Comment by grtjn** [comment]
PS: I added that flag, doesn't seem to help..

**Comment by grtjn** [comment]
How can I upgrade ml-gradle used with datahub? I'm mostly running gradle commands from commandline..

**Comment by rjrudin** [comment]
I don't know if it's recommend to try to change the underlying ml-gradle version that DHF is using.

Have you seen this happen on a DHF4 project, which uses ml-gradle 3.9.0?

**Comment by rjrudin** [comment]
Not sure if you can reproduce this still as it was on DHF 3, but issues with deleting collections not working have usually led to this issue in the Java Client - https://github.com/marklogic/java-client-api/issues/890 - which was als reported here as well - https://github.com/marklogic-community/marklogic-data-movement-components/issues/19#issuecomment-479533290 . I noticed in your commands that you're specifying the "database" parameter, which is what leads to the bug in the Java Client. The workaround is to connect to the REST server associated with the database that you want to delete collections from.
