### ISSUE TITLE
RFC: Package Server-Side JavaScript modules

### ISSUE THREAD

**Issue by jmakeig** [marklogic-community/ml-gradle#381]
As a MarkLogic Endpoint Developer, I want to be able to manage sophisticated data logic in JavaScript using the tools, libraries, and techniques that I know in order to get more value out of MarkLogic sooner.

[Server-Side JavaScript](https://docs.marklogic.com/guide/jsref/language) was a big step forward in making MarkLogic’s in-database programming environment more accessible to developers. It also opens up the possibility of using external libraries from the broader JavaScript ecosystem. However, today managing those dependencies is tricky and MarkLogic does not yet support—or may never support—capabilities like [ES2015 modules](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import) or [TypeScript](https://www.typescriptlang.org), which are seen as table stakes in the [Node](https://nodejs.org/en/) and browser communities.

The proposal here is for ml-gradle to optionally apply a packaging step before loading JavaScript to a modules database. By default, I'd propose using [Rollup](https://rollupjs.org/guide/en).

* Declare and manage dependencies with npm: Rollup has CommonJS and Node modules plugins that allow packaged code to use [Node.js’s package resolution rules, including `node_modules`](https://nodejs.org/api/modules.html). This would allow MarkLogic developers to tap into [npm](https://www.npmjs.com).
* ES2015 modules and tree shaking: Rollup defaults to ES2015 modules. Because ES2015 modules are declarative, Rollup can do optimizations around only bundling code that is used and discarding unused modules or even exports within a module. This is called “tree shaking”. The result is that developers get to use ES2015 modules and the resulting code is smaller and less complex than with manually managed CommonJS(ish) modules today. There’s also anecdotal evidence that smaller dependency graphs may improve JavaScript performance in MarkLogic modules. _(This hypothesis still needs to be tested.)_
* Rollup has a rich [plugin architecture](https://github.com/rollup/rollup/wiki/Plugins) that would allow other processing steps, such as [transpiling TypeScript](https://www.npmjs.com/package/rollup-plugin-typescript2) to vanilla ES2015 or [swapping out flags](https://github.com/rollup/rollup-plugin-replace), such as Node’s `process.env.NODE_ENV` to configure development, test, or production environments at build-time, already a concept in Gradle. This would allow developers to use the upstream tools that they’re accustomed to without MarkLogic having to explicitly support these.

**Comment by rjrudin** [comment]
Can you put together an example project with e.g. a single SJS module that has dependencies that npm can resolve, and then describe what you expect to be in the ML modules database after running mlLoadModules? That'll give me something to tinker with.

**Comment by jmakeig** [comment]
Yes. I’ll try to do that this weekend.

Until then, at a high-level, what Rollup (or Webpack or Bower) does is walk the dependency graph and consolidate every thing into (literally) a single `.sjs` file. So your entire “application" would be packaged in one `.sjs` file. Thus module upload from Gradle’s perspective would be to load one file into a modules database, rather than the entire dependency graph. From the developer’s persepctive, they get the benefits of modular code and all of the mature dev tooling around it (e.g. npm, TypeScript, ES2015 modules) without having to wait for MarkLogic to support each of those capabilities in its built-in JavaScript environment.

**Comment by jmakeig** [comment]
The only significant issue that I see here—and it’s pretty significant—is the difficulty of debugging bundled code. Stack traces will reflect the bundled code, not the original sources. Of course, the way to handle this is with sourcemaps. Browsers use sourcemaps automatically. There looks to be a [userland solution](https://github.com/mozilla/source-map), though.

**Comment by jmakeig** [comment]
[Argh](https://github.com/evanw/node-source-map-support/issues/197#issuecomment-422451035).

**Comment by jmakeig** [comment]
[gradle-js-plugin](https://github.com/eriwen/gradle-js-plugin) (Apache 2.0)

**Comment by abhairaj** [comment]
@jmakeig Do you know if there's any movement on this issue? I'm a developer working with MarkLogic quite a bit and would love to be able use Typescript in my ML server development. Thanks for bringing it up.

**Comment by rjrudin** [comment]
Closing, as I don't believe this will be considered within scope for ml-gradle.
