### ISSUE TITLE
Scheduled tasks with same task path will not deploy

### ISSUE THREAD

**Issue by bradmann** [marklogic-community/ml-gradle#387]
I've got 2 applications that both use a scheduled task with the same task path:

> /scheduledTasks/writeTelemetry.sjs

The scheduled tasks have different context and modules database values. ml-gradle will not allow me to deploy the second task because both have the same task-path.

**Comment by rjrudin** [comment]
The reason for this is that in order for ml-gradle to determine the URL for a task, it has to determine the ID of the task. It does that by using the task-path to figure out what the ID is. But as you've found, if you want multiple scheduled tasks with the same task-path, it won't work out. 

So the solution involves using more properties than just the task-path - thoughts on this? Perhaps task-path/task-database/task-modules would suffice? 

The workaround for this is to either clone the task module with a new name or have two task modules call the same library function.

**Comment by rjrudin** [comment]
Opened a ticket in ml-app-deployer for this.
