### ISSUE TITLE
Use mlLoadSchemas to load TDE template

### ISSUE THREAD

**Issue by lifan0127** [marklogic-community/ml-gradle#388]
When I tried to use `mlLoadSchemas` to load a TDE template into my schema data, the template was loaded but wasn't assigned to the `http://marklogic.com/xdmp/tde` and hence not activated. Is it a normal behavior, or are there other ways to load TDE templates? Thanks!

**Comment by rjrudin** [comment]
What directory do you have your templates in? See https://github.com/marklogic-community/ml-gradle/wiki/Loading-schemas - putting the templates in src/main/ml-schemas/tde should ensure that they get the TDE collection.

**Comment by lifan0127** [comment]
Thanks @rjrudin. I had the template under /ml-schemas. Once I moved it to /tde it worked.
