### ISSUE TITLE
ml-unit-test on jcenter

### ISSUE THREAD

**Issue by prestonmcgowan** [marklogic-community/ml-gradle#394]
I see ml-unit-test in jcenter on bintray.
https://bintray.com/bintray/jcenter/ml-unit-test

So can this be updated?

https://github.com/marklogic-community/ml-gradle/blob/4730db04307266bf3f9681796084a1366ec54a91/build.gradle#L19

**Comment by rjrudin** [comment]
Yes, good catch - it's also named "marklogic-unit-test" since 0.12.0 for that project.
