### ISSUE TITLE
Add support for query partitions

### ISSUE THREAD

**Issue by dmcassel** [marklogic-community/ml-gradle#397]
To use Tiered Storage, I want to set up query partitions. Doesn't look like that's currently supported.

**Comment by miguelrgonzalez** [comment]
@rjrudin I got it

**Comment by miguelrgonzalez** [comment]
@dmcassel kind off. I did have a look, agreed with @rjrudin on the approach and then got sidetracked...
Next week I should have time again to get it done.

**Comment by dmcassel** [comment]
Okay. No pressure (not sure my current client will be able to use it after all), just checking in.

**Comment by rjrudin** [comment]
@dmcassel Is this the right endpoint to use http://docs.marklogic.com/REST/POST/manage/v2/databases/[id-or-name]/partition-queries ? Or is it http://docs.marklogic.com/REST/POST/manage/v2/databases/[id-or-name]/partitions ?

**Comment by dmcassel** [comment]
Looks like the partition-queries endpoint is the right one. The partitions endpoint is for range partitions. If that's not supported, it would be good to get that in too at some point.

**Comment by rjrudin** [comment]
This will be new tasks, main work will be in ml-app-deployer
