### ISSUE TITLE
mlNewProject doesn't generate scaffolding

### ISSUE THREAD

**Issue by nizdobs** [marklogic-community/ml-gradle#398]
I invoked mlNewProject. The wizard prompted me for values. I got message that it was updating build.gradle, writing a bunch of environment specific property files, making ml-config & ml-modules directories, writing scaffolding files, and that the build was successful. But none of this was done. And when I did an mlDeploy I ended up with the default my-app on port 8003 and myapp-content and myapp-modules databases. 
```
Liesel:~/Documents/scratch/2018-11-13-TDE$ gradle mlNewProject
:mlNewProject
Welcome to the new project wizard. Please answer the following questions to start a new project.
Note that this will overwrite your current build.gradle and gradle.properties files, and backup copies of each will be made.
[ant:input] Application name: [myApp]
2018-11-13-TDE
[ant:input] Host to deploy to: [localhost]

[ant:input] MarkLogic admin username: [admin]

[ant:input] MarkLogic admin password: [admin]

[ant:input] REST API port (leave blank for no REST API server):
8440
[ant:input] Test REST API port (intended for running automated tests; leave blank for no server):
8441
[ant:input] Do you want support for multiple environments?  ([y], n)
y
[ant:input] Do you want resource files for a content database and set of users/roles created? ([y], n)
y
Updating build.gradle so that the Gradle properties plugin can be applied
Writing: build.gradle
Writing: gradle.properties
Writing: gradle-dev.properties
Writing: gradle-local.properties
Writing: gradle-qa.properties
Writing: gradle-prod.properties
Making directory: src/main/ml-config
Making directory: src/main/ml-modules
Writing project scaffolding files

BUILD SUCCESSFUL

Total time: 39.37 secs
Liesel:~/Documents/scratch/2018-11-13-TDE$ ls
build.gradle  gradle  gradlew  gradlew.bat

Liesel:~/Documents/scratch/2018-11-13-TDE$ cat build.gradle
plugins { 
  id "com.marklogic.ml-gradle" version "3.9.0"
}

```

**Comment by nizdobs** [comment]
Now I see the scaffolded files. This is the first time I used ml-gradle on a linux box and didn't realize that mlNewProject would put the scaffolded files in ~/.gradle/daemon/3.4.1. But if mlNewProject puts the scaffolded files there don't they get overwritten if I then issue mlNewProject from a different directory?

Is therre a way to tell ml-gradle that the scaffolding should be put in the present directory?

**Comment by rjrudin** [comment]
Are you using Java 11?

**Comment by nizdobs** [comment]
Java 8. Do I need to install Java 11?


```
Liesel:~/Documents/scratch/2018-11-13-TDE$ java -version
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
```

**Comment by rjrudin** [comment]
Hmm - try upgrading Gradle to the latest 4.x version. The reason the files are ending up there is because the file paths are being resolved relative to where the Gradle daemon is running. I've seen that happen with Java 11, but not with Java <11 and Gradle 4.x.

**Comment by nizdobs** [comment]
Looks like the upgrade to Gradle 4 did the trick.
