### ISSUE TITLE
Support substitution in mlDatabaseNamesAndReplicaCounts

### ISSUE THREAD

**Issue by dmcassel** [marklogic-community/ml-gradle#401]
I'd like to have a property like this:

    mlDatabaseNamesAndReplicaCounts=$myApp-staging,1,$myApp-content,1

Right now the property is not getting substituted, so the final value for `mlDatabaseNamesAndReplicaCounts` has the `$myApp` instead of the value.

**Comment by rjrudin** [comment]
ml-gradle is at the mercy of Gradle here, which as noted at https://stackoverflow.com/questions/23853044/does-gradle-support-properties-interpolation uses a plain Java properties file, and that doesn't support interpolation. But see the note in that link about how to (hopefully) achieve the same effect in build.gradle.

For your use case above, you can always manipulate the mlAppConfig object directly in an ext block in build.gradle. You'd be able to reference any property name so it'd still be dynamic.
