### ISSUE TITLE
Show example of a task class to reduce duplication across multiple MlcpTask tasks

### ISSUE THREAD

**Issue by rjrudin** [marklogic-community/ml-gradle#402]

**Comment by josvanroosmalen** [comment]
Please add that MLCP ingest, to create dynamically MLCP tasks (shared by @rjrudin within ML internally), which are 95% common, and where the last 5% (eg. input path, collections, etc) are derived from the properties.

**Comment by rjrudin** [comment]
https://github.com/marklogic-community/ml-gradle/wiki/Dynamically-creating-tasks
