### ISSUE TITLE
mlgradle not deploying files and folders starting with underscore

### ISSUE THREAD

**Issue by janmichaelyu** [marklogic-community/ml-gradle#412]
When migrating a project built on app-builder that uses templates for creating Excel documents, the code requires files with the following structure:

```

- <sheet name>
    - docProps
    - _rels
       - rels.xml
    - _word
       - _rels
         - document.xml.rels.xml
         - ...
    - [Content_Types].xml
```

The _rels folders are not uploaded into the modules database and when called from excel functions, an error is returned.

A workaround for this was to rename the folders with a prefix like "n_rels" and manually updating the code to remove that prefix before using it in excel functions.

**Comment by rjrudin** [comment]
I was not able to reproduce this - I created src/main/ml-modules/root/_test.xqy and src/main/ml-modules/root/_test/test.xqy, and both of those loaded fine - here's logging from mlWatch:

```
> Task :mlWatch
Initializing ExecutorService 
Writing 1 files
Writing: /_test.xqy
Shutting down ExecutorService

Wrote 1 documents to MarkLogic

> Task :mlWatch
Initializing ExecutorService 
Writing 1 files
Writing: /_test/test.xqy
Shutting down ExecutorService

Wrote 1 documents to MarkLogic
```

There's nothing in the code (in ml-javaclient-util) that ignores directories/files starting with "_" - the default behavior is only to ignore those starting with ".". 

Try creating the above directories/files as well to see if those work - something else must be going on here, as I don't see anything that would cause "_" directories/files to be ignored.

**Comment by janmichaelyu** [comment]
Thank you for confirming. Looks like from a different component than ml-gradle.
