### ISSUE TITLE
MLGradle/AppDeployer issue with App Server privileges

### ISSUE THREAD

**Issue by josvanroosmalen** [marklogic-community/ml-gradle#413]
Hi,

It seems that ML Gradle/AppDeployer does not properly handle privileges (ML 9.0-7, MLG, 3.10.0).

See the attached minimal working example project. This is a scaffolded project with as only change some ml-config changes: `security/privileges/priv.json` and `servers/testserver.json` which has as `"privilege" : "PrivilegeTest-ingest-execute"` the privilege the one described in priv.json.

If you do a `gradle mlDeploy` this will fail with `no such privilege: PrivilegeTest-ingest-execute` 

However the privilege is there (via ML Gradle). If I alter the testserver.json and remove the privilege, I can deploy it (`mlDeployServers`). Then I can add via the Admin UI that privilege I added via ML Gradle. 

[executePrivilegeNotWorking.zip](https://github.com/marklogic-community/ml-gradle/files/2682603/executePrivilegeNotWorking.zip)

**Comment by rjrudin** [comment]
It's not an ml-gradle issue - looks like the Manage API for a server wants the "action" of a privilege, not the "name". So use "http://test.com/something-execute" instead of "PrivilegeTest-ingest-execute".
