### ISSUE TITLE
ml-gradle doesn't work with Java 11 and the Gradle daemon running

### ISSUE THREAD

**Issue by dmcassel** [marklogic-community/ml-gradle#428]
Has ml-gradle been tested with Java 11 and Gradle 5? Those are the current versions. I tried using those versions with an existing project, but my modules don't get deployed. Wondering whether anyone else has used ml-gradle successfully under new versions.

**Comment by rjrudin** [comment]
It has not, and there's an issue with ml-app-deployer regarding this - https://github.com/marklogic-community/ml-app-deployer/issues/313 

If you have a chance, can you see if the same problem exists with Gradle 5 + Java 9 and Java 10, and add results to that ml-app-deployer ticket?

The short-term fix is to not run Gradle in daemon mode, but that's of course not a great fix.

**Comment by rjrudin** [comment]
Started looking into this - it's not specific to Gradle 5. Java 9 and 10 seem to not matter - seems like the common upgrade path is from Java 8 to 11. So I'm going to focus on supporting Java 11. 

@dmcassel One short term hack is to set mlConfigPath and mlModulePaths to absolute paths - e.g. mlConfigPath=/Users/janedoe/project/src/main/ml-config.

**Comment by rjrudin** [comment]
@dmcassel I have fixes for this in ml-app-deployer with a tiny but critical tweak in ml-gradle - will try to get 3.12.0 out soon to address Java 11 support. Still have the short term hack of setting mlConfigPaths, mlModulePaths, and mlSchemasPath to absolute paths.
