### ISSUE TITLE
Nicer mlUnitTest failure output

### ISSUE THREAD

**Issue by jonesyface** [marklogic-community/ml-gradle#430]
An enhancement request has been made on the marklogic-unit-test project (https://github.com/marklogic-community/marklogic-unit-test/issues/46) so that it easier to find which tests have failed and read the detail of the failure.

The latter issue can be dealt with in the marklogic-unit-test code but a solution to the former would be to change the directory structure of the test result output that is created when running the mlUnitTest task so that any failures are output into a specific failure directory. This would then ensure that any failing tests can be identified without trawling through all the test result output.

The code for this resides in the gradle/task/test/UnitTestTask.groovy file in this project so it is here that changes need to be made in conjunction with the requested changes to the format of the test results that need to be applied in the marklogic-unit-test project.

**Comment by rjrudin** [comment]
Thanks @jonesyface - I'm in the process of getting 3.12.0 ready, so I'm likely to look at this for 3.13.0. Let me know if it's urgent though.

**Comment by jonesyface** [comment]
The original enhancement request on marklogic-unit-test sounded like a nice-to-have to me so no major urgency, unless @damonfeldman (who originally raised it) says different.

**Comment by rjrudin** [comment]
As noted in the PR - I don't want to change the directory structure because that deviates from how "gradle test" works. The intent is for "gradle mlUnitTest" to write out results in the same fashion as "gradle test".
