### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by mthahir** [marklogic-community/ml-gradle#437]
Following the documentation, I have created a directory for triggers, but it failed and asked to put the exact trigger db name.  The documentation says: 
Version 3.7.0 of ml-gradle/ml-app-deployer adds support for deploying triggers to any triggers database, allowing for a setup like this:

databases
│       content-database.json
│       other-database.json
│       other-triggers-database.json
└───other-triggers-database
    └───triggers
            my-trigger.json
https://github.com/marklogic-community/ml-gradle/wiki/Project-layout
my directory structure is final-triggers-database.json . so, I created "final-triggers-database" folder and put my triggers there. However, in order to work, I have to change the folder name to "data-hub-final-TRIGGERS"

**Comment by mthahir** [comment]
![screenshot](https://user-images.githubusercontent.com/9898847/53738834-4a8b4580-3e5e-11e9-9bc0-4d90198de901.png)

**Comment by rjrudin** [comment]
Updated to make it absolutely clear - https://github.com/marklogic-community/ml-gradle/wiki/Project-layout
