### ISSUE TITLE
MlcpTask doesn't appear to support sequences with JavaScript transforms

### ISSUE THREAD

**Issue by ryanjdew** [marklogic-community/ml-gradle#440]
If I have a JavaScript mlcp transform that returns a sequence like the following:

`return Sequence.from([content]);` 

An mlcp command like the following works fine:

```
mlcp.sh import -input_file_path ./input/orders/orders.csv -input_file_type delimited_text -document_type json -transform_module /data-hub/5/transforms/mlcp-flow-transform.sjs -transform_param "options={},flow-name=LoadOrders" -host localhost -port 8010 -username admin -password ******** -output_collections step -output_uri_suffix .json -generate_uri true
```

Attempting to do the same with an MlcpTask renders the following error:

`xdmp.documentInsert(null, null, {collections:["Orders", "LoadOrders"], quality:"0"})`

**Comment by rjrudin** [comment]
I tried this out and couldn't reproduce it - I can't think of any reason why what the JS transform returns would have any bearing on how MLCP is invoked. 

These are the last two lines of my transform:

```
content.value = xdmp.unquote(xdmp.quote(newDoc));
return Sequence.from([content]);
```

I am wondering if the use of "options={}" is an issue in build.gradle, like perhaps the braces need to be escaped. Try removing that from the MlcpTask definition and see if it works.
