### ISSUE TITLE
ML Gradle Creates multiple forests for modules db when compared to triggers db

### ISSUE THREAD

**Issue by rahulkataram1** [marklogic-community/ml-gradle#442]
I have a 3 node cluster and have the below properties.
When I use the mlDeploy command, I see 3 content and modules forests where as only 1 triggers forest is created (as below). 
package-pqa-content-1
package-pqa-content-2
package-pqa-content-3
**package-pqa-modules-1
package-pqa-modules-2
package-pqa-modules-3**
package-pqa-triggers-1

I do not want 3 modules forest.
**I want only one forest for modules database just like triggers db.**

Below are the Properties:=
**mlContentForestsPerHost=1
mlDatabaseNamesAndReplicaCounts=package-pqa-content,1,package-pqa-modules,1,package-pqa-triggers,1**

**Comment by rjrudin** [comment]
What version of ml-gradle are you using? I just tried this on a 3-node cluster and got the expected behavior. 

My build.gradle file:

```
plugins {
	id "com.marklogic.ml-gradle" version "3.12.0"
}
```

My gradle.properties (the default value of mlAppName is "my-app"):

```
mlContentForestsPerHost=1
mlDatabaseNamesAndReplicaCounts=my-app-content,1,my-app-modules,1,my-app-triggers,1
```

**Comment by rahulkataram1** [comment]
hi @rjrudin ,
I am using the same version 3.12.0.
Do you mean the expected behaviour is generating 3 forests for content, 3 forests for modules and 1 forest for triggers databases?
I do not want 3 forests for modules database as it is having very less documents. I need only one forest and one replica for the modules database.

Can you please let me know how can i configure, so that modules db and forest db will have only one forest!
thanks
Rahul

**Comment by rjrudin** [comment]
Yes, I'm only getting one modules forest (on host 1) and one triggers forest (also on host 1). 

If this isn't happening for you, try setting mlDatabasesWithForestsOnOneHost as defined at https://github.com/marklogic-community/ml-gradle/wiki/Property-reference#database-and-forest-properties

**Comment by rahulkataram1** [comment]
Hi @rjrudin 
The below worked thanks!!!

mlContentForestsPerHost=1
mlDatabaseNamesAndReplicaCounts=package-qa-content,1,package-qa-modules,1,package-qa-triggers,1
**mlDatabasesWithForestsOnOneHost=package-qa-modules,package-qa-triggers**
