### ISSUE TITLE
Trigger permissions not applied

### ISSUE THREAD

**Issue by grtjn** [marklogic-community/ml-gradle#445]
I suspect an issue with the Management REST api, but posting it here for now, just in case it is linked to ml-gradle.

I have a trigger config like the following:

```
{
  "name": "config-modify",
  "description": "Config modify trigger",
  "event": {
    "data-event": {
      "collection-scope": {
        "uri": "config"
      },
      "document-content": {
        "update-kind": "modify"
      },
      "when": "pre-commit"
    }
  },
  "module": "/triggers/update-alerting.sjs",
  "module-db": "%%MODULES_DATABASE%%",
  "module-root": "/",
  "enabled": true,
  "recursive": false,
  "task-priority": "normal",
  "permission": [{
    "capability": "execute",
    "role-name": "%%mlAppName%%-role"
  }, {
    "capability": "read",
    "role-name": "%%mlAppName%%-role"
  }]
}
```

It deploys fine, and validation doesn't complain, but permissions don't get applied as expected. QC Explore shows permissions for these roles:

```
Role | R | U | I | E | N
-- | -- | -- | -- | -- | --
domain-management |   |   |   |   |  
security |   |   |   |   |  
trigger-management
```

At the least, I would have expected the app-role permissions to have been added.

**Comment by rjrudin** [comment]
Can you try posting that payload to the Manage API triggers endpoint? If you get the same behavior, please close this and file a bug against the Manage API.

**Comment by rjrudin** [comment]
I tried this via curl, and I got the same results - the permissions in the trigger are not applied to the trigger document (I modified the payload above to use "Modules" as the modules-database and I changed the roles to "manager-user"). 

```
curl -X POST --anyauth -u admin:admin --header "Content-type: application/json" -d "@src/main/ml-config/triggers/trigger1.json" "http://localhost:8002/manage/v2/databases/data-services-example-triggers/triggers"
```
