### ISSUE TITLE
Load data from standard data directory

### ISSUE THREAD

**Issue by rjrudin** [marklogic-community/ml-gradle#446]
As an ml-gradle user
I want a deployment to TITLE
So that data - e.g. reference or configuration data - that I always need loaded as part of a deployment can be loaded from a standard directory and thus I don't have to create an MLCP task

- src/main/ml-data would be the standard directory
- mlDataPaths would function just like mlConfigPaths and mlModulePaths
- The support documented at https://github.com/marklogic-community/ml-javaclient-util/wiki/Loading-files would be used for providing control over collections and permissions
- The URI would be the path of the file relative to the data directory (e.g. src/main/ml-data/my/doc.json would become /my/doc.json)
- An ml-data directory in an mlRestApi dependency would be added to mlDataPaths so that dependencies could contribute data as well

**Comment by rjrudin** [comment]
https://github.com/marklogic-community/ml-app-deployer/issues/339

**Comment by rjrudin** [comment]
Docs at https://github.com/marklogic-community/ml-gradle/wiki/Loading-data

**Comment by lifan0127** [comment]
Hi @rjrudin This is a very useful feature. Thank you! For specifying collections and permissions, how can I apply them to all files in subdirectories? Right now it seems they only affect files in the same directory but not in subdirectories.

https://github.com/marklogic-community/ml-javaclient-util/wiki/Loading-files#specifying-collections-and-permissions
