### ISSUE TITLE
Add explicit task to deploy search options

### ISSUE THREAD

**Issue by aajacobs** [marklogic-community/ml-gradle#452]
As a developer
I need to easily make changes to and deploy the search options for testing without introducing any other changes like mlLoadModules will

**Comment by rjrudin** [comment]
Is your expectation that this would work for the custom DHF commands for deploying search options too? If so, that would require a separate ticket in DHF. 

I think using mlModuleRegex is an easier approach here and doesn't require a new task. I'll work up a sample of this.

**Comment by rjrudin** [comment]
@aajacobs In an ml-gradle project, this can be achieved via:

    gradle -i mlLoadModules -PmlModulesRegex=.*options.*

But in a DHF project, mlModulesRegex is not honored by LoadHubModulesCommand nor by LoadUserModulesCommand (the latter for example will always load final-entity-options.xml and staging-entity-options.xml). 

My guess is you need this to work in a DHF project, which will require a DHF ticket - ideally making the above command work for DHF as well. I'm going to close this as ml-gradle already provides a solution.
