### ISSUE TITLE
Validating TDEs should exclude the current deployed version of the same template

### ISSUE THREAD

**Issue by luisjmart** [marklogic-community/ml-gradle#459]
When deploying an update to a TDE, the validation fails with "TDE-INCONSISTENTVIEW" because it compares to the deployed version. The template uri should be included on the $excludeTemplateURIs parameter of the tde:validate to ignore the previous version of the template.

**Comment by rjrudin** [comment]
This will be a fix in ml-javaclient-util. Thanks for pointing out that argument, I missed it when I first wrote the code for this.

**Comment by rjrudin** [comment]
Replacing this with https://github.com/marklogic-community/ml-javaclient-util/issues/113
