### ISSUE TITLE
ML Version 9 - Unable to deploy Modules

### ISSUE THREAD

**Issue by Basheer-Ahmed** [marklogic-community/ml-gradle#460]
We have recently migrated to ML 9. We are currently testing the ML 9 in one of our AWS DEV Server.
When I try to deploy the modules, I am receiving the below error. It fails while registering the REST Extensions.
XDMP-UNDFUN: (err:XPST0017) Undefined function entity :add-entity-prefix(); 
Location in my local : C:\Program Files\MarkLogic\Modules\MarkLogic\entity.xqy

I am unable to import the modules as these functions in the below location is set to private in ML 9.

**Comment by rjrudin** [comment]
ml-gradle is just the messenger here - the REST server you're trying to load modules into is rejecting your REST extension because it is trying to invoke a now-private function. You'll need to modify your extension to not reference a private function.
