### ISSUE TITLE
Deployment of triggers does not always work properly because of deployment operation ordering

### ISSUE THREAD

**Issue by anthony-gray** [marklogic-community/ml-gradle#463]
Deployment of triggers does not always work properly (especially when a trigger's scope includes documents in the modules database) because of deployment operation ordering. Below is a solution that I use that can be put in a build.gradle (it also includes always loading modules cleanly because of an issue with dirty modules). It should be noted that all trigger code/modules now goes in the src/main/ml-modules/root/root/lib/trigger folder, which can be changed to whatever folder you want.

import java.io.File
import java.nio.file.Path
import java.nio.file.Paths
import org.apache.commons.io.FileUtils
import com.marklogic.appdeployer.AppConfig
import com.marklogic.appdeployer.command.modules.DefaultModulesLoaderFactory
import com.marklogic.client.DatabaseClient
import com.marklogic.client.ext.modulesloader.ModulesFinder
import com.marklogic.client.ext.modulesloader.ModulesLoader
import com.marklogic.client.ext.modulesloader.impl.DefaultModulesFinder
import com.marklogic.gradle.task.MarkLogicTask

/* Implement LoadModulesTask instead of using AppConfig's/ModulesLoader's file filtering because
 * file filters cannot be changed more than once and module loader (instead of MlcpTask for example)
 * is needed for token replacement. Spawning tasks doesn't fix the filter change issue either. */
class LoadModulesTask extends MarkLogicTask {

  String modulesSubpath;

  @TaskAction
  void loadModules() {
    DatabaseClient client = null;
    try {
      client = newClient();
      AppConfig appConfig = getAppConfig();
      ModulesLoader loader = (new DefaultModulesLoaderFactory()).newModulesLoader(appConfig);
      ModulesFinder finder = new DefaultModulesFinder();
      for (String modulesPath : appConfig.getModulePaths()) {
        File tempModulesPath = new File("build/ml-modules-" + modulesPath.hashCode());
        Path currModulesSubpath = Paths.get(modulesPath, modulesSubpath).toAbsolutePath();
        try {
          FileUtils.copyDirectory(new File(modulesPath), tempModulesPath, {file ->
            Path filePath = file.toPath().toAbsolutePath();
            return filePath.startsWith(currModulesSubpath) || currModulesSubpath.startsWith(
              filePath);
          });
          loader.loadModules(tempModulesPath.getPath(), finder, client);
        } finally {
          FileUtils.deleteQuietly(tempModulesPath);
        }
      }
    } finally {
      if (client != null) {
        client.release();
      }
    }
  }
}
task mlLoadTriggersModules(type: LoadModulesTask) {
  modulesSubpath = "root/lib/trigger"
}
task mlLoadModulesExec(type: Exec) {
  commandLine Paths.get(gradle.startParameter.gradleHomeDir.absolutePath, "bin", "gradle" \
    + (isWindows ? ".bat" : "")).toFile().absolutePath, "mlLoadModules"
}
mlLoadTriggersModules.mustRunAfter mlClearTriggersDatabase
mlDeployTriggers.dependsOn mlClearTriggersDatabase, mlLoadTriggersModules
mlDeployTriggers.mustRunAfter mlClearModulesDatabase
mlLoadModules.dependsOn mlClearModulesDatabase, mlDeployTriggers
mlReloadModules.dependsOn mlDeployTriggers
mlPostDeploy.finalizedBy mlLoadModulesExec
mlDeleteModuleTimestampsFile.mustRunAfter mlClearTriggersDatabase
mlDeployApp.dependsOn mlClearTriggersDatabase, mlClearModulesDatabase, mlDeleteResourceTimestampsFile

**Comment by rjrudin** [comment]
@anthony-gray First, sorry for the delay on this. Can you provide an example of a trigger being deployed at an incorrect time? A trigger can depend on a modules database and on a role. The commands for deploying these resources have the following "sort order" values (where lower means earlier):

- Roles = 10
- Databases = 120
- Triggers = 700

Loading modules has a sort order of 400, but a trigger will still deploy correctly even if it refers to a non-existent module.

**Comment by rjrudin** [comment]
@anthony-gray  Please reopen this if you have an example that you can provide of the deployment ordering being incorrect.

**Comment by anthony-gray** [comment]
A trigger that triggers based on documents placed in the modules database (in our case configuration documents) must not only deploy "correctly" even if it refers to a non-existent module. It must actually trigger as soon as non-trigger code documents are placed in the modules database. This means that modules cannot be simply deployed before triggers and triggers cannot be simply deployed before modules. They are interdependent. Thus, you must deploy trigger modules, then deploy trigger configuration, and then deploy remaining modules.

I even provided you with the code that does this. This issue is still open. The solution I provided should at least help others if you don't want to fix this problem.

**Comment by rjrudin** [comment]
I think I get it now - you're proposing the following steps:

1. Deploy modules referenced by triggers
1. Deploy triggers
1. Deploy all other triggers

The changes would be made in ml-app-deployer, likely as a new command for step 1 and a change in sort order for the existing commands for steps 2 and 3. 

Backing up a bit though - what are your triggers doing that are triggered by documents being inserted into a modules database? I'm wondering if there's another approach for solving the problem addressed by the triggers.

**Comment by anthony-gray** [comment]
Our system is configuration driven. Configuration files are code artifacts placed in the modules (code) database. They are also automatically copied over to documents databases for efficient access by code running against these document databases and for access by end-users who won't necessarily be given access to the modules database. In addition, we have automatic lock-less svn type versioning (that I also implemented with a XQuery trigger) that applies for these configuration documents and some other regular non-module documents. The versioning is something in between temporal documents and the heavy weight library services document versioning. I should actually file this type of versioning as a generic MarkLogic feature request 😊.

My use of triggers is an ideal approach to meet our requirements. It’s just that ml-gradle/ ml-app-deployer isn’t doing the right thing. Irrespective of our approach it should always be the case that:

1.	Deploy modules referenced by triggers
2.	Deploy triggers
3.	Deploy remaining non-trigger modules

My solution to this handles some trickiness. So do not ignore a single statement in the solution. Every part of the solution is well thought out and well tested. There are many corner cases. Ordering is crucial.

**Comment by rjrudin** [comment]
What if after the modules are loaded, and after triggers are loaded, you just "touch" each module document that the triggers are interested in? Or just touch every document in the modules database to ensure all triggers are triggered. What would the downsides be to that?

The "Deploy modules referenced by triggers" step would need to ensure that any dependencies of those trigger modules are loaded as well - that could be dozens of other modules. I think it's common to store trigger modules in a path such as "/root/lib/triggers", but it's also common for those trigger modules to depend on library modules outside of that path. That creates a burden on a development team to ensure that with every deployment, the library modules depended on by trigger modules are guaranteed to be included in that first step.

**Comment by anthony-gray** [comment]
The problem with "touch" is that it necessarily occurs outside of the original write transaction, which is unacceptable for the atomicity, versioning, and transaction rollback on error that we require in our system. Besides, as I previously mentioned, **this deployment bug has nothing whatsoever to do with our use of triggers. The order of deployment mentioned should always occur in the way I described to be technically correct.**

**Comment by rjrudin** [comment]
I've opened a ticket in ml-app-deployer to address this, as the support would be provided there so that it's not dependent on Gradle - https://github.com/marklogic-community/ml-app-deployer/issues/369 .
