### ISSUE TITLE
mlNewProject fails with JDK 12

### ISSUE THREAD

**Issue by kcoleman-marklogic** [marklogic-community/ml-gradle#464]
I was trying to use ml-gradle 3.14 with gradle v5.4.1 and Java 12.0.1 on RHEL 7. The mlNewProject task coughed up the following failure:

>Execution failed for task ':mlNewProject'.
> Unable to write file at: /home/kcoleman/.gradle/daemon/5.4.1/./src/main/ml-config/databases/content-database.json; cause: ./src/main/ml-config/databases/content-database.json (No such file or directory)

Rob thought it was the same issue as #428 and as such should already have been fixed. Maybe Java 12 has found new and interesting ways to torture users. 

Stepping down to Java 9 made the problem go away. I'm fine with that, but wanted to let you know about the potential Java 12 wrinkle.

**Comment by rjrudin** [comment]
This may be a simple fix in ml-gradle - it's passing in "." as the project path, and I think that just needs to be resolved to a File first within Gradle so that it doesn't resolve against the daemon directory.

**Comment by rjrudin** [comment]
Just verified it works on Java 11 and fails on Java 12.
