### ISSUE TITLE
mlDeleteAllTasks should ignore the default MarkLogic tasks

### ISSUE THREAD

**Issue by dmcassel** [marklogic-community/ml-gradle#475]
When you run `mlDeleteAllTasks`, it (predictably) deletes all scheduled tasks. However, a standard MarkLogic installation includes at least one task that is for MarkLogic's internal purposes. I think it would be good to consider the `/MarkLogic/appservices/infostudio/tasks/fab-cleanup.xqy` task to be protected and not delete it when running `mlDeleteAllTasks`.

**Comment by dmcassel** [comment]
caveat: I don't remember what that task actually does, so I'm making an assumption that it's worth keeping around.

**Comment by rjrudin** [comment]
fab-cleanup.xqy isn't installed in a new ML 9.0-9.1 installation, so it must have been removed in some earlier version. I believe it was for deleting tickets specific to information studiou. I also wouldn't want to change the meaning of "delete all" - it should really mean "delete all".

**Comment by dmcassel** [comment]
If there were other system-installed task, I'd present an argument to leave them alone. Since it looks like there are not (anymore), no need.
