### ISSUE TITLE
Not using mlAppName

### ISSUE THREAD

**Issue by grtjn** [marklogic-community/ml-gradle#478]
I'd like to build out a template that does not use mlAppName, but something else, for instance mlGroveAppName. This would allow easier merging of multiple projects into one, for instance a DHF/DHS project in which you'd blend in Grove configs.

Using ml-gradle configs that use mlGroveAppName only, causes unexpected artifacts to get created, like my-app-content. If you specify `mlAppName=` to suppress the built-in one, it tries to upload ml-modules artifacts into `-modules`.

Is there a way around, or is it possible to improve the flexibility of this deployment framework?

**Comment by rjrudin** [comment]
When mlAppName is processed, the "setName" method is called on the instance of AppConfig that ml-gradle creates, which is stored under the Gradle property "mlAppConfig". So you can override that value in an "ext" block, which will run after Gradle evaluates every plugin but before it runs any task:

```
ext {
  mlAppConfig.name = mlGroveAppName
}
```

I would probably just choose "groveAppName" to make it clear that it's not an ml-gradle property but rather a Grove-specific property. 

I did a quick test of that on a simple project that just deploys a REST server, and it worked as expected - the REST server, content database, and modules database were all named after the value I passed in for "mlGroveAppName".

**Comment by grtjn** [comment]
Awesome, thnx!
