### ISSUE TITLE
undeploying a project without content-database

### ISSUE THREAD

**Issue by grtjn** [marklogic-community/ml-gradle#479]
We composed a set of instructions that allow having DHF and Grove work along side each other. It basically comes down to removing configs for content, schemas, and triggers, and pointing the other configs to those. That works well when deploying, all hooks into dhf-final db.

However, when you undeploy the Grove side of the project, you'd want it to only undeploy what you configured. Unfortunately, it was reported that it wipes the forests of final as well, and only stops wiping stuff it shouldn't when it notices that the content-db is used by dhf as well.

See also: https://github.com/marklogic-community/grove/issues/27

What can we do/can be done to improve this situation?

**Comment by rjrudin** [comment]
Try upgrading to ml-gradle 3.14.0 (either by upgrading DHF to 5.0.1, or by following these instructions - https://github.com/marklogic-community/ml-gradle/wiki/DHF-Integration ). 

I am fairly confident that 3.14.0 will avoid this problem, as there's no longer a command specific to a default content database. That is likely the command that was causing the problem.

I haven't tried to reproduce this, but if you still get the same problem with 3.14.0 or higher, please reopen this (check the info-level logging too to make sure that DeployContentDatabasesCommand isn't being executed).

**Comment by grtjn** [comment]
Thnx, will run tests with this knowledge..
