### ISSUE TITLE
add timestamp to mlWatch output

### ISSUE THREAD

**Issue by lonesloane** [marklogic-community/ml-gradle#480]
Sometimes, when mlWatch -i has been running for a while, it can be hard to tell when the last "file upload" occurred. Would be nice to have some "HH-MM-SS" indication alongside the current

Writing 1 files
Writing: /test/suites/access-request-security/access-request-security.xqy
Writing 1 documents to MarkLogic; port: 8000; database: xxx-Modules

**Comment by rjrudin** [comment]
Those messages are written at the "info" level by ml-gradle, but it's Gradle that controls the format of each log message. Unfortunately, there aren't many good docs on configuring Gradle's logging (the Gradle docs only cover setting the level, but not the format of each message). 

I did some searching, and this seems like it may help - https://stackoverflow.com/questions/26635671/gradle-logging-output-levels . You may need to check out the docs for some of Gradle's logging classes to figure out how to change how Gradle logs messages.

**Comment by lonesloane** [comment]
Thanks, will take a look :-)
