### ISSUE TITLE
mlTestRestPort not triggering creation of test db/app server with DHF5

### ISSUE THREAD

**Issue by dmcassel** [marklogic-community/ml-gradle#481]
My understanding is that if you specify the `mlTestRestPort` property, then a test content database and a test app server will be inferred and built with the same configuration as the main content database and app server. I have a DHF5 project where I've defined that property, but I'm not getting the test resources. Does this still work with DHF5?

**Comment by dmcassel** [comment]
Should have mentioned: 

- MarkLogic 9.0-9.1
- I've tried with marklogic-unit-test version 1.0.beta and with 0.12.0.

**Comment by rjrudin** [comment]
Neither mlRestPort nor mlTestRestPort are supported in DHF.

**Comment by dmcassel** [comment]
Ah, that explains it. So there is no way to automatically trigger the creation of the test database and app server. Bummer. Is there a way to tell ml-Gradle to ignore a database config file based on the environment?

**Comment by rjrudin** [comment]
Yes, you can use mlResourceFilenamesToIgnore

**Comment by dmcassel** [comment]
@rjrudin thanks Rob. So if I want to use marklogic-unit-test with DHF, I'm thinking I should define a test app server and content database manually (creating .json files for them), then use `mlResourceFilenamesToIgnore` to prevent them from getting deployed to prod. That means I'll have to be careful to keep `foo-content.json` and `foo-test-content` in sync, but otherwise should be fine. Is that correct?

**Comment by rjrudin** [comment]
This shows how to automate the setup of test servers/databases on a DHF 4.1 project - https://gist.github.com/rjrudin/df0ff09f5bff67833048e67f1ebaa5d6 . I haven't tried that on a DHF 5 project yet though.

**Comment by dmcassel** [comment]
Sweet, thanks Rob!
