### ISSUE TITLE
mlUnitTest -PunitTestResultPath does not work

### ISSUE THREAD

**Issue by lonesloane** [marklogic-community/ml-gradle#483]
Despite providing a different path, e.g. -PunitTestResultPath="C:\Temp\test-results", the test results are still created in the default folder, i.e. build/test-results/marklogic-unit-test

**Comment by rjrudin** [comment]
Yuck - this is a documentation issue, the task doesn't support that property. I'll fix that in ml-gradle. 

When https://github.com/marklogic-community/marklogic-unit-test/issues/82 is addressed in marklogic-unit-test, this property (or a similarly named one) will then be supported properly.

**Comment by rjrudin** [comment]
Hmm - I mis-spoke, looking into this further.

**Comment by rjrudin** [comment]
A docs issue - the property is "unitTestResultsPath". The task should work fine with that. I'm making a fix to correct the typo in the task description.
