### ISSUE TITLE
after giving custom value for forest even then I'm getting default forest. mlgradle version 2.7.3

### ISSUE THREAD

**Issue by cjtejasai** [marklogic-community/ml-gradle#484]
![image](https://user-images.githubusercontent.com/37042989/60586607-0a0deb00-9db0-11e9-96cb-ece981e3404f.png)

**Comment by rjrudin** [comment]
I don't know what "giving custom value for forest" means. Which property or set of properties are you setting? Or are you trying to define custom forests as described at https://github.com/marklogic-community/ml-gradle/wiki/Creating-forests#payload-driven ?

**Comment by rjrudin** [comment]
Closing this due to lack of response. If you can provide more detail as requested above, please reopen.
