### ISSUE TITLE
Scheduled Tasks do not use mlGroupName parameter

### ISSUE THREAD

**Issue by gku11ava** [marklogic-community/ml-gradle#487]
Scheduled tasks are being deployed to the Default group even if the task host is set to a server that belongs to a different group and the mlGroupName property is being ignored.

1. Tried specifying mlGroupName in gradle.properties
2. Tried specifying mlGroupName at the command-line (-PmlGroupName=myGroup)
3. Tried setting mlAppConfig.setGroupName in a build.gradle ext block.

ml-gradle version: 3.15.0
In all 3 cases, the scheduled task(s) were deployed to the Default group, not the group I specified.

**Comment by cskeefer** [comment]
I believe ml-gradle supports this by putting the task definition in a folder named after the group you are targeting. So to add a task in the e-nodes group you would do the following:

`ml-config/tasks/e-nodes/some-task.json`

Of course if you needed something more dynamic in nature the above wouldn't work.

**Comment by rjrudin** [comment]
@cskeefer is correct, and unfortunately I don't think it was documented anywhere (except for in the automated tests in ml-app-deployer, not that that's a place where someone would be expected to look).

I added the following docs to capture this - sorry for the gap:

https://github.com/marklogic-community/ml-app-deployer/wiki/Scheduled-Tasks#assigning-scheduled-tasks-to-groups
