### ISSUE TITLE
mlDeploy Fails NO SUCH DATABASE ERROR

### ISSUE THREAD

**Issue by millerbill3** [marklogic-community/ml-gradle#488]
The attached configuration fails to deploy. "MANAGE-INVALIDPAYLOAD: (err:FOER0000) Payload has errors in structure, content-type or values. Invalid payload: no such database: test-triggers" error is the result.
After numerous attempts, it seems that if the configuration for the Modules database and its associated Forests configuration is removed from the project/deployment it works successfully. 
[Archive.zip](https://github.com/marklogic-community/ml-gradle/files/3382158/Archive.zip)

**Comment by rjrudin** [comment]
ml-app-deployer sorts databases based on dependencies before deploying them. The sorting is based on the triggers-database, schema-database, and security-database properties. 

All 4 database files have schema-database and security-database set to the same things, and the sorting is not handling that correctly. I'm going to close this and open a ticket in ml-app-deployer to handle that situation correctly. 

In the meantime, you can fix the problem by removing schema-database and security-database from each database file, as they'll default to Schemas and Security.

**Comment by rjrudin** [comment]
Wrote up https://github.com/marklogic-community/ml-app-deployer/issues/368
