### ISSUE TITLE
Does ml-gradle support application-specific security databases? 

### ISSUE THREAD

**Issue by dmcassel** [marklogic-community/ml-gradle#490]
In a situation where multiple applications will be deployed to a single MarkLogic instance, there may be advantages to separating the security management. Does ml-gradle support this? (It doesn't appear to; wanted to see whether I'm missing something.)

**Comment by rjrudin** [comment]
I think this is less about ml-gradle and more about how you'd do this with the Manage API.

The Manage server has a content database of App-Services, which points to the Security database. In theory, you can setup a clone of the Manage server on a different port but point it to a content database with a different database for security. 

I don't know if that will actually work though - e.g. if you deploy a new user, does it get sent to that alternate security database or just to Security. If it does, then each application could have its own Manage server that it talks to. If it doesn't work, then that likely means the Manage API is fixed to writing to the Security database, and there's nothing ml-gradle can do about that.
