### ISSUE TITLE
mlDatabaseGroups work with triggers, modules and schemas

### ISSUE THREAD

**Issue by dunntrevor** [marklogic-community/ml-gradle#491]
Hi.  I am trying to use the property mlDatabaseGroups.  It  works awesome for the content database.  However when I add the modules/triggers/schemas databases to it so their forests will also be created on our d-nodes.  It does not seem to work.  The forests are always created on the enode defined by mlHost for those three databases.

mlDatabaseGroups=database-content,D_Nodes,database-triggers,D_Nodes,database-schemas,D_Nodes,database-modules,D_Nodes

**Comment by rjrudin** [comment]
Thanks @dunntrevor , I'm trying to reproduce this right now.

**Comment by rjrudin** [comment]
What version of ml-gradle are you using?

I wasn't able to reproduce this with a local 3-node cluster using ml-gradle 3.15.2. I created a second group called "Other" and added the 3rd host to it, so the other two hosts are still in "Default". 

I then have the following in my gradle.properties file:

```
mlForestsPerHost=my-content,1
mlNoRestServer=true
mlDatabaseGroups=my-content,Default,my-other-stuff,Other
```

I then have 4 database files in src/main/ml-config/databases - my-content, my-modules, my-triggers, and my-other-stuff. None of the files have any properties besides database-name.

When I run "gradle -i mlDeploy", I see the following submitted to create the databases and forests:

```
Submitting configuration: {
  "config" : [ {
    "database" : [ {
      "database-name" : "my-triggers"
    }, {
      "database-name" : "my-other-stuff"
    }, {
      "database-name" : "my-modules"
    }, {
      "database-name" : "my-content"
    } ]
  }, {
    "forest" : [ {
      "forest-name" : "my-triggers-1",
      "host" : "ml1.local",
      "database" : "my-triggers"
    }, {
      "forest-name" : "my-triggers-2",
      "host" : "ml2.local",
      "database" : "my-triggers"
    }, {
      "forest-name" : "my-triggers-3",
      "host" : "ml3.local",
      "database" : "my-triggers"
    }, {
      "forest-name" : "my-other-stuff-1",
      "host" : "ml3.local",
      "database" : "my-other-stuff"
    }, {
      "forest-name" : "my-modules-1",
      "host" : "ml1.local",
      "database" : "my-modules"
    }, {
      "forest-name" : "my-modules-2",
      "host" : "ml2.local",
      "database" : "my-modules"
    }, {
      "forest-name" : "my-modules-3",
      "host" : "ml3.local",
      "database" : "my-modules"
    }, {
      "forest-name" : "my-content-1",
      "host" : "ml1.local",
      "database" : "my-content"
    }, {
      "forest-name" : "my-content-2",
      "host" : "ml2.local",
      "database" : "my-content"
    } ]
  } ]
}
```

That is as expected - my-content is only on the two Default hosts; my-triggers and my-modules have forests on all 3 hosts; and my-other-stuff only has a forest on the Other host.

**Comment by dunntrevor** [comment]
Thanks @rjrudin  for looking into this.  I was using 3.11 but I have upgraded to 3.15.2.
Using your example I can replicate the behaviour.
First thing I did was set up a project same as yours.  I got the exact same output as you.
I had 2 nodes in default and one node in other group.  I used the node in other group as the mlHost property.  So my gradle.properties looked like this

````
#Other Host
mlHost=XX.XX.XXX.132

mlUsername=admin
mlPassword=admin

mlForestsPerHost=my-content,1
mlNoRestServer=true
mlDatabaseGroups=my-content,Default,my-other-stuff,other
````

Then I  added my-triggers,other to the mlDatabaseGroups to give

`mlDatabaseGroups=my-content,Default,my-other-stuff,other,my-triggers,Default`

That also worked as expected.  You can see the output, the triggers were created on the two  hosts for default only.
````
 "database" : [ {
      "database-name" : "my-triggers"
    }, {
      "database-name" : "my-other-stuff"
    }, {
      "database-name" : "my-modules"
    }, {
      "database-name" : "my-content"
    } ]
  }, {
    "forest" : [ {
      "forest-name" : "my-triggers-1",
      "host" : "ip-xx-xx-xxx-151.us-west-2.compute.internal",
      "database" : "my-triggers"
    }, {
      "forest-name" : "my-triggers-2",
      "host" : "ip-xx-xx-xxx-156.us-west-2.compute.internal",
      "database" : "my-triggers"
    }, {
      "forest-name" : "my-other-stuff-1",
      "host" : "ip-xx-xx-xxx-132.us-west-2.compute.internal",
      "database" : "my-other-stuff"
    }, {
      "forest-name" : "my-modules-1",
      "host" : "ip-10-xx-xxx-132.us-west-2.compute.internal",
      "database" : "my-modules"
    }, {
      "forest-name" : "my-modules-2",
      "host" : "ip-xx-xx-xxx-151.us-west-2.compute.internal",
      "database" : "my-modules"
    }, {
      "forest-name" : "my-modules-3",
      "host" : "ip-xx-xx-xxx-156.us-west-2.compute.internal",
      "database" : "my-modules"
    }, {
      "forest-name" : "my-content-1",
      "host" : "ip-xx-xx-xxx-151.us-west-2.compute.internal",
      "database" : "my-content"
    }, {
      "forest-name" : "my-content-2",
      "host" : "ip-xx-xx-xxx-156.us-west-2.compute.internal",
      "database" : "my-content"
    }
````
Now is where the interesting thing happens.  If I add the property mlHost=my to gradle properties, changing nothing else, the my-triggers are no longer created on the two hosts in default group as expected and shown in previous example, it is now created only once  on the one host in other group  which is specified as the mlHost property.

Here is  my gradle.properties and the output.  You can see that the my-triggers is being ignored in the mlDatabaseGroups property and  is only created on the one host specified in the mlHost property.

````
#Other node
mlHost=xx.xx.xxx.132

mlAppName=my

mlUsername=admin
mlPassword=admin

mlForestsPerHost=my-content,1
mlNoRestServer=true
mlDatabaseGroups=my-content,Default,my-other-stuff,other,my-triggers,Default

"config" : [ {
    "database" : [ {
      "database-name" : "my-triggers"
    }, {
      "database-name" : "my-other-stuff"
    }, {
      "database-name" : "my-modules"
    }, {
      "database-name" : "my-content"
    } ]
  }, {
    "forest" : [ {
      "forest-name" : "my-triggers-1",
      "host" : "ip-xx-xx-xxx-132.us-west-2.compute.internal",
      "database" : "my-triggers"
    }, {
      "forest-name" : "my-other-stuff-1",
      "host" : "ip-xx-xx-xxx-132.us-west-2.compute.internal",
      "database" : "my-other-stuff"
    }, {
      "forest-name" : "my-modules-1",
      "host" : "ip-xx-xx-xxx-132.us-west-2.compute.internal",
      "database" : "my-modules"
    }, {
      "forest-name" : "my-modules-2",
      "host" : "ip-xx-xx-xxx-151.us-west-2.compute.internal",
      "database" : "my-modules"
    }, {
      "forest-name" : "my-modules-3",
      "host" : "ip-xx-xx-xxx-156.us-west-2.compute.internal",
      "database" : "my-modules"
    }, {
      "forest-name" : "my-content-1",
      "host" : "ip-xx-xx-xxx-151.us-west-2.compute.internal",
      "database" : "my-content"
    }, {
      "forest-name" : "my-content-2",
      "host" : "ip-xx-xx-xxx-156.us-west-2.compute.internal",
      "database" : "my-content"
    } ]
  } ]
}
````

**Comment by rjrudin** [comment]
What's happening here is when mlAppName is set, that results in mlAppConfig.triggersDatabaseName having a value of "my-triggers". When mlAppConfig is instantiated with the value of mlAppName, it then has a little check in it to say that if triggersDatabaseName (and schemasDatabaseName) has a value, it should be added to the set of database names that should only have forests on one host - the thought being that for what are typically very small databases like the triggers and schema databases, only one forest on one host is needed. 

If you run mlDeploy with "-i" for info logging, you'll see a message noting this:

```
Only creating forests on the first host: ml1.local
Checking for existence of resource: my-triggers
```

I actually had forgotten about this behavior. It pre-dates the creation of the properties that allow for this to be configured explicitly. I'm going to add a ticket to ml-app-deployer to deprecate this feature so that it can be removed in ml-app-deployer 4.0. 

Going to close this, as I think it's all been settled.

**Comment by rjrudin** [comment]
https://github.com/marklogic-community/ml-app-deployer/issues/377

**Comment by rjrudin** [comment]
Just for reference, this feature was actually added to cover some other functionality that was being deprecated - https://github.com/marklogic-community/ml-app-deployer/issues/328 . 

But I think using mlDatabasesWithForestsOnOneHost is the better option.
