### ISSUE TITLE
Expand tokens during module (re-)load?

### ISSUE THREAD

**Issue by mnuman** [marklogic-community/ml-gradle#494]
Hi,

I am trying to have token substitution performed on (some) XQuery files during (re-)deployment, using the mlLoadModules and mlReloadModules tasks. We're currently using Gradle 4.8 with ml-gradle 3.6.3.
However, I can't get the token substitution to work at all, although I can see that the AppConfig object in task has all tokens present in its customTokens property ...

Any pointers as to how to achieve the token substitution during deployment on the XQuery files?
(The purpose of this is to have some environment specific configuration inside the modules database in order to store information like endpoints and client_id for an external OAuth introspection service).

Kind regards,
Milco

**Comment by dmcassel** [comment]
If you could provide a simple example of what you're trying, that might make it easier for someone to spot a problem.

**Comment by rjrudin** [comment]
And check https://github.com/marklogic-community/ml-gradle/wiki/How-modules-are-loaded#replacing-tokens-in-modules just to make sure it doesn't address whatever the issue may be.

**Comment by mnuman** [comment]
Hi @dmcassel ,
You're right ... I have a simple XQuery module, currently only consisting of a variable declaration; it's value is to be taken from a property that is present in the gradle.properties file.
I have verified using the mlPrintTokens task that the token %%mlHost%% is actually present with the expected value. The mlHost token is also listed in the %%filterTokens%% list.

### gradle.properties
mlHost=localhost

### XQuery module - plugins/config/test-config.xqy
xquery version "1.0-ml";
module namespace tc = "http://my.company.com/config/test-config";
(: test to verify whether tokens are expanded in XQuery resources  :)
declare variable $_SOME_VARIABLE as xs:string := "%%mlHost%%";

Now, after running the mlReloadModules the XQuery has been deployed to the modules database at /config/test.config.xqy, but the "%%mlHost%%" has **not** been expanded into "localhost" as I had expected.

**Comment by rjrudin** [comment]
So the token is replaced correctly during mlDeploy? But not when running mlLoadModules or mlReloadModules? What about mlWatch?

Can you share what's in your gradle.properties file, sans passwords and anything similar?

**Comment by mnuman** [comment]
Hi @rjrudin ,

Nothing special in our gradle properties file - see attachment
[gradle_properties.txt](https://github.com/marklogic-community/ml-gradle/files/3513442/gradle_properties.txt)

And as to mlDeploy - in the local dev env we usually deploy using the ReloadModules task, tried running mlDeploy but this currently fails.

As I understand from ml-gradle documentation (https://github.com/marklogic-community/ml-gradle/wiki/Configuring-resources), all tokens are made available for token replacement as we're running 3.6.3.

In both my XQuery and JSON files (plugin/config), I have used replacement tokens:

-- Json:
{
  "environment" : "%%DATABASE%%",
  "built-from"  : "%%buildFile%%",
  "finalprop"   : "%%mlJobPort%%"
}

-- XQuery module:
xquery version "1.0-ml";
module namespace tc = "http://my.company.com/config/test-config";
(: test to verify whether tokens are expanded in XQuery resources :)
declare variable $_SOME_VARIABLE as xs:string := "%%mlHost%%";

All replacement tokens are known (verified by running gradle in debug mode), but no token replacements occur in the files that are uploaded to the database.

**Comment by mnuman** [comment]
Hi,
We seem to have found a way around this, albeit by defining a custom task copying the required resource and applying an Apache Ant ReplaceToken filter in the process.
Should somebody happen to know a cleaner way using standard ml-gradle tasks and configuration, we'd love to hear it.
//Milco

**Comment by rjrudin** [comment]
Are you able to try the latest version of ml-gradle to see if the issue happens with that as well?
