### ISSUE TITLE
Can't set mlModulePermissions based on app name

### ISSUE THREAD

**Issue by dmcassel** [marklogic-community/ml-gradle#495]
I have an application with multiple instances ("APP-DEV", "APP-UAT") deployed to the same MarkLogic instance. In order to keep them separate in the Security database, role names are prefaced with "%%mlAppName%%", so for instance I have an "APP-DEV-USER". 

I want to use the "mlModulePermissions" property to set up permissions. It looks like I can't do that directly in gradle.properties, as (according to a reference I found), substitutions don't work there. Instead, I added this to my "build.gradle": 

```
ext {
  mlModulePermissions = "$mlAppName-USER,read,$mlAppName-USER,update,$mlAppName-USER,execute".toString()
}
```

When I run "./gradlew properties", the mlModulePermissions property is there and has the correct value. But after running "./gradlew mlLoadModules", the modules have the default permissions. The value of "mlModulePermissions" is respected if I hard-code it in gradle.properties. 

I don't know whether this is relevant, but I noticed that when I define the property in build.properties, it shows up in filterTokens, but it does not if I define it in build.gradle. (Not sure what the purpose of filterTokens is or how to change it.) 

Should I be able to define mlModulePermissions in build.gradle and have the value used?

**Comment by rjrudin** [comment]
The Gradle property mlModulePermissions is just a shortcut for all AppConfig.setModulePermissions. When the "ext" block is evaluated, the ml-gradle plugin has already been evaluated, and it's already applied all of the properties. Thus, changing the value of a property won't have any impact. 

Instead, try doing this:

```
ext {
  mlAppConfig.moduelPermissions = "..."
}
```

**Comment by dmcassel** [comment]
Perfect, thanks Rob!
