### ISSUE TITLE
Wrong modules loaded due to old unzipped mlBundle code in the build directory

### ISSUE THREAD

**Issue by damonfeldman** [marklogic-community/ml-gradle#497]
mlReloadModules and mlRedeploy does not appear to clear out downloaded code from the mlRestAPI or mlBundle operations when the bundles are removed from the gradle dependencies. This occurred particularly when moving from the separately-packaged version of Smart Mastering Toolkit to DHF 5.x which includes SMT in the hub core code.

Suggested that redeploy and perhaps reloadmodules would clear these out of the build directory and re-extract.

**Comment by rjrudin** [comment]
I'm not clear on the problem - the directory build/mlRestApi/smart-mastering-code may still exist, but nothing will be loaded from it unless there's an mlRestApi or mlBundle dependency for smart-mastering-code. If that dependency is removed, then the build/mlRestApi/smart-mastering-code path won't be added to the set of module paths that ml-gradle loads from. 

mlDeploy/mlRedeploy/mlReloadModules already delete each directory corresponding to an mlRestApi/mlBundle dependency and then extracts each dependency (this is done via mlPrepareBundles, which each of those tasks depends on). 

I'm reluctant to have ml-gradle delete other directories under build/mlRestApi or build/mlBundle. For example, a user may modify some of a bundle's source files, but then remove or comment out the dependency in build.gradle. The user wouldn't want ml-gradle to then delete that directory.

But I'm not clear on the problem either - is this just for cleanliness, or is some error occurring as a result?

**Comment by rjrudin** [comment]
Note that the wrong modules would be loaded if a developer overrides mlModulePaths to include build/mlRestApi/smart-mastering-code. But the fix for that would be for the developer to remove that path from mlModulePaths.

**Comment by rjrudin** [comment]
@damonfeldman My guess is that mlModulePaths was configured to include the obsolete path. If you can show that ml-gradle was loading modules from a path that was neither in mlModulePaths nor associated with an mlBundle, please reopen this with steps to reproduce.
