### ISSUE TITLE
Add -P option to deploy specific database / server

### ISSUE THREAD

**Issue by ewillia1983** [marklogic-community/ml-gradle#503]
I'm thinking of something along the lines of mlDeployDatabase -Pdatabase=my_database.  I've got over 60 databases / 1500 servers in my config directories, so running all of them for every change is pretty time consuming.

**Comment by rjrudin** [comment]
Try using -PmlResourceFilenamesToIncludeRegex , which is intended to be a more general solution for this sort of problem. So e.g.

    gradle -i mlDeployDatabases -PmlResourceFilenamesToIncludeRegex=my_database.*

**Comment by ewillia1983** [comment]
That does the trick.  Many thanks!
