### ISSUE TITLE
%%PORT%% Not being injected

### ISSUE THREAD

**Issue by prestonmcgowan** [marklogic-community/ml-gradle#506]
I was deploying the data-services-example and noticed the server.json file has the hard coded 8099 port. I updated the code to `"port": %%PORT%%` and gradle threw an invalid JSON message. I then tried  to add quotes `"port": "%%PORT%%"` and gradle threw a bad type from MarkLogic.
I noticed the %%PORT%% was not being injected.

```
  "server-name" : "data-services-example",
  "group-name" : "Default",
  "server-type" : "http",
  "enabled" : true,
  "root" : "/",
  "port" : "%PORT%%",
  "authentication" : "digest",
  "content-database" : "data-services-example-content",
  "modules-database" : "data-services-example-modules"
}
```

Documentation: https://github.com/marklogic-community/ml-gradle/wiki/Configuring-resources

**Comment by rjrudin** [comment]
Do you have a Gradle property named "PORT"? Normally, mlRestPort would be used, in which case you'd want %%mlRestPort%%.

**Comment by prestonmcgowan** [comment]
I do not have anything hamed PORT. I was going off the documentation above.
%%PORT%% - typically used for a REST API server port.
None of the other items like MODULES_DATABASE are called out directly in my property files either, but they are utilized.

**Comment by rjrudin** [comment]
Hmm, that page should be more explicit about what properties are mapped to those tokens. mlRestPort is mapped to PORT, so set mlRestPort.

**Comment by prestonmcgowan** [comment]
I had that set, it still didn't work for me :-(

**Comment by rjrudin** [comment]
I updated the docs at https://github.com/marklogic-community/ml-gradle/wiki/Configuring-resources to hopefully better explain what these tokens are for - "%%PORT%%" is only used in the context of creating a REST server (it has either the value of mlRestPort or mlTestRestPort).

The better approach is to just define a Gradle property and reference that in the payload.

**Comment by rjrudin** [comment]
Closing this, please reopen if you think there's anything further to do.
