### ISSUE TITLE
mlNewProject and Data Services

### ISSUE THREAD

**Issue by prestonmcgowan** [marklogic-community/ml-gradle#508]
I wanted to create a new gradle project with Data Services.
I created the following build.gradle.
```
plugins {
  id "net.saliman.properties" version "1.5.1"
  id "com.marklogic.ml-gradle" version "3.16.1"
  id "com.marklogic.ml-development-tools" version "4.1.1"
}
```

After running `mlNewProject` the ml-development-tools was removed from my plugins and my original file was copied to backup-build.gradle.

I would have expected the ml-development-tools to be in the final build.gradle.

I am easily able to move the plugin back into the build.gradle to work around this issue.

**Comment by rjrudin** [comment]
I don't think mlNewProject is going to get into the business of trying to parse the existing build.gradle and retain certain things. So the workaround is the way to go.

**Comment by prestonmcgowan** [comment]
👍
