### ISSUE TITLE
MarkLogic 10

### ISSUE THREAD

**Issue by prestonmcgowan** [marklogic-community/ml-gradle#509]
Shouldn't the README be updated to include MarkLogic 10?

> Start using ml-gradle
> ml-gradle depends on at least Java 8 and MarkLogic 8 or 9, so if you have those installed, you're just a couple minutes away from using ml-gradle to start a new project and deploy an application from it.

**Comment by rjrudin** [comment]
Good catch - updated - https://github.com/marklogic-community/ml-gradle/blob/master/README.md
