### ISSUE TITLE
mlModulesPermissions default/suggestion in gradle.properties

### ISSUE THREAD

**Issue by prestonmcgowan** [marklogic-community/ml-gradle#510]
Please put the mlModulesPermissions default/suggested values the generated gradle.properties, even if they are just commented out. Having the sample for mlModulesPermissions makes it easier to see how to apply these permissions or at least serves are a starting point.

**Comment by rjrudin** [comment]
What's the "when" for this request? When running mlNewProject? That's the only time ml-gradle ever touches the gradle.properties file (whereas DHF has its hubInit task).

**Comment by prestonmcgowan** [comment]
mlNewProject

**Comment by rjrudin** [comment]
I modified the gradle.properties file to have a link to https://github.com/marklogic-community/ml-gradle/wiki/Property-reference , and I updated that page so that mlModulePermissions has the correct default value, which serves as a good starting point.
