### ISSUE TITLE
mlGenerateUnitTestSuite sjs support

### ISSUE THREAD

**Issue by prestonmcgowan** [marklogic-community/ml-gradle#511]
Allow the mlGenerateUnitTestSuite to take in an argument to create sjs or xqy unit test samples. The third sample could be a hybrid of sjs and xqy, but I am not sure of a good way to generate that.

Impacted file: ml-gradle/src/main/groovy/com/marklogic/gradle/task/test/GenerateUnitTestSuiteTask.groovy

Possible sample output from modifying the xqy sample files.

[sjsSampleTestSuite.zip](https://github.com/marklogic-community/ml-gradle/files/3709126/sjsSampleTestSuite.zip)

**Comment by grtjn** [comment]
It would make a lot of sense if this task code would be moved to the ml-unit-test repo, hence this ticket should move there too?

**Comment by dmcassel** [comment]
> It would make a lot of sense if this task code would be moved to the ml-unit-test repo, hence this ticket should move there too?

I don't think marklogic-unit-test currently exports any tasks, so there would be no place for the code to land (currently).

**Comment by grtjn** [comment]
Not something that can't be fixed.. :)

Can't imagine it to be very hard. Wouldn't it be matter of somehow adding it to the ml-unit-test-client? Then again, not really an expert on exposing gradle tasks in jars.. :)

**Comment by dmcassel** [comment]
> Not something that can't be fixed.. :)
> 
> Can't imagine it to be very hard. Wouldn't it be matter of somehow adding it to the ml-unit-test-client? Then again, not really an expert on exposing gradle tasks in jars.. :)

Sounds like a question for @rjrudin

**Comment by dmcassel** [comment]
@rjrudin fyi I'm preparing a PR for this
