### ISSUE TITLE
Add JavaExec example to data-services project

### ISSUE THREAD

**Issue by rjrudin** [marklogic-community/ml-gradle#513]
And open bug for ML docs for DS to point to this project as a working example

**Comment by jmakeig** [comment]
Who is the audience here? If we’re talking Java and Gradle already, that sounds like a Developer or an Architect. I would expect them to be able to draw a straight line from tests to applications on their own or with architectural guidance. If we’re talking to a Data Engineer/SME, we shouldn’t be talking about Java, but rather APIs and Data Services in the abstract. What am I missing?

As such, I don’t think we should do this. It’s more code to test and maintain that doesn’t have much to do with our story. If we did some helper plumbing, I think a minimal REST API would be better.

**Comment by rjrudin** [comment]
Good points above, closing this.
