### ISSUE TITLE
How to change modules Path

### ISSUE THREAD

**Issue by nblessing** [marklogic-community/ml-gradle#515]
As we are migrating from Roxy to Gradle for our project we decided to maintain the folder structure similar to the roxy folder structure. So basically I tried changing the modulesPath in the build.gradle file as below

ext {
  mlAppConfig {
	contentDatabaseName = "%%mlAppName%%"
	modulePaths.add("../src")
	dataConfig.dataPaths.add("../data/")
}}

Though I was successful in changing it to /src from /src/main/ml-modules/root, I was not able eliminate the /root folder since its seems to hardwired in ExportModulesTask.groovy

exportPath = modulePaths.get(modulePaths.size() - 1) + "/root"

Is there a way to eliminate this root folder and pick the source code from /src directly?

Thanks,
Blessing.

**Comment by nblessing** [comment]
Thanks for the explanation. In our case we are releasing a version #2 of
our application near soon.
The version #1 of the application used Roxy and we migrated to mlGradle in
v#2. Also the application is a fully non-REST modules.
We would like to retain our project structure similar to Roxy which our
developers across the globe are used to where all the Roxy related files
are in the "roxy" directory and the application codebase resides within
"src" directly.

Now migrating to mlGradle enforces to maintain the application code inside
src/root which we are trying to eliminate. I tried  changing the
exportPath to eliminate the root folder but that didnt help, looks like the
actual modules loader is in ml-javaclient-util.

Is there a way where we could parametrize the Modules export Path rather
than changing  code in mlgradle/ml-javaclient-util(which we dont want to)
so that we can eliminate the hassle to change the project structure.

Requesting your valuable suggestion and appreciate your help!

Thanks,
Blessing.

**Comment by rjrudin** [comment]
ml-gradle defaults to src/main/ml-modules as a modules path, and thus src/main/ml-modules/root is where all non-REST modules will go. Trying to standardize on "src" in a Gradle project isn't really a good idea. Gradle follows the Maven project structure convention, which is that all source code is in "src/main" for application code and "src/test" for test code. "src/main" then has child directories - e.g. "java" and "resources", and in ml-gradle's case, "ml-config" and "ml-modules". 

So on any Gradle or Maven project, it's extremely unlikely that any source files would be directly under "src". 

Now, you can still put the Roxy code in a "roxy" directory - that would be src/main/ml-modules/root/roxy. And then your application code can be in e.g. src/main/ml-modules/root/app. 

If you have test code, I would not however put that under src/main/ml-modules/root/test. Instead, add the following to gradle.properties:

    mlModulePaths=src/main/ml-modules,src/test/ml-modules

And then put your test code at src/test/ml-modules/root. 

I understand wanting to keep the current project structure, but that structure of having source files directly under "src" just isn't compatible with the Maven directory convention that is predominant in the Java ecosystem, for better or worse. 

Finally, I don't think modifying the export process helps much here, as that's a one-time process that's intended to simplify the migration process, with the expectation that you can make any changes you want after the export process completes.

**Comment by rjrudin** [comment]
Please reopen if there's anything left to do here
