### ISSUE TITLE
mlClearModulesDatabase causes error

### ISSUE THREAD

**Issue by dmcassel** [marklogic-community/ml-gradle#523]
When I run `mlReloadModules`, I'm seeing an error that I've narrowed down to the call to `mlClearModulesDatabase`:

> Could not get unknown property 'context' for task ':mlClearModulesDatabase' of type com.marklogic.gradle.task.databases.ClearModulesDatabaseTask.

The stack trace points to line 20 in [`ClearModulesDatabaseTask.groovy`](https://github.com/marklogic-community/ml-gradle/blob/b92e923715fd423605aadba071461210978867c9/src/main/groovy/com/marklogic/gradle/task/databases/ClearModulesDatabaseTask.groovy#L20). Sure enough, context is not defined in that class, nor in its parent (`MarkLogicTask`). On the other hand, `getManageClient()` is a method on the parent class. 

Looks like line 20 should simply remove the reference to `context` and call `getManageClient` directly.

**Comment by rjrudin** [comment]
Thanks @dmcassel , I just published a bugfix release for this - https://github.com/marklogic-community/ml-gradle/releases/tag/3.16.4

**Comment by dmcassel** [comment]
Thanks @rjrudin!
