### ISSUE TITLE
Ignore timestamps file by default with mlLoadModules

### ISSUE THREAD

**Issue by rjrudin** [marklogic-community/ml-gradle#528]
mlLoadModules isn't used that much, and there seems to be too much confusion when mlLoadModules doesn't load files due to the timestamps file. The timestamps file is needed for mlWatch. But I think there'd be far less confusion if mlLoadModules ignores the timestamp file. A property can be used to force it to pay attention to the timestamp file for backwards compatibility purposes.

**Comment by hansenmc** [comment]
I wouldn't say that it isn't used that much, but I do agree that it has been a common issue and point of confusion for users that when they attempt to use `mlLoadModules` it doesn't always load the modules when they expected it to.

**Comment by dmcassel** [comment]
I use mlLoadModules frequently, but I do find that I sometimes need to manually delete the timestamps file to ensure everything gets deployed.
