### ISSUE TITLE
Loading a TDE results in TDE-INCONSISTENTVIEW

### ISSUE THREAD

**Issue by josvanroosmalen** [marklogic-community/ml-gradle#532]
Hi,

Assume I have 2 TDE  _**U**_ and _**V**_ with the SAME name with column _**X**_ of type _**Y**_. I deploy this TDE. This is going fine. Now I change the of  _**X**_ to type  _**Z**_, and run a `mlDeploy`. 

This will result in a `TDE-INCONSISTENTVIEW` error.  For both TDE I have updated the type from __**X**__ to __**Z**__, however it seems that `mlDeploy` loads them not atomic.  So it loads first the first TDE with type __**Z**__ and finds that in the system there is an other TDE which is __**X**__, however in the same `mlDeploy` I am going to change that also to __**Z**__.

The solution is running `mlReloadSchemas` because this first removes the TDEs, however that is going to produce a full reindex if that is happening. An alternative is to take only the involved views offline prior to the load schemas. 

@rjrudin We need to load TDEs atomic to avoid this. If MLGradle is doing this, I will raise a BugTrack.

**Comment by rjrudin** [comment]
I am assuming that this is the same issue as https://github.com/marklogic-community/ml-gradle/issues/459 . If you're using a version of ml-gradle >= 3.13.0, please try reproducing this by loading the updated TDE manually via /v1/documents and see if you get the same error. If you do, it'd be an issue in the server. That's all that ml-gradle is doing - it's just loading the template via /v1/documents.
