### ISSUE TITLE
Documentation error on https://github.com/marklogic-community/ml-gradle/wiki/DMSDK-Tasks

### ISSUE THREAD

**Issue by taatuut** [marklogic-community/ml-gradle#533]
Documentation error on https://github.com/marklogic-community/ml-gradle/wiki/DMSDK-Tasks

`plugins {
  id "com.marklogic:ml-gradle" version "3.2.1"
}`

Should be:

`plugins {
  id "com.marklogic.ml-gradle" version "3.2.1"
}`

Replace the colon with a dot.

**Comment by rjrudin** [comment]
Thanks! Fixed it.
