### ISSUE TITLE
Need ml-gradle task configuration to run data hub flows

### ISSUE THREAD

**Issue by chenfiona** [marklogic-community/ml-gradle#534]
Need configuration in ml-gradle to orchestrate data hub flows ( run flows one by one )

**Comment by rjrudin** [comment]
This is outside the scope of ml-gradle; ml-gradle is intentionally not aware of DHF, as it's a general purpose build and deployment tool for MarkLogic applications.

**Comment by dmcassel** [comment]
@chenfiona you might want to file an issue at https://github.com/marklogic/marklogic-data-hub.

**Comment by chenfiona** [comment]
I did file the request in the said link. Basically I am looking at DH orchestration. Since we iron out Gradle, next will be Apache tools or JAR to schedule/run tasks.
