### ISSUE TITLE
Java 9 error while running ./gradlew mlDeploy (with sample project and plain vanilla gradle.properties)

### ISSUE THREAD

**Issue by sundarbandepalli** [marklogic-community/ml-gradle#535]
I have Java 8, 11 and 12 installed.  When I set Java Home to 8, I get this error message while running ./gradlew mlDeploy. 
A problem occurred configuring root project 'sample-project'.
> Could not open proj remapped class cache for 8pmrcz9l8qjkl3m0ikr222px8 (/Users/sbandepa/.gradle/caches/3.5/scripts-remapped/build_94t2vmwk4mhf6z8063o90iqmt/8pmrcz9l8qjkl3m0ikr222px8/projd83e59d2b532fa589b1d328df8684f7a).
  > Could not open proj generic class cache for build file '/Users/sbandepa/Downloads/ml-gradle-master/examples/sample-project/build.gradle' (/Users/sbandepa/.gradle/caches/3.5/scripts/8pmrcz9l8qjkl3m0ikr222px8/proj/projd83e59d2b532fa589b1d328df8684f7a).
   > com/marklogic/appdeployer/command/CommandContext has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
thoughts?

Now, when I set java home to 11 or 12 - getting a different error. /gradlew mlDeploy
FAILURE: Build failed with an exception.
* What went wrong:
Could not determine java version from '12.0.1'.
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

Java 9 is not available for download.

**Comment by rjrudin** [comment]
ml-gradle 4 requires Java 9 or higher. The problem you're getting is an incompatibility issue between Gradle and the version of Java you're using. Try using Gradle 5 or 6 when using Java 11 or 12 (Gradle 4 may work as well).

**Comment by dmcassel** [comment]
In case it helps someone else, the combination of OpenJDK 13, Gradle 5.0.0, and ml-gradle 4.0.0 gave me an error (which I've already cleared, so I can't paste it). Upgrading to Gradle 6.2.2 made it happy again.
