### ISSUE TITLE
Error Caused by Apparent Change in Behavior of ml-gradle's mlLoadModules Task

### ISSUE THREAD

**Issue by shoppen60** [marklogic-community/ml-gradle#542]
I help develop and support a MarkLogic application that we manage with the ml-gradle Gradle plugin.

I am trying to upgrade our ml-gradle version from 3.7.0 to 3.17.0.

However, with 3.17.0, I encounter an XDMP-CONFLICTINGUPDATES error when trying to deploy the application’s XQuery and JavaScript modules.

The modules are in three different source trees.

The intent is that many of the modules in one of the source trees replace modules in another of the trees—that is, they are loaded to the same document URIs.

This works fine with ml-gradle version 3.7.0 because, as is apparent from the output of running the deployment script with the “-i” option, the three sets of modules are loaded in separate transactions; the modules in a later transaction overwrite those in an earlier one.

However, it’s apparent from the output of running the script in 3.17.0 that ml-gradle/ml-app-deployer is trying to load the modules from all three source trees in one transaction.

This precipitates the aforementioned conflicting updates.

Is there a property we can set, or some other way to load the modules in separate transactions, or must we eliminate the “overridden” source modules so that only the “overriding” ones are loaded?

Please let me know if you have any questions, concerns or need further information.

Thank you!

**Comment by hansenmc** [comment]
That sounds a little dangerous. How do you know which of the modules should "win" and be the one loaded at a particular URI?

One workaround would be to maintain your modules in a different directory structure, then use some task to do your module overlay into a consolidated area, and then deploy those consolidated modules.

**Comment by rjrudin** [comment]
@shoppen60 Long time no chat! Try setting mlModulesLoaderBatchSize=1, or some number low enough that will cause the modules to be written in multiple transactions such that there's no chance that the modules that resolve to the same URI will be in the same batch (1 is sure to work, but will be the slowest approach).

**Comment by shoppen60** [comment]
Hi, @rjrudin! Yes, it's been too long! I hope you and your family are staying safe.

@hansenmc thinks our app's module strategy sounds a little dangerous. Would you like to tell him about the EMF and its "hooks" mechanism, or should I? ;-)

Anyway, in order to gauge an appropriate mlModulesLoaderBatchSize, is there any assurance of the order in which modules are loaded and their URIs resolved?

For example, it appears modules are loaded from their file trees in the order the trees' base directories are listed in the mlModulePaths property.

Is that likely to remain the case?

If so, then given that, in our application's case, many of the modules under the second directory listed are to replace ones under the first directory, and modules in the third directory do not replace any other modules, then the optimal mlModulesLoaderBatchSize would seem to be the number of modules under the first directory. (At this point, that number does not vary.)

Does that sound viable?

Thanks!

**Comment by rjrudin** [comment]
Yes, setting it to the number of modules in EMF should do the trick.

**Comment by rjrudin** [comment]
Closing this, but please report back if it's still an issue
