### ISSUE TITLE
DMSDK Collection Delete against DHS not deleting

### ISSUE THREAD

**Issue by awanczowski** [marklogic-community/ml-gradle#543]
When targeting a DHS Instance the data for the collection specified in the task is not removed from the final data base. 

```

task deleteDailyReportData (type: com.marklogic.gradle.task.datamovement.DeleteCollectionsTask) {
  collections = ["Daily_Report_Ingest"]
}

```

**Comment by rjrudin** [comment]
Closing this, as it's not actionable without credentials, and we don't want to communicate those here. Will resolve this internally.
