### ISSUE TITLE
Deprecated properties / methods `destinationDir` and `baseName` in creating mlBundle

### ISSUE THREAD

**Issue by lifan0127** [marklogic-community/ml-gradle#545]
When running the provider project, the following deprecation warnings were reported:

https://github.com/marklogic-community/ml-gradle/blob/master/examples/dependency-project/provider-project/build.gradle

```bash
The AbstractArchiveTask.destinationDir property has been deprecated. 
This is scheduled to be removed in Gradle 7.0. 
Please use the destinationDirectory property instead. 
See https://docs.gradle.org/6.3/dsl/org.gradle.api.tasks.bundling.AbstractArchiveTask.html#org.gradle.api.tasks.bundling.AbstractArchiveTask:destinationDir for more details.

The AbstractArchiveTask.baseName property has been deprecated. 
This is scheduled to be removed in Gradle 7.0. 
Please use the archiveBaseName property instead. 
See https://docs.gradle.org/6.3/dsl/org.gradle.api.tasks.bundling.AbstractArchiveTask.html#org.gradle.api.tasks.bundling.AbstractArchiveTask:baseName for more details.
```

The warnings are related to the bundleJar task

```gradle
task bundleJar(type: Jar) {
	from("src/main/ml-config") {
		into("example-dependency/ml-config")
	}
	from("src/main/ml-modules") {
		into("example-dependency/ml-modules")
	}
	from("src/main/ml-data") {
		into("example-dependency/ml-data")
	}
	from("src/main/ml-plugins") {
		into("example-dependency/ml-plugins")
	}
	from("src/main/ml-schemas") {
		into("example-dependency/ml-schemas")
	}
	destinationDir file("build/libs")
	baseName "example-dependency"
}
```

However, updating the method names would lead to "Could not find method" error:

```bash
Could not find method destinationDirectory() for arguments
```

**Comment by Lucas3oo** [comment]
+1.
I get the same error on the zip task.
All tasks from AbstractArchiveTask.java seems to have this.
Looking into AbstractArchiveTask.java I only see a "getter" for getArchiveBaseName() but no setter.

I am using Gradle 7.0.2

**Comment by rjrudin** [comment]
Thanks, just pushed a fix, the Gradle syntax is:

```
archiveBaseName = "my-name"
destinationDirectory = file("some-lib")
```

**Comment by khushbooparmargit** [comment]
Configure project :react-native-reanimated
Android gradle plugin: 7.4.2
Gradle: 8.0.1
The AbstractCompile.destinationDir property has been deprecated. This is scheduled to be removed in Gradle 9.0. Please use the destinationDirectory property instead. Consult the upgrading guide for further information: https://docs.gradle.org/8.0.1/userguide/upgrading_version_7.html#compile_task_wiring       


solve this

**Comment by kavithareddyedula** [comment]
upgrade from gradle 6.8 to gradle 7.5  
deprecated  3 : archiveName,baseName,destinationDir 
respective new methods/ fileds names plz 

task tarGz(type: Tar, dependsOn: copyJar) {
    from 'build/appBundle'
    **archiveName**  = "${rootProject.name}-${version}.tar.gz"
    compression = Compression.GZIP
     **baseName**= rootProject.name
    **destinationDir** = file('build')
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

**Comment by rjrudin** [comment]
@ kavithareddyedula Gradle is telling you how to fix the deprecation warnings. See https://github.com/marklogic/ml-gradle/issues/545#issuecomment-852101794 as well.
