### ISSUE TITLE
Tasks that only differ by `task-root` do not all get imported

### ISSUE THREAD

**Issue by ahwitz** [marklogic-community/ml-gradle#547]
**Describe the bug**
We have a case where two AppServers are served from the filesystem using almost-identical codebases which include scheduled tasks. This means that we have two scheduled tasks that need to be deployed with identical configuration except for the `task-root` property. Running `gradle -i mlDeployTasks` with configuration for both of these tasks causes only the second one encountered to be stored.

I'm fairly certain this is related to upstream functionality, but I'm not sure if it's in one of these Github repos or in the ML codebase. `GET /manage/v2/tasks` does not return the `task-root` property, which might be related.

**To Reproduce**
This is a very base-case reproduction that doesn't require valid filesystem paths.
1. Make a `gradle.properties` file with `mlConfigPaths=src/main/test-config`
2. Make a `/src/main/test-config/tasks` directory with two files, 'test-one.json' and 'test-two.json'.
3. In test-one.json:
```json
{
    "task-database": "Documents",
    "task-enabled": true,
    "task-modules": "",
    "task-path": "/test/path",
    "task-period": 1,
    "task-priority": "normal",
    "task-root": "/test/root/one",
    "task-start-time": "00:05:00",
    "task-type": "daily",
    "task-user": "nobody"
}
```
4. In test-two.json:
```json
{
    "task-database": "Documents",
    "task-enabled": true,
    "task-modules": "",
    "task-path": "/test/path",
    "task-period": 1,
    "task-priority": "normal",
    "task-root": "/test/root/two",
    "task-start-time": "00:05:00",
    "task-type": "daily",
    "task-user": "nobody"
}
```
(only difference being `task-root`)
5. Run `gradle -i mlDeployTasks`.
6. Check :8001 Default scheduled tasks listing, and only one shows up.

**Expected behavior**
First: the `gradle` output is as follows:
```
Executing command [com.marklogic.appdeployer.command.tasks.DeployScheduledTasksCommand] with sort order [800]
Processing files in directory: /gradle/src/main/test-config/tasks
Processing file: /gradle/src/main/test-config/tasks/test-one.json
Sending XML GET request as user 'andrew' to path: /manage/v2/tasks?group-id=Default
Checking for existence of resource: null
Sending XML GET request as user 'andrew' to path: /manage/v2/tasks?group-id=Default
Creating task: /test/path
Sending JSON POST request as user 'andrew' to path: /manage/v2/tasks?group-id=Default
Created task: /test/path
---------
Processing file: /gradle/src/main/test-config/tasks/test-two.json
Sending XML GET request as user 'andrew' to path: /manage/v2/tasks?group-id=Default
Checking for existence of resource: 6838552124715619820
Sending XML GET request as user 'andrew' to path: /manage/v2/tasks?group-id=Default
Deleting scheduled task first since updates are not allowed except for task-enabled; task ID: 6838552124715619820
Checking for existence of resource: 6838552124715619820
Sending XML GET request as user 'andrew' to path: /manage/v2/tasks?group-id=Default
Sending XML GET request as user 'andrew' to path: /manage/v2/tasks?group-id=Default
Deleting task at path /manage/v2/tasks/6838552124715619820?group-id=Default
Sending  DELETE request as user 'andrew' to path: /manage/v2/tasks/6838552124715619820?group-id=Default
Deleted task at path /manage/v2/tasks/6838552124715619820?group-id=Default
Creating task: /test/path
Sending JSON POST request as user 'andrew' to path: /manage/v2/tasks?group-id=Default
Created task: /test/path
Finished executing command [com.marklogic.appdeployer.command.tasks.DeployScheduledTasksCommand] in 10174ms
```
This was done with no overlapping tasks in MarkLogic, so I would expect neither of these files to delete an existing/duplicate scheduled task.

I would also expect to have two new tasks, one for each `task-root`, created in the scheduled task listing for the Default group.

Let me know if any more information is needed!

**Comment by rjrudin** [comment]
Thanks for the detailed report. Checkout https://github.com/marklogic-community/ml-app-deployer/wiki/Scheduled-Tasks#deploying-multiple-tasks-with-the-same-task-path - because it's not feasible for a scheduled task file to contain its actual ID (which ML generates), ml-gradle uses a compound key of task-path and task-database.

For your use case - could you have task-root of "/" and then task-path would differ for each task? I believe that task-root is primarily for referring to OOTB ML modules. For custom modules that are likely in your modules database, I believe it's typical to set task-root to "/" and then task-path is the absolute path to your module.

**Comment by ahwitz** [comment]
> ml-gradle uses a compound key of task-path and task-database.

We actually found this as part of a migration to a different machine with different `task-root` values the other day, so in the end, this likely saved us a decent amount of time, too...

> For custom modules that are likely in your modules database, I believe it's typical to set task-root to "/" and then task-path is the absolute path to your module.

One thing I may have missed in the writeup is that all of these are currently `filesystem` AppServers, and our convention across the codebase is to use absolute paths for XQuery `import`s/SJS `require`s.

Creating the following task:
```json
{
    "task-database": "Documents",
    "task-enabled": true,
    "task-modules": "",
    "task-path": "%%PATH_TO_ROOT%%tasks/test.xqy",
    "task-period": 1,
    "task-priority": "normal",
    "task-root": "/",
    "task-type": "minutely",
    "task-user": "nobody"
}
```
... in a repository with the structure:
```
/tasks/
    /collections-on-save.xqy
    /test.xqy
```

...with the following import:
```xquery
import module namespace cos = "http://rilm.org/egret/collections-on-save" at "/tasks/collections-on-save.xqy";

xdmp:log('triggered'),
xdmp:log($cos:cos-prefix)
```

...yields the following error:
```
2020-04-27 10:56:00.304 Notice: SVC-FILOPN: File open error: open '/tasks/collections-on-save.xqy': No such file or directory
2020-04-27 10:56:00.304 Notice:+in /Users/ahorwitz/path/to/tasks/test.xqy, at 2:0 [1.0-ml]
```

We're hoping this isn't going to be a case of needing to refactor everything that the task relies on, and/or that we won't have to add a manual "dupe the scheduled task" task to our deployment process. Do we have an option other than "Convert to module-based appservers." or "Convert to relative import paths."?

**Comment by rjrudin** [comment]
What version of ml-gradle are you using? Changing ml-app-deployer (specifically, a method in the TaskManager class) to account for task-root would not be difficult, and it's about time for a minor release to account for a handful of small changes. This would likely be a 4.0.2 or 4.1.0, but a 3.17.1 or 3.18.0 is possible too.

**Comment by ahwitz** [comment]
Currently on 3.x.x, but this is the only thing we use Java for on our servers, so upgrading to 4 could also be feasible.

Do you know offhand if the AWS Coretto JDK is compatible with the entire stack here? They advertise it as [a "distribution of OpenJDK"](https://docs.aws.amazon.com/corretto/latest/corretto-11-ug/what-is-corretto-11.html), but your [installation docs page](https://docs.marklogic.com/guide/installation/intro#id_78179) doesn't explicitly say it's okay; `yum search openjdk` on AWS Linux only gives me 7/8/14 as options, and we're currently on 8/the installation docs page says support caps at 11.

I can send in a quick request through help.marklogic.com if you want, but I figured this might be a bit closer to the source...

**Comment by rjrudin** [comment]
I don't know about the AWS JDK. I've only been using OpenJDK for Java 9+. 

I think the fastest/simplest workaround is to create a custom Gradle task to create your second scheduled task. So put one scheduled task file under src/main/ml-config/tasks. Then see https://github.com/marklogic-community/ml-gradle/wiki/Writing-your-own-task for instructions on how to make a task that uses getManageClient().post/putJson to send your task JSON to the Manage API.

The one catch is I believe you'll still need to do what ml-gradle is doing - i.e. checking to see if a POST or PUT is needed based on whether the task exists or not. If you look at TaskManager.getResourceId in ml-app-deployer, you can copy that to figure it out and use hardcoded values in the XPath expression. I unfortunately don't know of a better way to answer the question of "Does this scheduled task exist or not?"

Alternatively, you can do a hack where you do a POST, and if that fails, do a PUT instead. Or if you don't expect the contents of the task to really ever change, then just log the error as a warning and move on. 

Can you also submit a ticket to ml-app-deployer? That's where the change will occur (and it's more useful if someone besides me creates the ticket). Indicate whether you'd prefer a 3.x or 4.x release, or if it doesn't matter.

**Comment by ahwitz** [comment]
^ Cross-referenced above. Will contact formal support and ask them about the Amazon JDK, but forcing us onto 4.x shouldn't be a huge issue.

We'll also look into the dupe tasks if we have a need to before y'all have a chance to get to this. We also have some custom `HttpTask`s jury-rigged (securely) to run as admin because of other limitations, and we could theoretically wire a manual call to `admin:group-add-scheduled-task` if necessary.

(If you want this ticket closed, that's fine by us; not sure if you do want that, though)

**Comment by rjrudin** [comment]
Closing this, as it's being addressed in ml-app-deployer
