### ISSUE TITLE
Assign content-database during mlDeployTemporal

### ISSUE THREAD

**Issue by rodgersandrew** [marklogic-community/ml-gradle#548]
Is there a way to choose which server/database applies the temporal configuration during mlDeploy/mlDeployTemporal?

Context: Say we have a datahub-STAGING and datahub-FINAL app server with respective databases. It seems that the temporal configuration is only applied to the datahub-FINAL database. We would like to have a set of temporal collections deployed to datahub-STAGING and a separate set of temporal collections deployed to datahub-FINAL.

I have tried including additional servers in ml-config directory, but it does not seem to have any impact.

Please advise on any other solutions/workarounds or if this capability is currently not possible.

**Comment by rjrudin** [comment]
Yes - see https://github.com/marklogic-community/ml-gradle/wiki/Project-layout#database-specific-resources . Please reopen if you find this doesn't work, as that would indicate a bug (provide steps to reproduce too).

**Comment by rodgersandrew** [comment]
@rjrudin, had a feeling I just couldn't find the right docs, thanks! Works exactly as desired.
