### ISSUE TITLE
MlcpTasks Fail When Deploying App with ml-gradle 3.17.0 to MarkLogic Server 10.0-4

### ISSUE THREAD

**Issue by shoppen60** [marklogic-community/ml-gradle#550]
We use ml-gradle (currently version 3.17.0) to deploy an application to MarkLogic Server (currently version 10.0-4.)

The deployment includes several MlcpTasks to upload content from a filesystem (which is not a Hadoop filesystem.)

While the tasks succeeded when deploying to MarkLogic 9, they now fail (though they do report the correct number of input paths to process.)

Each failing task's output includes the following two messages:

2020-05-04 13:17:25 ERROR LocalJobRunner:148 - Error checking output specification: 
2020-05-04 13:17:25 ERROR LocalJobRunner:149 - java.lang.IllegalArgumentException: No enum: segment

Though we can upload the content successfully using MLCP version 10.4.0's mlcp.bat manually from the command line, we'd prefer to use ml-gradle.

Suggestions?

Please let me know if you need further information.

Thanks!

**Comment by rjrudin** [comment]
Hey @shoppen60 - bump up the version of MLCP that you're using - you're running into an incompatibility between MLCP and ML. Closing this as I'm 99.9% sure that's the fix, but please reopen if you find otherwise.
