### ISSUE TITLE
Unsupported Authentication Scheme Error When Trying to Run Tests After Reloading Modules

### ISSUE THREAD

**Issue by shoppen60** [marklogic-community/ml-gradle#553]
We're upgrading from ml-gradle 3.7.0 to 3.17.1 to manage an application using MarkLogic Server 10.0-4.

When we run "gradle mlReloadModules" (or any other task that causes modules to be reloaded) and then run "gradle test", the tests fail immediately, encountering the errors, "Error occurred while loading modules; host: localhost; port: 8022; cause: unsupported auth scheme: [Basic realm=public]."

I have attached a file to which the "gradle -i test" command's output was redirected. It provides details about the errors. (See below, after the paragaraph beginning, "Judging by...")

The errors occur while trying to load REST modules.

The port in question is the test REST port (value of the mlTestRestPort Gradle property), which is configured to use Basic authentication.

(Note: the application's Gradle properties include "mlRestAuthentication=basic".)

Judging by the stack traces in the attached log, it appears the DefaultModulesLoader and ResourceExtensionsImpl expect to use Digest authentication with that port
[test-error.log](https://github.com/marklogic-community/ml-gradle/files/4670509/test-error.log)
.

Beside ml-gradle 3.17.1, the application's testImplementation dependencies include com.marklogic:ml-junit:3.1.0 and com.marklogic:ml-app-deployer:3.17.0 (which depends on com.marklogic::ml-javaclient-util:3.14.0). 

Curiously enough, running "gradle test" after the failures results in the task not trying to load modules again, and the tests succeed.

However, we'd rather not have to invoke the tests twice in our CI/CD system.

Is there something we can do to prevent this issue?

Please let me know if you have questions or need further information.

Thanks!

**Comment by rjrudin** [comment]
Is the 8022 app server expecting digest auth instead of basic? I recall there being a custom task in your build.gradle file to fiddle with basic/digest auth on the app servers, but I can't remember what it was.

**Comment by shoppen60** [comment]
The 8022 App Server expects Basic auth.

We do have a custom task that sets the main REST App Server's (port 8020) auth scheme to Basic just after that App Server is created, but it does not do so to the test server (8022.)

To confirm what appears to be happening, I reloaded modules, then reset 8022's auth scheme to Digest.

Then I configured Gradle to run some tests that post content to the test REST port (8022) using Basic auth, and ran them.

Though the loading of REST modules succeeded, the tests failed.

So it seems to me that, while the 8022 App Server expects Basic auth, the REST modules loading expects to use Digest auth.

**Comment by rjrudin** [comment]
Check what's documented at https://github.com/marklogic-community/ml-gradle/wiki/Property-reference#rest-api-server-connection-properties - that notes that the call to /v1/rest-apis results in a REST server that uses digest, and so if you want to use basic, you have to do a couple things. 

Also, I just checked my (probably pretty old) copy of build.gradle from your project, and saw the SetRestApiToBasicAuthCommand command the comments on it. 

Finally - another thing to check is if ModulesLoaderTestExecutionListener.class is still used in AbstractEmfTest. The purpose of that was to do the same thing as mlWatch. But it's not necessary and can be removed. I wonder if the error is coming from there - i.e. if it's trying to load modules when the test suite begins.

**Comment by shoppen60** [comment]
AbstractEmfTest was indeed still using ModulesLoaderTestExecutionListener.

I was wondering why the modules were being reloaded before the tests were run.

I removed the ModulesLoaderTestExecutionListener and the tests run fine.

Thanks!
