### ISSUE TITLE
404s in documentation

### ISSUE THREAD

**Issue by mikeburl** [marklogic-community/ml-gradle#555]
**Describe the bug**
There's now a couple of links in the 'Loading modules in SSL' page where they will either return 404 or don't appear to link to the resource they intend to.  Specifically- 'certificate template config file' returns a 404, build.gradle has no mention of GenerateTemporaryCertificateCommand, and gradle.properties has no mention of mlSimpleSsl.  

**To Reproduce**
1. Go to https://github.com/marklogic-community/ml-gradle/wiki/Loading-modules-via-SSL
2. Click on the "certificate template config file" link
3. 404

**Expected behavior**
The certificate template config file

**Comment by rjrudin** [comment]
Thanks - all references in that section now point to ssl-project instead of sample-project.
