### ISSUE TITLE
Kerberos Ticket authentication is not supported

### ISSUE THREAD

**Issue by crism** [marklogic-community/ml-gradle#557]
**Describe the bug**
When a server is set to authenticate with `kerberos-ticket`, an error is received:
```
> No enum constant
com.marklogic.client.ext.SecurityContextType.KERBEROS-TICKET
```

**To Reproduce**
1. Set up a server definition using macros: `"authentication": "%%testServerAuth%%"`
1. In the gradle properties, define authentication as Kerberos ticket: `testServerAuth=kerberos-ticket`
1. Deploy the server definitions.
1. Receive error above.

**Expected behavior**
Kerberos ticket authentication should be deployed to the target app server.

**Notes**
If authentication is defined in properties as `kerberos`, we do not get the enum error; however, the server definition payload is rejected by the REST API, as `kerberos` is not a valid authentication value.

The root cause is that the app deployer gets the authentication property and looks it up using case transformation: `SecurityContextType.valueOf(prop.toUpperCase())`. The security enum has `KERBEROS` as a value, but not `KERBEROS-TICKET`, so the lookup fails; the other way around, `kerberos` is rejected by the management API.

The workaround is to set `kerberos` in the gradle properties file, but to hard-code `kerberos-ticket` in the JSON payload.

The problem may be in the Data Hub Framework rather than ml-gradle; it’s not clear whose responsibility the mismatch is.

**Comment by rjrudin** [comment]
testServerAuth isn't an ml-gradle or DHF property, so I don't know how it's being used other than as a token in the app server file. 

If it's being used to configure the construction of a DatabaseClient, it's not valid because "kerberos-ticket" isn't a valid value for selecting an ML Java Client SecurityContext. The value "kerberos" corresponds to a KerberosAuthContext - http://docs.marklogic.com/javadoc/client/com/marklogic/client/DatabaseClientFactory.KerberosAuthContext.html - and there is no such thing as a KerberosTicketAuthContext. 

I believe the problem lies with how the "testServerAuth" property is being used for two different purposes. But that's a problem with how the custom property is being used, it's not an ml-gradle or DHF issue.

**Comment by crism** [comment]
This was with DHF; I oversimplified the description. If this is done for the staging server:
```
mlStagingAuth=kerberos-ticket
```
and in `staging-server.json`:
```
"authentication": "%%mlStagingAuth%%"
```
In the latest DHF code, `hubConfigImpl` has this line in `newStagingClient()`:
```
config.setSecurityContextType(SecurityContextType.valueOf(stagingAuthMethod.toUpperCase()));
```
… which reads the `mlStagingAuth` and tries to find an enum. Please reopen this.

**Comment by rjrudin** [comment]
I got it now - please open this as a new ticket in DHF - the general request is that you want the ability to specify different values for the authentication method used by an app server and the authentication method used for constructing a DatabaseClient (kerberos/kerberos-ticket may be the only instance right now, but there could be more in the future). Sounds like this would pertain to the final and job servers as well. 

As a workaround - you can change the content of staging-server.json, and better yet, I believe you can add a staging-server to the ml-config directory with your preferred authentication value in there, and the two files will be merged together.

**Comment by crism** [comment]
Yes, the workaround is to set the gradle auth to `kerberos` and the JSON payload to `kerberos-ticket`. This makes using macros for authentcation impossible, which makes having different authentication at different service tiers challenging.
I will open this against DHF.
