### ISSUE TITLE
CallResourceTask causes failure of any task if credentials are not set up. 

### ISSUE THREAD

**Issue by dmcassel** [marklogic-community/ml-gradle#558]
Please use the debugging guide first to see if you can identify the problem - https://github.com/marklogic-community/ml-gradle/wiki/Debugging-guide . That addresses the most common bugs, such as not being able to load modules, or getting any error when deploying a particular resource, or getting any error with one of the data movement asks. 

**Describe the bug**
For projects using the credentials plugin, the credentials may not be configured after cloning a project. If the project has a CallResourceTask, then even calling "./gradlew addCredentials" will fail, reporting: 

    Could not create task of type 'CallResourceTask'.

**To Reproduce**
1. Create an ml-gradle project that uses the credentials plugin and uses those credentials for mlAppConfig.restAdminUsername and mlAppConfig.restAdminPassword. 
2. Create a task of type CallResourceTask. 
3. Try to run "./gradlew addCredentials --key anykey --value anyvalue"

**Expected behavior**
If I'm not trying to run the CallResourceTask, it shouldn't interfere with me running other commands.

**Comment by dmcassel** [comment]
I suspect that the problem is that [CallResourceTask calls `newClient()` on initialization](https://github.com/marklogic-community/ml-gradle/blob/4428c5011fc59c2e68f492e3914e40fb3218449a/src/main/groovy/com/marklogic/gradle/task/client/CallResourceTask.groovy#L13) and that deferring that until needed will solve the problem. I'll try testing that.

**Comment by rjrudin** [comment]
Thanks @dmcassel  - no idea why I did that, see it defaults to newClient() in the task method. Can definitely do a bugfix release for that.

**Comment by dmcassel** [comment]
@rjrudin PR sent. A bugfix release would be great; this is causing some trouble at one of my clients.

**Comment by rjrudin** [comment]
Thanks @dmcassel  - here's the release - https://github.com/marklogic-community/ml-gradle/releases/tag/4.0.4
