### ISSUE TITLE
Gradle npm install fails with error:"spawn npm ENOENT" unless you install all dependencies in the subfolders

### ISSUE THREAD

**Issue by Brendan-NTT** [marklogic-community/ml-gradle#561]
**Describe the bug**
*npm install* fails with a "spawn npm ENOENT" error unless you run *npm install* from inside each of the depenency subfolders first 

**To Reproduce**
1. Follow the instructions on the MarkLogic getting started Gradle page : https://marklogic-community.github.io/grove/guides/getting-started/
2. Step 7 (*npm start*) fails unless you install all dependencies

**Expected behavior**
Gradle starts

**Comment by rjrudin** [comment]
This issue is specific to the grove project - can you please file it there? (I tried to use the "Transfer" feature in github, but it wouldn't let me select grove). 

The grove project is linked to in those docs - it's at https://github.com/marklogic-community/grove .
