### ISSUE TITLE
ml-gradle install error with openjdk 1.8 - classfile version error

### ISSUE THREAD

**Issue by Brendan-NTT** [marklogic-community/ml-gradle#562]
**Describe the bug**
When following the instructions in the README.md the following error is encountered : 

"FAILURE: Build failed with an exception.

* Where:
Build file '/opt/Grove/GRDC_Search_Portal/ml-gradle/build.gradle' line: 1

* What went wrong:
An exception occurred applying plugin request [id: 'com.marklogic.ml-gradle', version: '4.0.1']
> Failed to apply plugin [id 'com.marklogic.ml-gradle']
   > Could not create plugin of type 'MarkLogicPlugin'.
      > Could not generate a decorated class for type MarkLogicPlugin.
         > com/marklogic/appdeployer/AppDeployer has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0"

openjdk :
openjdk version "1.8.0_262"
OpenJDK Runtime Environment (build 1.8.0_262-b10)
OpenJDK 64-Bit Server VM (build 25.262-b10, mixed mode)

CentOS 8.

**To Reproduce**
1. Follow README.md instructions

**Expected behavior**
ml-gradle should be installed.

**Comment by rjrudin** [comment]
This sounds specific to your project's README file - the README file for ml-gradle - https://github.com/marklogic-community/ml-gradle/blob/master/README.md - states that Java 9 or higher is needed for ml-gradle 4.
