### ISSUE TITLE
newAppServicesDatabaseClient doesn't use mlAppServicesPort

### ISSUE THREAD

**Issue by grtjn** [marklogic-community/ml-gradle#569]
https://github.com/marklogic-community/ml-gradle/wiki/Writing-your-own-task tells you can use the following approach to execute code via AppServices port:

```
task myJavascriptTask(type: com.marklogic.gradle.task.ServerEvalTask) {
  client = mlAppConfig.newAppServicesDatabaseClient("name of database")
  javascript = "my JS code here"
}
```

My console output seems to indicate it is running against mlRestPort instead, not mlAppServicesPort.

I am trying to run something like:

```
task undeployQcBrand(type: com.marklogic.gradle.task.ServerEvalTask) {
    group 'Deployment Branding'
    logger.info("Removing QueryConsole branding.")
    client = mlAppConfig.newAppServicesDatabaseClient("Documents")
    xquery =
        "xquery version '1.0-ml';\n"+
        "xdmp:eval('"+
        "  xquery version \"1.0-ml\"; \n"+
        "  declare namespace env-ui = \"http://marklogic.com/environment-ui\"; \n"+
        "  let \$env-ui-node := \n"+
        "    fn:doc(\"/cluster-ui-settings.xml\")/env-ui:environment-ui \n"+
        "  return \n"+
        "    if (exists(\$env-ui-node)) then \n"+
        "      xdmp:node-replace(\$env-ui-node/env-ui:ui-active, <env-ui:ui-active>{fn:false()}</env-ui:ui-active>)\n"+
        "    else ()',\n"+
        "  (),\n"+
        "  <options xmlns='xdmp:eval'>\n"+
        "    <database>{xdmp:database('App-Services')}</database>\n"+
        "  </options>)"
```

The above is supposed to run before mlUndeployApp, and runs fine when mlRestPort is still available, but fails if you try to run it a second time.

**Comment by grtjn** [comment]
Is there an easy workaround? Could use a quick fix..

**Comment by rjrudin** [comment]
Here's the code in question - https://github.com/marklogic-community/ml-app-deployer/blob/master/src/main/java/com/marklogic/appdeployer/AppConfig.java#L412 . appServicesPort is used, and the only time it's set is when mlAppServicesPort is configured. It defaults to 8000. 

I recommend running the task by itself and checking which access log is getting hit. And look for a reference to mlAppServicesPort - e.g. perhaps it's set in gradle-*.properties to the same value as mlRestPort.

**Comment by grtjn** [comment]
This is using `id 'com.marklogic.ml-data-hub' version '5.2.3'`. Running with this property `mlAppServicesPort=8300`. (I am running against a dockerized MarkLogic, with 8300 mapped to 8000 inside the container)

Interestingly, adding `-PmlRestPort=8300`, or `-PmlAppServicesPort=8300` makes no difference..

**Comment by rjrudin** [comment]
Ah - please close this and open it as a DHF ticket. You're not using ml-gradle when you use DHF, you're using the DHF Gradle plugin, which extends and modifies ml-gradle behavior. For example, mlRestPort has no impact in DHF. 

Please include steps to reproduce the problem as well - i.e. the task definition, what's in gradle.properties and gradle-local.properties, and what error you're getting.

**Comment by grtjn** [comment]
Ah, right... FYI: `-PmlFinalPort=8300` did work. Should have known mlRestPort wasn't used.

**Comment by grtjn** [comment]
Created new ticket here: https://github.com/marklogic/marklogic-data-hub/issues/4562
