### ISSUE TITLE
ml-gradle appears to decide it must create forests

### ISSUE THREAD

**Issue by shoppen60** [marklogic-community/ml-gradle#573]
My organization has a Gradle script for deploying an application to MarkLogic (version 10.0-4.2) using ml-gradle version 3.17.1 (to which we upgraded three months ago).

The script has not been changed in any significant way for many months.

However, a week ago, it began creating forests in our Dev and Test environments for which there are no pre-existing configurations.

(Or it appears to have begun creating the forests then; our MarkLogic DBA says it is reported to him that the forests have been "open" since last Tuesday, September 8.)

This precipitates errors in the application indicating the newly created forests are not available.

The only ml-gradle specific tasks upon which our deployment task depends are mlReloadModules and mlUpdateIndexes.

The dependency on mlUpdateIndexes was added three weeks ago, when an element range index was added to the content database's configuration document. (The intent is to remove the mlUpdateIndexes dependency once the updated configuration has been deployed to the Dev, Test and Production databases.)

Hence, the dependency on mlUpdateIndexes precedes the first time the additional forests were created by two weeks.

Though we have updated many of the application's XQuery source files recently, none of the updates includes code to create or otherwise manage forests.

Our application's content database in the Dev and Test environments is set up to have 18 forests, 9 whose Status the Admin UI reports as "open", and another 9 whose Status is "sync replicating".

The 9 "open" forests' names are "chs-content-p1.1" through "chs-content-p1.6", "chs-content-p2.1" through "chs-content-p2.6" and "chs-content-p3.1" through "chs-content-p3.6". The "sync replicating" forests' names are the same as the "open" forests, with 
either "-s2" or "-s3" appended.

The newly created 9 forests' names are "chs-content-19" through "chs-content-27". (Our DBA assumes 9 forests are being created because MarkLogic by default wants 3 forests per DB per node in the cluster; we have 3 nodes in out cluster.)

I am attaching the log output from running our deployment task (named "chsDeploy") with the --debug option.

If you search it for the string "chs-content-19", you'll see the first occurrence in a JSON document preceded by the log message "Submitting configuration:". That message is preceded by messages announcing GET requests to retrieve the properties for the 18 pre-existing forests.

Our question is, why is ml-gradle submitting a request to create the forests?

I am also attaching our application's build.gradle file (named build.txt to mollify GitHub). Again, our deployment task is named "chsDeploy".

My thanks for your help!

[chs-deploy-debug.log](https://github.com/marklogic-community/ml-gradle/files/5228181/chs-deploy-debug.log)

[build.txt](https://github.com/marklogic-community/ml-gradle/files/5228194/build.txt)

**Comment by rjrudin** [comment]
Did you upgrade ML recently in those environments? And if so, from what ML version?

My hunch is that you upgraded from an older version of ML 9 that does not support the Configuration Management API (CMA). Now that you're on a version that does support CMA, ml-gradle says - oh hey, I can use CMA to speed up deployments. And I'm wondering if that's revealed a lingering bug in mlUpdateIndexes that is triggered when CMA is available - i.e. it will try to create forests, but if CMA isn't available, it won't. 

The easy workaround here should be to just add mlCreateForests=false to either gradle-*.properties or to the command line - e.g. -PmlCreateForests=false . 

If you can confirm the above, I can create a ticket in ml-gradle to force mlCreateForests=false to ensure that the command never tries to create forests.

**Comment by shoppen60** [comment]
Yes, we upgraded to ML 10.0-4.2 from 9.0.7 recently in our Test and Production environments, and to ML 10 from 9.0.7 in Dev a few months or so ago.

We added mlCreateForests=false to our gradle properties file, built and deployed our application to Dev, and no forests were created.

Many thanks!

**Comment by rjrudin** [comment]
Opened #574 to improve mlUpdateIndexes
