### ISSUE TITLE
Inconsistent encoding handling with mlLoadModules across OSes

### ISSUE THREAD

**Issue by ahwitz** [marklogic-community/ml-gradle#583]
**Describe the bug**
We've been trying to load the [swagger-ui](https://github.com/swagger-api/swagger-ui/blob/master/dist) dist folder into a MODULES DB. Loading it when the Gradle agent is hosted on a Linux machine causes no issues, but running Gradle from a Windows machine causes encoding issues. We primarily develop with MarkLogic inside a Docker image on a Windows host, so we've confirmed that the same command (using the same Gradle code and the same ML installation) works on the Linux side but not the Windows side.

Also not sure if this is something that can be fixed in the first place, but figured we should report it.

**To Reproduce**
1. Copy https://github.com/swagger-api/swagger-ui/blob/master/dist somewhere within an `ml-modules` directory that's exposable to an AppServer. (ours is at `ml-modules/ext/swagger`)
2. Navigate to the file in your browser (for us, `http://localhost:8011/ext/swagger/index.html`)
3. If done from Linux, file loads. If done from Windows, page should appear blank and two of the following errors appear in the console:

![image](https://user-images.githubusercontent.com/3514397/113720881-0ada5c00-96bd-11eb-816c-2c6b434096d1.png)

File has source content `^\x20-\x7EÀ-ž`, but shows up in the database as `^\x20-\x7EÃ€-Å¾` when loaded from Windows.

**Expected behavior**
We want to be able to enforce an encoding on the files and have the same command load the same file the same way, regardless of OS. I remembered reading that ML only supports UTF-8, but if there's a way to force it to convert back from the Windows encoding back to UTF-8 so that the file will load, that'd be great. If this is resolvable as "It's a Windows problem", we totally understand.

**Comment by rjrudin** [comment]
Try what's in #155 for forcing Gradle to use UTF-8 - seems like a similar problem.

**Comment by ahwitz** [comment]
Least painful resolution to a Windows encoding error I've ever seen. Cheers!
