### ISSUE TITLE
Gradle Groovy plugin MLCP

### ISSUE THREAD

**Issue by chenfiona** [marklogic-community/ml-gradle#586]
Please provide Solution Two in https://github.com/marklogic/java-client-api/issues/1295

**Comment by rjrudin** [comment]
I don't know what the referenced ticket is asking for. In case it's asking for ml-gradle to bundle a version of MLCP and provide OOTB MLCP tasks, that's not going to happen - the proper way to use MLCP via ml-gradle is via MlcpTask, and note that the only value there is a little bit of syntactic sugar - a user can always use JavaExec or even Exec to invoke MLCP.
