### ISSUE TITLE
Query options missing when having multiple REST-API servers

### ISSUE THREAD

**Issue by lifan0127** [marklogic-community/ml-gradle#587]
When setting up a ml-gradle project with two REST-API servers, I found that query options were not loaded for the secondary REST-API server.

To reproduce, create a new ml-gradle project using `mlNewProject` and then configure two REST-API servers:

![image](https://user-images.githubusercontent.com/7218193/116480963-531a1380-a850-11eb-91d3-62030a6db148.png)

Default REST-API server (rest-api-server.json):

```json
{
  "server-name": "%%NAME%%",
  "server-type": "http",
  "root": "/",
  "port": "%%PORT%%",
  "modules-database": "%%MODULES_DATABASE%%",
  "content-database": "%%DATABASE%%",
  "error-handler": "/MarkLogic/rest-api/error-handler.xqy",
  "url-rewriter": "/MarkLogic/rest-api/rewriter.xml",
  "rewrite-resolves-globally": true,
  "authentication": "basic"
}
```

Secondary REST-API server (rest-api-server-2.json):

```json
{
  "server-name": "%%NAME%%-2nd",
  "server-type": "http",
  "root": "/",
  "port": "%%mlRestPort2%%",
  "modules-database": "%%MODULES_DATABASE%%",
  "content-database": "%%DATABASE%%",
  "error-handler": "/MarkLogic/rest-api/error-handler.xqy",
  "url-rewriter": "/MarkLogic/rest-api/rewriter.xml",
  "rewrite-resolves-globally": true,
  "authentication": "basic"
}
```

Relevant gradle.properties:

```properties
mlAppName=ml-multi-server-search-options
mlRestPort=9900
mlRestPort2=9902
mlTestRestPort=9901
```

Upon deployment (`mlDeploy`), both REST-API servers were created:

![image](https://user-images.githubusercontent.com/7218193/116481323-f5d29200-a850-11eb-8768-afae83d62919.png)

The primary REST-API server can access the default query options (ml-multi-server-search-options-options.xml):

http://localhost:9900/v1/search?options=ml-multi-server-search-options-options

```xml
<search:response xmlns:search="http://marklogic.com/appservices/search" snippet-format="snippet" total="0" start="1" page-length="10">
  <search:metrics>
  <search:query-resolution-time>PT0.0006643S</search:query-resolution-time>
  <search:total-time>PT0.000824S</search:total-time>
  </search:metrics>
</search:response>
```

The secondary REST-API server returned "No configured options" error:

http://localhost:9902/v1/search?options=ml-multi-server-search-options-options

```xml
<error-response xmlns="http://marklogic.com/xdmp/error">
  <status-code>400</status-code>
  <status>Bad Request</status>
  <message-code>REST-INVALIDPARAM</message-code>
  <message>REST-INVALIDPARAM: (err:FOER0000) Invalid parameter: No configured options: ml-multi-server-search-options-options</message>
</error-response>
```

Indeed, no query options for server `%%NAME%%-2nd` in the module database:

![image](https://user-images.githubusercontent.com/7218193/116481617-8d37e500-a851-11eb-9a84-cb3c213e4959.png)

Thank you in advance for looking into this issue.

**Comment by rjrudin** [comment]
See https://github.com/marklogic-community/ml-gradle/wiki/How-modules-are-loaded#copying-search-options-to-additional-app-servers . ml-gradle is not aware of mlRestPort2 and whether or not REST extensions should be loaded into it, so you'll need to use a task as shown in that Wiki page. 

Closing, but please reopen if this doesn't address your need.

**Comment by lifan0127** [comment]
Hi @rjrudin , thanks for your prompt response. This is the issue I am facing.

Before today I didn't know that query options URIs are tied to individual servers. It makes sense now.
