### ISSUE TITLE
Exception due to missing annotations in PrepareBundlesTask when using Gradle 7.0

### ISSUE THREAD

**Issue by gku11ava** [marklogic-community/ml-gradle#588]
The following message is displayed when attempting to run a gradle task that has a dependency on mlPrepareBundlesTask. 
The error occurs with Gradle 7.0.  It does not occur with 6.0.1 or earlier.  I have not tested later versions of Gradle 6.

> Task :mlPrepareBundles FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Some problems were found with the configuration of task ':mlPrepareBundles' (type 'PrepareBundlesTask').
  - Type 'PrepareBundlesTask' property 'adminManager' is missing an input or output annotation.

    Reason: A property without annotation isn't considered during up-to-date checking.

    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.

    Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#missing_annotation for more details about this problem.
  - Type 'PrepareBundlesTask' property 'adminPassword' is missing an input or output annotation.

    Reason: A property without annotation isn't considered during up-to-date checking.

    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.

    Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#missing_annotation for more details about this problem.
  - Type 'PrepareBundlesTask' property 'adminUsername' is missing an input or output annotation.

    Reason: A property without annotation isn't considered during up-to-date checking.

    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.

    Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#missing_annotation for more details about this problem.
  - Type 'PrepareBundlesTask' property 'appConfig' is missing an input or output annotation.

    Reason: A property without annotation isn't considered during up-to-date checking.

    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.

    Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#missing_annotation for more details about this problem.
  - Type 'PrepareBundlesTask' property 'appDeployer' is missing an input or output annotation.

    Reason: A property without annotation isn't considered during up-to-date checking.

    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.

    Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#missing_annotation for more details about this problem.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/7.0/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1s
1 actionable task: 1 executed

**Comment by rjrudin** [comment]
Thanks - ml-gradle hasn't been tested yet on Gradle 7. I've created #589 to capture that and am tentatively targeting the 4.2 release for Gradle 7 support. I'll add a comment to this ticket as reference for one item that needs to be tested.
