### ISSUE TITLE
Please to HELP. Cannot disable Hadoop exception on MLCP GRADLE on Windows.

### ISSUE THREAD

**Issue by vnayfeld** [marklogic-community/ml-gradle#591]
I have hit a know problem of running MLCP Gradle Project on Windows.
It has been described by
[https://github.com/marklogic-community/ml-gradle/wiki/MarkLogic-Content-Pump-%28mlcp%29-and-Gradle#suppressing-hadoop-binary-messages-on-windows]

I have made code changes to resolve this problem, by following recommendation of that link.
I verified that code changes have been executed, however a Gradle still fails due to Exception of not finding Hadoop file.
Could you, please, help me figure out why proposed resolution does not work and how to run MLCP Gradle on Windows.

**Please see details below.**
I apologize for my short experience in Gradle and Groovy. However my Java development experience is deep enough.

1.  I made changes in my "build.gradle" following a section:
[https://github.com/marklogic-community/ml-gradle/wiki/MarkLogic-Content-Pump-%28mlcp%29-and-Gradle#suppressing-hadoop-binary-messages-on-windows]

> "Create a dummy lib\bin\winutils.exe file in your project
> Add the following to your task that extends MlcpTask:
> systemProperty "hadoop.home.dir", "$project.rootDir/lib"

2. Initial code changes followed an example from 
[https://github.com/marklogic-community/ml-gradle/wiki/Dynamically-creating-tasks]
**NOTE** I tried to copy literally a line **systemProperty "hadoop.home.dir", "$project.rootDir/lib"** it did not work.
Hence, I replaced it by the code I am familiar with:
		**System.setProperty ("hadoop.home.dir", "$project.rootDir\\lib")**

The code looks like;

- Subclass of com.marklogic.gradle.task.MlcpTask

  **class MlcpNoHadoopTask**  extends com.marklogic.gradle.task.MlcpTask {
	void IngestTask() {
		classpath = configurations.mlcp
		command = "IMPORT"
		database = mlAppConfig.contentDatabaseName
		output_collections = "sample-import"
		output_permissions = "rest-reader,read,rest-writer,update"
		output_uri_replace = ".*import,'/import'"
		logOutputUri = "/mlcp-log.txt"
		args = ["-input_file_path", "data/import"]
		**System.setProperty ("hadoop.home.dir", "$project.rootDir\\lib")**
	}
}

- Task  change to use a new Subclass
task importRdf(**type: MlcpNoHadoopTask**) {
	classpath = configurations.mlcp
	command = "IMPORT"
	database = mlAppConfig.contentDatabaseName
	input_file_path = "data/taxonomy.rdf"
	input_file_type = "rdf"
	output_uri_replace = ".*data,'/'"
	output_collections = "world-bank-topical-taxonomy"
	output_permissions = "rest-reader,read,rest-writer,update"
	port = mlAppConfig.restPort
	username=mlAppConfig.restAdminUsername
	password=mlAppConfig.restAdminPassword
	
}

I ran a command    **gradle -i importRdf. A task failed exactly with the message described in a WIKI sectrion.
```
2021-06-20 23:00:02 ERROR Shell:373 - Failed to locate the winutils binary in the hadoop binary path
java.io.IOException: Could not locate executable null\bin\winutils.exe in the Hadoop binaries.
```
All details in the attached log file. (please wrap the lines if an editor does not do it automatically). 
[importRdf_Subclass_log.txt](https://github.com/marklogic-community/ml-gradle/files/6688361/importRdf_Subclass_log.txt)

I added debug code to print values of "hadoop.home.dir", "$project.rootDir\\lib" into the log.
```
 println "FROM Task MlcpNoHadoopTask subtask of com.marklogic.gradle.task.MlcpTask"
		println "Root Directory Lib = " + "$project.rootDir\\lib"
		println "BEFORE SET Property hadoop.home.dir = " + System.getProperty("hadoop.home.dir")
		System.setProperty ("hadoop.home.dir", "$project.rootDir\\lib")
		println "AFTER SET Property hadoop.home.dir = " + System.getProperty("hadoop.home.dir")	
		def files = file(System.getProperty("hadoop.home.dir")).listFiles()   //.sort()
		println " Files in Directory listed below"
		files.each { File file ->
			if (file.isDirectory()) {
				println " *** $file.name/ ***"
			} else if (file.isFile()){
				println " *** $file.name ***"
			}
		}
		def filesBin = file(System.getProperty("hadoop.home.dir") + "\\bin").listFiles()
		println " Files in Directory /bin "
		filesBin.each { File file ->
			 if (file.isFile()){
				println " *** $file.name ***"
			}
		}
```

At first I put them into a method **void IngestTask()**
Nothing was printed to the Log, what meant that a new subclass *MlcpNoHadoopTask**  has not been called.

Therefore I refactored code by removing a Subclass and included a DoFirst task in the body of 
`task importRdf(type: com.marklogic.gradle.task.MlcpTask) `

Now Code looks like 

```
task importRdf(type: com.marklogic.gradle.task.MlcpTask) {
	classpath = configurations.mlcp
	command = "IMPORT"
	database = mlAppConfig.contentDatabaseName
	input_file_path = "data/taxonomy.rdf"
	input_file_type = "rdf"
	output_uri_replace = ".*data,'/'"
	output_collections = "world-bank-topical-taxonomy"
	output_permissions = "rest-reader,read,rest-writer,update"
	port = mlAppConfig.restPort
	username=mlAppConfig.restAdminUsername
	password=mlAppConfig.restAdminPassword
	
doFirst {
        println "Root Directory Lib = " + "$project.rootDir\\lib"  
	    println "BEFORE SET Property hadoop.home.dir = " + System.getProperty("hadoop.home.dir")
		System.setProperty ("hadoop.home.dir", "$project.rootDir\\lib")
		println "AFTER SET Property hadoop.home.dir = " + System.getProperty("hadoop.home.dir")			
		def files = file(System.getProperty("hadoop.home.dir")).listFiles()   //.sort()
  	    println " Files in Directory listed below"
        files.each { File file ->
            if (file.isDirectory()) {
                println " *** $file.name/ ***"
            } else if (file.isFile()){
                println " *** $file.name ***"
            } 
        }
		def filesBin = file(System.getProperty("hadoop.home.dir") + "\\bin").listFiles()
		println " Files in Directory /bin "
		filesBin.each { File file ->
             if (file.isFile()){
                println " *** $file.name ***"
            } 
        }
	}
	
}
```

I ran Gradle command again **gradle -i `importRdf.**`
It ended up with the same exception,
```
2021-06-20 23:00:02 ERROR Shell:373 - Failed to locate the winutils binary in the hadoop binary path
java.io.IOException: Could not locate executable null\bin\winutils.exe in the Hadoop binaries.
```

However, this time it printed to the log that 
hadoop.home.dir - was set and an empty "winutil.exe" is found in .../lib/bin path.

```

Root Directory Lib = C:\TutorialData\multi-project-deploy\mlcp-project\mlcp-project\lib
BEFORE SET Property hadoop.home.dir = null
AFTER SET Property hadoop.home.dir = C:\TutorialData\multi-project-deploy\mlcp-project\mlcp-project\lib
 Files in Directory listed below
 *** .classpath ***
 *** .project ***
 *** .settings/ ***
 *** bin/ ***
 *** build.gradle ***
 *** log4j.properties ***
 *** src/ ***
 Files in Directory /bin 
 *** winutils.exe ***


```

Below see the log file of this run.
[importRdf_DO_FIRST_log.txt](https://github.com/marklogic-community/ml-gradle/files/6688607/importRdf_DO_FIRST_log.txt)

**Comment by rjrudin** [comment]
It looks like the docs are a little out-of-date, as Gradle's JavaExec task (which MlcpTask extends) no longer includes "systemProperty" but instead has "systemProperties": 

https://docs.gradle.org/current/dsl/org.gradle.api.tasks.JavaExec.html#org.gradle.api.tasks.JavaExec:systemProperties

Here's an example of that syntax - I'll update the docs page too:

https://discuss.gradle.org/t/passing-system-properties-from-javaexec-task-doesnt-seem-to-work/1458

Note also that this is just suppressing a message. If the message is actually revealing an issue, then you should use the standalone MLCP distribution and not use MlcpTask, which is really just syntactic sugar vs using the regular MLCP distribution.

**Comment by rjrudin** [comment]
Based on the docs being updated, I'm assuming this can be closed. Please reopen if you still have an issue.

**Comment by vnayfeld** [comment]
@rjrudin. I am novice with this "issues" tool, so I am not sure how to re-open this issue, so I put direct reference to your name.

Unfortunately, you provided incorrect syntax for setting systemProperties 
systemProperties = ['hadoop.home.dir', '$project.rootDir/lib']
at 
[https://github.com/marklogic-community/ml-gradle/wiki/MarkLogic-Content-Pump-%28mlcp%29-and-Gradle#suppressing-hadoop-binary-messages-on-window]

Eventually, I made it working.  In the process, I stumbled through a few blocks.
Final syntax that works is:
systemProperties = [ "hadoop.home.dir"  :  "$project.rootDir\\lib" ]

Please note that final version contains:
1.  ":" instead of ",".      ---  This is critical because "," produces "ArrayList" instead of Map.
2.  $project.rootDir  should be inside DOUBLE QUOTE instead of SINGLE QUOTE. SINGLE QUOTE does not expand $project.rootDir to a "true" value of the PATH.

Neither I found updates on the page you mentioned
[https://discuss.gradle.org/t/passing-system-properties-from-javaexec-task-doesnt-seem-to-work/1458]

Below is Logging of successful run.
Instead of:

> Successfully started process 'command 'C:\Program Files\Java\jre1.8.0_281\bin\java.exe''
> 2021-06-21 13:47:57 ERROR Shell:373 - **Failed to locate the winutils binary in the hadoop binary path**
> java.io.IOException: Could not locate executable null\bin\winutils.exe in the Hadoop binaries.
> 	at org.apache.hadoop.util.Shell.getQualifiedBinPath(Shell.java:355)
> 	at org.apache.hadoop.util.Shell.getWinUtilsPath(Shell.java:370)
it produced
==============================================================
```
`Successfully started process 'command 'C:\Program Files\Java\jre1.8.0_281\bin\java.exe''
2021-06-29 12:05:10 INFO  LocalJobRunner:488 - Content type: XML
2021-06-29 12:05:11 INFO  ContentPump:236 - Job name: local_626402633_1
2021-06-29 12:05:11 INFO  FileAndDirectoryInputFormat:217 - Total input paths to process : 1
2021-06-29 12:05:12 INFO  RDFReader:1015 - Ingested 10000 triples from file:///C:/TutorialData/multi-project-deploy/mlcp-project/data/taxonomy.rdf
2021-06-29 12:05:12 INFO  RDFReader:1015 - Ingested 20000 triples from file:///C:/TutorialData/multi-project-deploy/mlcp-project/data/taxonomy.rdf
2021-06-29 12:05:12 INFO  RDFReader:1015 - Ingested 30000 triples from file:///C:/TutorialData/multi-project-deploy/mlcp-project/data/taxonomy.rdf
2021-06-29 12:05:12 INFO  LocalJobRunner:519 -  completed 100%
2021-06-29 12:05:13 INFO  LocalJobRunner:287 - com.marklogic.mapreduce.MarkLogicCounter: 
2021-06-29 12:05:13 INFO  LocalJobRunner:291 - INPUT_RECORDS: 326
2021-06-29 12:05:13 INFO  LocalJobRunner:291 - OUTPUT_RECORDS: 326
2021-06-29 12:05:13 INFO  LocalJobRunner:291 - OUTPUT_RECORDS_COMMITTED: 326
2021-06-29 12:05:13 INFO  LocalJobRunner:291 - OUTPUT_RECORDS_FAILED: 0
2021-06-29 12:05:13 INFO  LocalJobRunner:295 - Total execution time: 1 sec
:mlcp-project:importRdf (Thread[Execution worker for ':',5,main]) completed. Took 3.293 secs.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.8.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 6s
1 actionable task: 1 executed
Configuration Cache (C:\TutorialData\multi-project-deploy\.gradle\configuration-cache) removing files not accessed on or after Tue Jun 22 12:05:13 EDT 2021.
Configuration Cache (C:\TutorialData\multi-project-deploy\.gradle\configuration-cache) cleaned up in 0.0 secs.
VCS Checkout Cache (C:\TutorialData\multi-project-deploy\.gradle\vcs-1) removing files not accessed on or after Tue Jun 22 12:05:08 EDT 2021.
VCS Checkout Cache (C:\TutorialData\multi-project-deploy\.gradle\vcs-1) cleaned up in 0.001 secs.
```
`
