### ISSUE TITLE
Triggers defined in bundles are not deployed

### ISSUE THREAD

**Issue by nic-gibson** [marklogic-community/ml-gradle#592]
It appears that mlDeployTriggers does not depend on mlPrepareBundles leaving triggers defined in bundles unable to be deployed. 

This can be demonstrated by creating a bundle that only deploys a single trigger, a test project which uses it and running `gradle mlDeployTriggers`. 

A workaround is to add `mlDeployTriggers.dependsOn(mlPrepareBundles)` to the project using the bundle. Obviously, this is less than optimal.

**Comment by rjrudin** [comment]
Hmm. It would seem that every "mlDeploy*" task needs to depend on mlPrepareBundles, as a bundle can have any kind of resource in its ml-config directory.
