### ISSUE TITLE
Option UseConcMarkSweepGC deprecated

### ISSUE THREAD

**Issue by grtjn** [marklogic-community/ml-gradle#606]
In case of low heap, a suggestion is printed to enable CMS GC, but doing so causes Java to print the following warning:

> OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.

According to http://openjdk.java.net/jeps/291, the suggestion is to use UseG1GC instead..

**Comment by grtjn** [comment]
Whoops, this belongs to corb2 instead of ml-gradle. Can someone transfer this issue to corb2?

**Comment by hansenmc** [comment]
I don't have rights to transfer, but just opened a new one under CoRB https://github.com/marklogic-community/corb2/issues/173 you can close this one.

**Comment by grtjn** [comment]
thnx
