### ISSUE TITLE
com.marklogic.gradle.task.qconsole.ExportWorkspacesTask  fails to export database and server setting

### ISSUE THREAD

**Issue by lingtao-sa** [marklogic-community/ml-gradle#612]
The exported qconsole workspace xml are different between direct export and the above mlgradle task. 

That results in could not import the qconsole workspace properly.

**Describe the bug**
The following query property are missing from the ExportWorkspaceTask.

- listorder
- taborder
- database
- server
- database-name
- server-name
- optimize
<img width="634" alt="2022-03-28 06_20_08-Query Console - MarkLogic — Mozilla Firefox" src="https://user-images.githubusercontent.com/83944109/160297219-413f918c-f79f-4b7c-b86d-829e65bb1ca5.png">

**Comment by rjrudin** [comment]
Will be resolved via https://github.com/marklogic-community/ml-javaclient-util/pull/143  in ml-gradle 4.3.5
