### ISSUE TITLE
Incorporate Host Zone in properties-driven forest creation to ensure HA

### ISSUE THREAD

**Issue by hansenmc** [marklogic-community/ml-gradle#635]
The [properties-driven forest creation ](https://github.com/marklogic-community/ml-gradle/wiki/Creating-forests#properties-driven) currently does not take into account the Host Zone when generating the HA replica forests and assignment. 

For customers deployed across multiple data centers, for instance in multiple AWS Availability Zones, it is best to ensure that an HA replica forest is assigned to a host that is in a different Zone. This helps ensure HA if an entire Zone were to be lost. The remaining 2/3 of the cluster would have open replicas and the cluster could remain operational.

This is a common requirement and a best practice that we should look to support and make it easier to achieve. 

Several users have asked about how to do this in ml-gradle:
- https://stackoverflow.com/q/74645717/14419
- https://stackoverflow.com/q/61744739/14419

**Comment by rjrudin** [comment]
Going to leave this here in case it's been linked to, but re-opening it in ml-app-deployer - https://github.com/marklogic-community/ml-app-deployer/issues/461
