### ISSUE TITLE
Cannot set app server authentication to "digestbasic"

### ISSUE THREAD

**Issue by eaolson** [marklogic-community/ml-gradle#649]
When trying to change an app server's authentication method from "digest" to "digestbasic", I get the error:

```
An exception occurred applying plugin request [id: 'com.marklogic.ml-data-hub', version: '5.2.6']
> Failed to apply plugin [id 'com.marklogic.ml-data-hub']
   > No enum constant com.marklogic.client.ext.SecurityContextType.DIGESTBASIC
```

This is allowed through the REST API, because when I POST this to manage/v2/servers/{name}/properties, it changes as expected:
```
<http-server-properties xmlns="http://marklogic.com/manage">
  <authentication>digestbasic</authentication>
</http-server-properties>
```

I've changed to using "basic" instead.

I'm not sure if this is an ml-gradle issue or more for ml-javaclient-util, because it doesn't appear to be listed under [SecurityContextType](https://github.com/marklogic-community/ml-javaclient-util/blob/master/src/main/java/com/marklogic/client/ext/SecurityContextType.java) there.

**Comment by rjrudin** [comment]
I believe this is specific to DHF (you're using the DHF Gradle plugin), in that the mlStagingAuth / mlFinalAuth / mlJobAuth properties are used for two purposes:

1. To define the "authentication" property of an app server
2. To define what kind of authentication to use when connecting to MarkLogic

While "digestbasic" is a valid choice for 1, it is not a valid choice for 2 - a user must explicitly choose "basic" or "digest". 

I don't know if this has changed in the latest release of DHF, but one workaround is to modify the DHF server file to not use the e.g. "%%mlStagingAuth%%" token but rather either use a different property or just hardcode the value in there. 

If you run into further issues, please create the ticket in the marklogic-data-hub repository and/or create a Support ticket if you have a support contract.
