### ISSUE TITLE
Include example of loading namespaces in sample-project

### ISSUE THREAD

**Issue by tzejohn** [marklogic-community/ml-gradle#99]
The REST API has `config/namespaces`.  Is there any built-in functionality in ml-gradle to deploy this configuration?  I searched and did not see it in any of the existing code.

**Comment by rjrudin** [comment]
Yup - ml-javaclient-util has examples under src/test/resources. I'll convert this into a ticket for including an example in sample-project for it.

The way it works:

1. Create a file under src/main/ml-modules/namespaces - e.g. "sample.txt"
1. The name of the file minus the extension becomes the prefix, and the contents of the file become the namespace - so sample.txt is a 1-line file with e.g. "urn:sample:namespace" as the text of that single line

**Comment by tzejohn** [comment]
Perfect.  I have this working fine in my configuration now.

**Comment by rjrudin** [comment]
This feature is deprecated now in the Java Client, so closing this ticket.

**Comment by kefo** [comment]
When I try the mlgradle code now, I can see no evidence that a namespace was added, even though the mlgradle output says it has been added.   So I'm confused about this - is adding namespaces supported or deprecated?  If supported, did it change?  If deprecated, was it replaced?

**Comment by rjrudin** [comment]
According to the docs - http://docs.marklogic.com/REST/POST/v1/config/namespaces - the client REST API still supports it, but it's deprecated. The recommendation in the docs is to add the namespaces via the servers endpoint. So I'd use that instead. 

For evidence though with the deprecated way - check the /manage/v2/servers endpoint for your server to see if the namespaces are listed in the properties for the server.
